### ISSUE TITLE
Size field mismatch size of content downloaded

### ISSUE THREAD

**Issue by xybu** [OneDrive/onedrive-api-docs#492] opened 2016-12-26 09:22 UTC
I noticed that for some (not all) files in my OneDrive Personal account the size reported by the API is not consistent with the length of content actually downloaded, yet the SHA-1 hash values match.

For example, I have a JPEG file named `IMG_0100.JPG` whose `size` is 62671 bytes reported by API yet the downloaded file is only 57814 bytes. However, the API says the SHA-1 hash is `D4AE13DB398E5F51A1DCA6908212B2EF855AB04C` which matches the SHA-1 hash of the downloaded file. Because the hashes match, I think the file is downloaded properly and thus the file size reported by the OS is correct.

Follow-ups:
* I re-uploaded the downloaded file back to OneDrive yet value of size field of the returned Item does not change.
* Most such files seem MSOffice, PDF, or image files. But I don't have various types of files in my OneDrive.

Any idea why this happened?

I'm running Ubuntu 16.04 64-bit and using Python 3.5.

(Pasted the original issue here from onedrive-sdk-python repo.)

**Comment by ificator** [comment] 2016-12-29 16:47
Hi @xybu, this is definitely strange and obviously not expected. Can you share the `id` for one of the files that is exhibiting this behavior?

**Comment by xybu** [comment] 2016-12-30 04:09
So I have 157 files which exhibit this problem, and they are all .doc(x), .pdf, .jp(e)g files.

One example:

`D781730A6D2C6611!20520` (hwk5.pdf): This PDF file has 30012B yet the API says 35126B. However, the API gives the same SHA-1 hash as the Linux util `sha1sum` returns:
```
6f0ea82157e8ae813dccc4b71e9c3bdafa5a00e6  hwk5.pdf
```

**Comment by ificator** [comment] 2017-01-03 22:08
Hi @xybu I've confirmed that this is indeed due to a known issue that's been around for quite some time. I'm going to close this issue as a dupe, and you can follow the progress over at https://github.com/OneDrive/onedrive-api-docs/issues/123.

**Closed by ificator** 2017-01-03 22:08 UTC
Labels: bug
