### ISSUE TITLE
provision a user's OneDrive by requesting the root folder of the drive from Microsoft Graph

### ISSUE THREAD

**Issue by dtheodor** [OneDrive/onedrive-api-docs#530] opened 2017-03-02 13:53 UTC
According to a commit from a few days ago, it is possible to provision a user's OneDrive if the user doesn't already have one

https://github.com/OneDrive/onedrive-api-docs/commit/49dd4ab6d891022d3f9055b675d033d6c97177a9#diff-ec2bf10c5c4e9921fc21cb5e452ab0a1R86

>In some cases a work/school user may not have a `mySite` value returned.
This occurs when the account has not created their OneDrive for Business yet.
In this scenario, your app will need to use Microsoft Graph to provision the user's OneDrive by requesting the root folder of the drive from Microsoft Graph.

I'm trying to find out what this call is. I'm trying various combitations of GET and POST on `/users/<user-id>/drive/root`, but with no luck. Do you mind sharing?

**Comment by dtheodor** [comment] 2017-03-02 15:13
I was able to provision a user's OneDrive through a `GET https://graph.microsoft.com/v1.0/me/drive/root`, using a token retrieved from an authorization code. Although now I cannot reproduce it and get back a
```json
{
    "error" : {
        "innerError" : {...},
        "message" : "404 FILE NOT FOUND",
        "code" : "UnknownError"
    }
}
```

What I was looking for is to provision arbitrary users of a company through an app-only token by calling `GET https://graph.microsoft.com/v1.0/drives/user@company.com/root`, which fails with 
```json
{
    "error" : {
        "innerError" : {...},
        "message" : "The provided drive id appears to be malformed, or does not represent a valid drive.",
        "code" : "invalidRequest"
    }
}
```

**Comment by katahir** [comment] 2017-03-06 17:02
Hi Theodore,
This is a known issue. We currently don't support provisioning of users' OneDrives using an app-only token. The error message thrown in this case is indeed a little misleading. We will fix the error message in the short term, while we look to enable the provisioning scenario using app-only tokens.

**Comment by dtheodor** [comment] 2017-03-06 18:21
Ok. How about provisioning users' OneDrives without an app-only token? This could be possible in two ways:

1. a personal token where the user provisions his/her own drive
2. a personal admin token with permissions to control all site collections, where an admin can provision other users' OneDrives

Which of these is possible, and which API call can do this?

**Comment by katahir** [comment] 2017-03-06 21:32
Only the 1st one is currently enabled. You can acquire an app + user token and make a GET request to /drive endpoint and that should provision the OneDrive of the user if its not already provisioned. You can also make a HEAD request to /drive, which will not provision, but will just return the existing state i.e. 404 for drives not provisioned, and a 200 for provisioned ones.

**Comment by dtheodor** [comment] 2017-03-07 12:06
Thanks for the info.

Last question: There's an equivalent "provision Onedrives" API call in the sharepoint API, https://msdn.microsoft.com/en-us/library/dn790354.aspx#bk_ProfileLoaderCreatePersonalSiteEnqueueBulk , which I've tried to call using both app-only and user tokens, having enabled all permissions in my app, even made it my app a Company Administrator of the company I wanted to provision user drives through `Add-MsolRoleMember -RoleName "Company Administrator" -RoleMemberType ServicePrincipal ...`, but without success, I would always get back a 401 Access Denied. The API call works fine with username/password authentication though. Any idea if this API call works with tokens at all?

**Comment by katahir** [comment] 2017-03-07 17:11
Looking around, it seems like if your app is using app-only and has Sites.FullControl.All scope, then it should be able to provision using the above api. If that is not the case, please let me know and I can add a subject matter expert, as this is not my domain.

**Comment by dtheodor** [comment] 2017-03-08 12:09
I am not able to provision using the sharepoint API. I'm using an app-only token with these permissions

![app-permissions](https://cloud.githubusercontent.com/assets/1549648/23701932/a9c226d4-0401-11e7-853b-1366007b82e0.png)


Here's my request
```sh
curl -i -X POST "https://<tenant>-admin.sharepoint.com/_api/sp.userprofiles.profileloader.getprofileloader/createpersonalsiteenqueuebulk" \
     --header "Content-Type: application/json" \
     --header "Accept: application/json;odata=verbose" \
     --header "Authorization: Bearer <app-only token>" \
     --data '{"emailIDs": ["email@tenant.com"]}'
```     
And the response I get

Response headers

```
HTTP/1.1 403 Forbidden
Cache-Control: private, max-age=0
Transfer-Encoding: chunked
Content-Type: application/json;odata=verbose;charset=utf-8
Expires: Tue, 21 Feb 2017 09:54:42 GMT
Last-Modified: Wed, 08 Mar 2017 09:54:42 GMT
Server: Microsoft-IIS/8.5
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
X-SharePointHealthScore: 0
X-MSDAVEXT_Error: 917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+first+browse+to+the+web+site+and+select+the+option+to+login+automatically.
X-SP-SERVERSTATE: ReadOnly=0
DATASERVICEVERSION: 3.0
SPClientServiceRequestDuration: 39
SPRequestDuration: 98
X-AspNet-Version: 4.0.30319
SPRequestGuid: 46f8db9d-60df-3000-fb33-53f8750944ea
request-id: 46f8db9d-60df-3000-fb33-53f8750944ea
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.6223
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
X-MSEdge-Ref: Ref A: B846E63E7F674EA78F2DF4A1ECFC53DD Ref B: VIESCHEDGE0414 Ref C: Wed Mar  8 01:54:42 2017 PST
Date: Wed, 08 Mar 2017 09:54:42 GMT
```

Response body
```json
{
    "error": {
        "code": "-2147024891, System.UnauthorizedAccessException",
        "message": {
            "lang": "en-US",
            "value": "Access denied. You do not have permission to perform this action or access this resource."
        }
    }
}
```

I tried various variations of this call, just in case. I tried to
* use different root urls: `https://<tenant>.sharepoint.com`, `https://<tenant>-my.sharepoint.com`
* use the `X-FORMS_BASED_AUTH_ACCEPTED: f` header, this returned a 401 instead
* use a personal token of a tenant admin instead of the app-only token
* not use tokens at all, get rid of the `Authorization` header, and use the `Cookie` and `X-RequestDigest` headers. This is the only one that worked. The cookie value I get from my browser when I am logged in to Sharepoint Online with a tenant admin account, which is not really useful in any programmatic scenario.

Let me know if I'm doing anything wrong, otherwise if you can please get this issue to be seen by a domain expert that would be great

**Comment by katahir** [comment] 2017-03-08 17:32
I am interested in the call you make with https://tenant-my.sharepoint.com. That one theoretically should succeed. Can you provide the detail of that call, just like you did for the call to the -admin site? That will help tremendously.

**Comment by dtheodor** [comment] 2017-03-08 21:14
Here it is:

Request
```sh
curl -i -X POST "https://<tenant>-my.sharepoint.com/_api/sp.userprofiles.profileloader.getprofileloader/createpersonalsiteenqueuebulk" \
     --header "Content-Type: application/json" \
     --header "Accept: application/json;odata=verbose" \
     --header "Authorization: Bearer <app-only token?" \
     --data '{"emailIDs": ["name@tenant.com"]}'
```
Response
```
HTTP/1.1 403 Forbidden
Cache-Control: private, max-age=0
Transfer-Encoding: chunked
Content-Type: application/json;odata=verbose;charset=utf-8
Expires: Tue, 21 Feb 2017 21:07:50 GMT
Last-Modified: Wed, 08 Mar 2017 21:07:50 GMT
Server: Microsoft-IIS/8.5
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
X-SharePointHealthScore: 0
X-MSDAVEXT_Error: 917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+first+browse+to+the+web+site+and+select+the+option+to+login+automatically.
X-SP-SERVERSTATE: ReadOnly=0
DATASERVICEVERSION: 3.0
SPClientServiceRequestDuration: 53
SPRequestDuration: 266
X-AspNet-Version: 4.0.30319
SPRequestGuid: cb1edc9d-9022-3000-fb33-51f43a304cc2
request-id: cb1edc9d-9022-3000-fb33-51f43a304cc2
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.6302
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
X-MSEdge-Ref: Ref A: 84C851D21F91482195C6B8E14A2A4097 Ref B: AMS04EDGE0317 Ref C: Wed Mar  8 13:07:50 2017 PST
Date: Wed, 08 Mar 2017 21:07:50 GMT
```
```json
{
   "error":{
      "code":"-2147024891, System.UnauthorizedAccessException",
      "message":{
         "lang":"en-US",
         "value":"Access denied. You do not have permission to perform this action or access this resource."
      }
   }
}
```

**Comment by bigmethos** [comment] 2017-04-13 22:43
I have the exact same problem running this endpoint. I have confirmed I have Sites.FullControl.All. Just wondering if there is anything else we can try?

**Comment by maps2002** [comment] 2017-05-08 17:42
Hi @katahir, Hi all,

For CSP Partners, using the Authorization flow and Pre-Consent App described here: https://developer.microsoft.com/en-us/graph/docs/authorization/auth_cloudsolutionprovider
how am I able to trigger the provisioning using an API?

I tried with an App-Only but I get a 404 - message=User's mysite not found.
For an App + User token I get a 400 - message=Current authenticated context is not valid for this request.

I also suppose that for a CSP Partner the direct call to the SharePoint provisioning API is off-limits?

How can I make this work using the CSP Partner credentials?

Thank you

**Comment by jmacneill** [comment] 2017-07-11 15:46
I'm having the same issue.  However, my code started working on July 7, 2017 and then it stopped working when I tried it today, July 11, 2017.  I just had our tenant admin use the consent URL again just to make sure the app's permissions didn't somehow get "squeezed".

**Comment by jmacneill** [comment] 2017-07-11 16:00
Here's my code:

Imports System.IO
Imports System.Web.Script.Serialization

Module Module1
    Private dtAccessToken As DateTime = "1/1/1900"
    Private strAccessToken As String = ""
    Private strUploadFile As String = "C:\Applications\OneDrive\test.pdf"
    Private strUserName As String = "REDACTED"
    Private strTokenURL As String = "https://login.microsoftonline.com/REDACTED/oauth2/v2.0/token"
    Private strAppSecret As String = "client_id=REDACTED&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&client_secret=REDACTED&grant_type=client_credentials"

    Sub Main()
        GetAccessToken()

        Dim driveID As String = GetDriveID(strAccessToken, strUserName)
        Dim strURL As String = "https://graph.microsoft.com/v1.0/drives/" & driveID & "/root:/test.pdf:/createUploadSession"
        Dim rsp As String = ""
        Dim wc As New Net.WebClient()

        wc.Headers.Add("Authorization", "Bearer " & strAccessToken)
        wc.Headers.Add("Content-Type", "application/json")

        rsp = wc.UploadString(strURL, "POST", "{""item"": {""@microsoft.graph.conflictBehavior"": ""rename""}}")

        Dim jss As New JavaScriptSerializer
        Dim objRsp As Object = jss.Deserialize(Of Object)(rsp)
        Dim strUploadUrl As String = ""

        If objRsp.TryGetValue("uploadUrl", strUploadUrl) Then
            Dim strm As New IO.FileStream(strUploadFile, FileMode.Open)
            Dim iLen As Integer = strm.Length
            Dim byt(iLen) As Byte

            strm.Read(byt, 0, strm.Length)

            Dim wr As Net.HttpWebRequest = Net.WebRequest.Create(strUploadUrl)

            wr.ContentLength = iLen
            wr.Headers.Add("Content-Range", "bytes 0-" & iLen - 1 & "/" & iLen)
            wr.Method = "PUT"

            Console.WriteLine("bytes 0-" & iLen - 1 & "/" & iLen)

            Dim rs As IO.Stream = wr.GetRequestStream
            rs.Write(byt, 0, iLen)

            Dim rspe As Net.WebResponse = wr.GetResponse

            rs.Close()
        End If
    End Sub

    Private Sub GetAccessToken()
        Dim wc As New Net.WebClient()

        wc.Headers.Add("Content-Type", "application/x-www-form-urlencoded")

        Dim strReturn = wc.UploadString(strTokenURL, strAppSecret)
        Dim jss As New JavaScriptSerializer
        Dim objRet As Object = jss.Deserialize(Of Object)(strReturn)

        strAccessToken = objRet("access_token").Replace(vbCrLf, "").Replace(vbNewLine, "")
        dtAccessToken = Now()
    End Sub

    Private Function GetDriveID(strToken As String, strUser As String) As String
        Dim strDriveID As String = ""

        Try
            Dim wc As New Net.WebClient()

            wc.Headers.Add("Authorization", "Bearer " & strToken)

            Dim strResponse As String = wc.DownloadString("https://graph.microsoft.com/v1.0/users/" & strUser & "/drives")
            Dim jss As New JavaScriptSerializer
            Dim objContents As Object = jss.Deserialize(Of Object)(strResponse)

            For Each obj As Dictionary(Of String, Object) In objContents("value")
                Dim strContent As Object = Nothing

                If obj.TryGetValue("id", strContent) Then
                    strDriveID = obj.Item("id")
                End If
            Next
        Catch ex As Exception

        End Try

        Return strDriveID
    End Function

End Module

**Comment by suniljalahalli** [comment] 2017-10-05 17:07
I am also facing same issue. When I call provision one drive endpoint I get access denied. Please let me know if anyone got solution on this.

**Comment by kirill-sh** [comment] 2018-01-26 13:34
Are there any additional conditions for making automatic provisioning to work?

I make folowing steps:

1. Create user and assign Office 365 Enterprise E5 license

2. Using the Microsoft Graph Explorer I make request for drive (under user credential) with Files.ReadWrite.All permission

<pre>GET https://graph.microsoft.com/v1.0/me/drive</pre>

<pre>HTTP/1.1 404 Not Found
{
  "error": {
    "code": "ResourceNotFound",
    "message": "User's mysite not found.",
    "innerError": {
      "request-id": "999e9803-e27e-4087-91e5-e60efc48f8ba",
      "date": "2018-01-26T13:23:03"
    }
  }
}</pre>

<pre>GET https://graph.microsoft.com/v1.0/me/drive/root</pre>

The same response.

**Comment by lockelost** [comment] 2018-04-13 21:53
I'm having the same situation with 403 error.
The same setting for the tenant and Azure app, but one works the other throws 403.
Anyone succeeded?

> X-MSDAVEXT_Error: 917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+first+browse+to+the+web+site+and+select+the+option+to+login+automatically.

**Comment by mhtsharma9** [comment] 2018-05-18 12:01
Exact same issue here.
Does anyone found the solution?
refer my [question](https://stackoverflow.com/questions/50405051/error-while-accessing-onedrive-users-mysite-not-found).

**Comment by patrick-rodgers** [comment] 2018-08-30 20:02
Similar [issue here](https://stackoverflow.com/questions/51987591/auto-create-user-drive-using-delegated-permissions-and-microsoft-graph) and also verified it does not work using the graph explorer with either user's id or UPN as the segment path to drive. All requests result in 404.

**Comment by garrytrinder** [comment] 2019-09-18 22:45
I'm hitting this same issue when posting XML to Client.svc to mimic CSOM call in the Office 365 CLI https://github.com/pnp/office365-cli/issues/929 

At first I thought it might have been a licensing issue with the user account passed in but I've proved that this is also not the case.

@patrick-rodgers any news on this from your side?

**Comment by wobba** [comment] 2019-12-12 07:18
I believe this is due to the backend call checking if the user is a Profile Admin, something probably working explicitly with basic auth, but not a grant available being passed on via AAD.

**Comment by vaskovasilev** [comment] 2020-10-25 15:04
Hello all. I have the same problem while using microsoft drive explorer written on javascript. I am using personal account and have one drive basic. 
As far as i can understand, this javascript is useless for such scenario ?

**Comment by patrick-rodgers** [comment] 2023-02-17 20:21
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:21 UTC
Labels: automation:Closed
