### ISSUE TITLE
Got 404 response when using Delta API to sync changes

### ISSUE THREAD

**Issue by allen1759** [OneDrive/onedrive-api-docs#1476] opened 2021-04-08 06:33 UTC
#### Category
- [ ] Question
- [ ] Documentation issue
- [X] Bug

#### Expected or Desired Behavior

We use this endpoint `https://api.onedrive.com/v1.0/drive/items/root/view.delta` to GET delta on OneDrive.

And specify value `200` with the `top` query parameter,  start with no `token` parameter is given.

We were able to retrieve first 200 changes from OneDrive and get next token in `@delta.token` field, and use the new token to get next 200 changes, and so on.

But after about 80 rounds, with the same endpoint, the same top parameter, and a different delta token, we received a `404 Not Found` response.

The response body with JSON format:
```json
{
    "error": {
        "code": "itemNotFound",
        "localizedMessage": "That item seems to be missing. Someone may have deleted or moved the item, or you may not have permission to view it.",
        "message": "Item does not exist"
    }
}
```

#### Observed Behavior

We think that our service should continue calling this delta API with next token until we got no changes or no `@delta.token` / `@delta.nextLink` returned.

We do receive `@delta.token` / `@delta.nextLink` and `value` with non-empty list from OneDrive server, so it suppose to provide another 200 (or less if it is the latest feed) changes at this delta API request.

> Please also provide the following response headers corresponding to your request(s):
- Date:
  - Thu, 08 Apr 2021 02:56:18 GMT
- request-id: 
  - We cannot find any request-id in response header / body, is there anything else we can provide to help diagnose ?
- SPRequestGuid
  - We have this problem in ODP, hasn't been reproduced in ODB yet.

##### Delta API request - 1 (regular)

```
GET https://api.onedrive.com/v1.0/drive/items/root/view.delta?top=200&token=aTE09NjM3NTM0NDUwNTcyMjM7SUQ9Qzg0NDZFNThGRUE1QkQ1RSExMDc7TFI9NjM3NTM0NDczNzQzMzM7RVA9MjA7U0k9NjU7RExFUD0wO0xJRD0xOTU0OTE7RkQ9VHJ1ZTtCVT1UcnVlO1NHPTE7U089MjtQST0z
```
Request:
```
Authorization:  Bearer XXX
```
Response `200 OK`:
```
Cache-Control:              no-store
Via:                        1.1 DM5SCH102222121 (wls-colorado)
Content-Length:             346698
Content-Type:               application/json; odata.metadata=minimal
Vary:                       Accept,Accept-Language,Authorization,Prefer
P3P:                        CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
X-WLSPROXY:                 DM5SCH102222121
MS-CV:                      GUOuvNFHzUa31Da+TkV+ng.0
X-MSNSERVER:                SN4PPFAFB88AAB2
Strict-Transport-Security:  max-age=31536000; includeSubDomains
OData-Version:              4.0
X-AsmVersion:               UNKNOWN; 19.646.319.2010
X-MSEdge-Ref:               Ref A: C92A5F86DB1745BB8407054928779B05 Ref B: TPE31EDGE0517 Ref C: 2021-04-08T02:56:18Z
Date:                       Thu, 08 Apr 2021 02:56:18 GMT
{
    "@delta.token": "aTE09NjM3NTM0NDUwNTcyMjM7SUQ9Qzg0NDZFNThGRUE1QkQ1RSExMDc7TFI9NjM3NTM0NDczNzg3MjA7RVA9MjA7U0k9NjU7RExFUD0wO0xJRD0xOTUyNzE7RkQ9VHJ1ZTtCVT1UcnVlO1NHPTE7U089MjtQST0z",
    "@odata.context": "https://api.onedrive.com/v1.0/$metadata#drives('me')/items",
    "@odata.nextLink": "https://api.onedrive.com/v1.0/drives('me')/items('root')/view.delta?$top=200&token=aTE09NjM3NTM0NDUwNTcyMjM7SUQ9Qzg0NDZFNThGRUE1QkQ1RSExMDc7TFI9NjM3NTM0NDczNzg3MjA7RVA9MjA7U0k9NjU7RExFUD0wO0xJRD0xOTUyNzE7RkQ9VHJ1ZTtCVT1UcnVlO1NHPTE7U089MjtQST0z",
    "value": [
        XXX
    ]
}
```

##### Delta API request - 2 (problematic)

```
GET https://api.onedrive.com/v1.0/drive/items/root/view.delta?top=200&token=aTE09NjM3NTM0NDUwNTcyMjM7SUQ9Qzg0NDZFNThGRUE1QkQ1RSExMDc7TFI9NjM3NTM0NDczNzg3MjA7RVA9MjA7U0k9NjU7RExFUD0wO0xJRD0xOTUyNzE7RkQ9VHJ1ZTtCVT1UcnVlO1NHPTE7U089MjtQST0z
```
Request:
```
Authorization:  Bearer XXX
```
Response `404 Not Found`:
```
Via:                        1.1 SN3PPFAC21AFD31 (wls-colorado)
Content-Length:             204
Content-Type:               application/json
P3P:                        CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
X-WLSPROXY:                 SN3PPFAC21AFD31
MS-CV:                      EMrrDpe8xka2LpOS86SgJA.0
X-MSNSERVER:                SN4PPFC8874352E
Strict-Transport-Security:  max-age=31536000; includeSubDomains
X-QosStats:                 {"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}
X-ThrowSite:                39d6.d19e
X-AsmVersion:               UNKNOWN; 19.646.319.2010
X-MSEdge-Ref:               Ref A: CA62F7191C794E9780887483BE6E568B Ref B: TPE31EDGE0416 Ref C: 2021-04-08T02:56:22Z
Date:                       Thu, 08 Apr 2021 02:56:23 GMT
{
    "error": {
        "code": "itemNotFound",
        "localizedMessage": "That item seems to be missing. Someone may have deleted or moved the item, or you may not have permission to view it.",
        "message": "Item does not exist"
    }
}
```

#### Steps to Reproduce

Use cURL here to reproduce the problem.

1. send regular delta API request

```
curl -X GET 'https://api.onedrive.com/v1.0/drive/items/root/view.delta?top=200&token=aTE09NjM3NTM0NDUwNTcyMjM7SUQ9Qzg0NDZFNThGRUE1QkQ1RSExMDc7TFI9NjM3NTM0NDczNzQzMzM7RVA9MjA7U0k9NjU7RExFUD0wO0xJRD0xOTU0OTE7RkQ9VHJ1ZTtCVT1UcnVlO1NHPTE7U089MjtQST0z' \
     -H 'Authorization: Bearer XXX'
```
This request return `value` and `@delta.token` normally.

2. send problematic delta API request

```
curl -X GET 'https://api.onedrive.com/v1.0/drive/items/root/view.delta?top=200&token=aTE09NjM3NTM0NDUwNTcyMjM7SUQ9Qzg0NDZFNThGRUE1QkQ1RSExMDc7TFI9NjM3NTM0NDczNzg3MjA7RVA9MjA7U0k9NjU7RExFUD0wO0xJRD0xOTUyNzE7RkQ9VHJ1ZTtCVT1UcnVlO1NHPTE7U089MjtQST0z' \
     -H 'Authorization: Bearer XXX'
```
This request return `404` and `itemNotFound` error code.

##### Notes

* Re-sending the Step 1. delta API request will get another token, which is different to the token used in the Step 2. delta API. However, every token we receive from Step 1. delta API could all used to reproduce the issue.

* We also tried to restart this continuous API call (begin another delta API with no token is given), the problem can also be reproduced with different token.

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by zachzi** [comment] 2021-04-09 00:31
Thank you for the detailed issue description! We're investigating this issue and will respond back once we have more information.

**Comment by zachzi** [comment] 2021-04-09 01:09
Since it looks like you can reproduce the issue, could you go to: https://onedrive.live.com/?v=traceme - this will collect a diagnostic trace of the request from the service's perspective. Please make sure you are signed in with the same Microsoft account you will use to reproduce the failing delta request.

Steps:
1) Start a new trace with everything selected:
![image](https://user-images.githubusercontent.com/8701984/114114056-d91bed80-9894-11eb-83a3-314a8d4b0eb8.png)

2) Wait ~1 minute for the trace to begin.
3) Re-run the failing delta API call.
4) Save the paths under the "Please provide this value to your OneDrive customer support agent" text.

**Comment by allen1759** [comment] 2021-04-09 01:21
Sure! We'll work with the owner of failing OneDrive account to trace the delta API call, it may take some time.

Thanks for your help.

**Comment by allen1759** [comment] 2021-04-14 02:14
Hi @zachzi ,

Here is our trace ID,

Calls on my data:
C8446E58FEA5BD5E\2021-04-13_183700

Calls I make:
C8446E58FEA5BD5E\2021-04-13_183706


The latest successful API call used the `token` parameter with value `aTE09NjM3NTM4OTg1MDIxODc7SUQ9Qzg0NDZFNThGRUE1QkQ1RSExMDc7TFI9NjM3NTM5NjE0ODg1MTM7RVA9MjA7U0k9MTk7RExFUD0wO0xJRD0xOTU0Mzk7RkQ9VHJ1ZTtCVT1UcnVlO1NHPTE7U089MjtQST0z`.

And can be reproduced by this cURL command:
```
curl -X GET 'https://api.onedrive.com/v1.0/drive/items/root/view.delta?top=200&token=aTE09NjM3NTM4OTg1MDIxODc7SUQ9Qzg0NDZFNThGRUE1QkQ1RSExMDc7TFI9NjM3NTM5NjE0ODg1MTM7RVA9MjA7U0k9MTk7RExFUD0wO0xJRD0xOTU0Mzk7RkQ9VHJ1ZTtCVT1UcnVlO1NHPTE7U089MjtQST0z' \
     -H 'Authorization: Bearer XXX'
```


The following problematic API call use the `token` retrieve from response of previous API call, which is `aTE09NjM3NTM4OTg1MDIxODc7SUQ9Qzg0NDZFNThGRUE1QkQ1RSExMDc7TFI9NjM3NTM5NjE0ODk4OTc7RVA9MjA7U0k9MTk7RExFUD0wO0xJRD0xOTUyMzY7RkQ9VHJ1ZTtCVT1UcnVlO1NHPTE7U089MjtQST0z`.

Can be reproduced by this cURL command:
```
curl -X GET 'https://api.onedrive.com/v1.0/drive/items/root/view.delta?top=200&token=aTE09NjM3NTM4OTg1MDIxODc7SUQ9Qzg0NDZFNThGRUE1QkQ1RSExMDc7TFI9NjM3NTM5NjE0ODk4OTc7RVA9MjA7U0k9MTk7RExFUD0wO0xJRD0xOTUyMzY7RkQ9VHJ1ZTtCVT1UcnVlO1NHPTE7U089MjtQST0z' \
     -H 'Authorization: Bearer XXX'
```

**Comment by zachzi** [comment] 2021-04-15 22:27
Thanks @allen1759! We'll take a look at those traces and get back to you.

**Comment by zachzi** [comment] 2021-04-17 02:19
Quick update: we believe we have identified the issue and are investigating a fix.

**Comment by allen1759** [comment] 2021-04-19 09:12
Hi @zachzi ,

Good to hear that you can identify the problem!

Is any information you can provide to specify this issue? The account owner said that Microsoft OneDrive support cannot help to find the root cause. And is it possible to provide an estimated fix time in regular? :)

Many thanks!

**Comment by zachzi** [comment] 2021-04-20 04:32
Hi @allen1759,

We have checked in a fix, and that will deploy in the next 1-2 weeks. The issue was that the account owner shared some items with a Microsoft account that had since been deleted. When evaluating the permissions for these items during the delta API call, we were hitting an error since we could not look up the deleted user. The fix will address this.

Thanks!

**Comment by allen1759** [comment] 2021-04-20 05:51
Hello @zachzi ,

Glad to hear that you will fix the issue so soon! Your comments are useful to our developer team. 🙏

Thank you.

**Comment by zachzi** [comment] 2021-04-30 20:32
Hi @allen1759, it looks like this fix has been deployed now.

Thanks again for reporting this issue and all your help investigating it!

**Comment by allen1759** [comment] 2021-05-03 06:26
Hi @zachzi ,

Thank you for confirming the deployment!

**Comment by chackman** [comment] 2021-05-07 17:30
Thank you! 
allen1759 - please respond if there are any issues. Tagged this so that our bot will notify and then auto-close this if there are no further issues.

**Closed** 2021-05-27 20:00 UTC
Labels: Needs: Author Feedback, no-recent-activity
