### ISSUE TITLE
[Question] difference for If-Match header for personal and business

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#131] opened 2015-06-08 23:08 UTC
Few clarification over If-Match Header 

1) OneDrive for Business
DELETE /drive/items/<item-id>
If-Match: * 

response 204. getting deleted

2) OneDrive for personal
DELETE /drive/items/<item-id>
If-Match: *

repsonse error code 400 with "code: invalidArgument | message: Malformed If-Match header"

why this different behaviour, what values can If-Match can take?

**Comment by ankit-ankuagrawal** [comment] 2015-06-08 23:10
same for moving and deleting file/folder

**Comment by aclev** [comment] 2015-06-08 23:27
Hi @ankit-ankuagrawal 
It looks like there is a bug with our precondition headers.  The OneDrive for Business response is the expected behavior for both personal and business. 
Thanks for noticing, we are working on a fix now.

**Comment by aclev** [comment] 2015-08-11 17:39
Hey @ankit-ankuagrawal This should be fixed now, can you confirm that it works?
Thanks again for reporting the bug!

**Closed** 2015-08-17 18:24 UTC
Labels: bug
