### ISSUE TITLE
Receiving 401 when upload a .swf to onedrive for business

### ISSUE THREAD

**Issue by verybada** [OneDrive/onedrive-api-docs#533] opened 2017-03-06 03:36 UTC
Hi,

I got 401 {"error":{"code":"unauthenticated","message":"The caller is not authenticated."}}  during upload a hahaha.swf to my onedriveforbusiness account.  Here are my results
```
PUT https://xxxxxx-my.sharepoint.com/_api/v2.0/me/drive/items/01P6SIEXPAL7XS5CPJY5ALS3OHAZOYJ7XO/children/hahaha.swf/content params={'@name.conflictBehavior': 'fail'},headers={}
21593/21593 transferred
"PUT /_api/v2.0/me/drive/items/01P6SIEXPAL7XS5CPJY5ALS3OHAZOYJ7XO/children/hahaha.swf/content?%40name.conflictBehavior=fail HTTP/1.1" 401 None
>>>>>>>> {"error":{"code":"unauthenticated","message":"The caller is not authenticated."}}
```

it will be good when I change the extension as .sw_
```
PUT https://xxxxxx-my.sharepoint.com/_api/v2.0/me/drive/items/01P6SIEXPAL7XS5CPJY5ALS3OHAZOYJ7XO/children/hahaha.sw_/content params={'@name.conflictBehavior': 'fail'},headers={}
21593/21593 transferred
```

**Comment by katahir** [comment] 2017-03-06 21:37
@verybada Currently this limitation is by design. If NoScript feature is enabled on the site, SharePoint will not allow uploading an .swf file. You can try this using the UI. However, we are looking to somewhat relax/lift this restriction in the near future.

**Comment by katahir** [comment] 2017-06-15 17:23
@verybada We have checked in a fix to ensure this works now. Can you please confirm if this is no longer an issue for you?

**Closed** 2017-06-22 17:34 UTC
Labels: bug
