### ISSUE TITLE
wrong HTTP header in downloading file

### ISSUE THREAD

**Issue by isac322** [OneDrive/onedrive-api-docs#482] opened 2016-12-03 17:21 UTC
first, sorry for my poor english. :(

I wanted to download a file with original name by only id string.

so I followed [official download doc](https://dev.onedrive.com/items/download.htm) and found out that if send GET request to download URL, recieved with 302, the response header has _Content-Disposition_ and it contains file name (!!!).
but I found two bugs.

1. double escaped name
- example : **Content-Disposition: attachment; filename\*=UTF-8''%5b%25EC%2588%2598%25EC%25A0%2595%5d%2520vol.5.mp3**

I think it's minor but... it actually means **[수정] vol.5.mp3** in korean. but as you can try ([online URL decoder/encoder](http://meyerweb.com/eric/tools/dencoder/)), example is double escaped.
I guess that this caused by name saving mechanism. but if Onedrive should send single escaped name, it would be very convenient to non-ASCII people...

2. totally wrong name
- example : **Content-Disposition: attachment; filename\*=UTF-8''%252f..txt**

I this it's major bug. original name is **%2f%2e.txt**. I know this is very rare case, but server treat the name as non-ASCII despite full ASCII string. and even though it could consider as non-ASCII, server gives totally wrong string.

finally I decided to get name and download URL from getting metadata. but I wish these were fixed.
thanks!

**Comment by ificator** [comment] 2016-12-14 20:25
Hi @isac322 - are you still seeing this behavior. I tried to repro and was unable, and there's definitely been some work going on in this area that could have inadvertently fixed the issue. Let me know if you're still having problems and we can try to drill in further.

**Comment by isac322** [comment] 2016-12-15 08:06
thanks @ificator ! but nothing has changed. :(

**Comment by ificator** [comment] 2016-12-15 17:07
Thanks for following up. I have a few questions to help try and narrow down what's going on:
1. Is this for the Consumer or Business endpoint? I'm guessing consumer but I want to make sure.
2. Can you confirm the name in the metadata is `name=[수정] vol.5.mp3`?
3. A dump of the request / response headers would allow me to make sure my repro attempt was equivalent. You do not have to provide the actual URL being hit, the headers will be sufficient.

**Comment by isac322** [comment] 2016-12-16 10:12
1. consumer

2. Response of [Getting metadata of item](https://dev.onedrive.com/items/get.htm) request contains `"name":"[\uc218\uc815] vol.5.mp3"` (which is same as `[수정] vol.5.mp3` if decoded ([online Unicode converter](https://www.branah.com/unicode-converter)))

3.
- first request
```
GET https://api.onedrive.com/v1.0/drive/items/{Item-ID}/content HTTP/1.1
host: api.onedrive.com
accept-encoding: gzip
authorization: bearer EwAYA61DBAAUGCCXc8wU....
```

- first response
```
HTTP/1.1 302 Found
Content-Length: 0
Location: https://public-bn1305.files.1drv.com/y3mptgQ3ZRYDAQz2PVfKL5hIfaGlNDV7C2JANIklzqntZKxoGBN2DXINAkT4fQ8sZPYoRXjUH3Tx-H13UByIcBEiC2uCacXPO25boiWtRcWcLRhJ7hPVPJA-iH0jRmOenHkEIeUInryLVNFlcHN5kIGyrbqjOcMP-OTsF6HDlJ0k0aToLxf3gsG96Drr_antZvjpRRXw5cfm9SSuCyYkH9gOpiJkBWtLGQ1TXIP5r0WY8dtCkpHI3npOnXz1zU83iYw/[%EC%88%98%EC%A0%95]%20vol.5.mp3
Server: Microsoft-IIS/8.5
P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
X-MSNSERVER: BN2BAP98358D9CC
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-AsmVersion: UNKNOWN; 11.1.0.0
X-MSEdge-Ref: Ref A: 373ED98A746C4E77B15270685D378BB8 Ref B: B97A886E9182DF299ABE55CBD18E61F9 Ref C: Fri Dec 16 01:48:53 2016 PST
Date: Fri, 16 Dec 2016 09:48:52 GMT
```

- second request
```
GET https://public-bn1305.files.1drv.com/y3mIEW5v_Wcmm33qIyr9wI8BcL_2xmNyrMrQdM0i11Ae1d8Xd9_BAKuT4-nIXKoGZCPxMtYfKKy4GP-k1wbjxylerA9rc1GGKe_U6bp4NgaXRAYyDmGJ-YsGdsWCy_LQm3MwFw721O-HoPUgSM5vnM0FU2GYv0zq_Gi4Ev5dK0ZekDrLqPvm6MjFIVICitJCpRu56-KDNhCMajpH-sFYMcYGlTYtSy-rOPewh3wwFOZlMOaungvAN68C2RJ83j-cd2S/%5B%25EC%2588%2598%25EC%25A0%2595%5D%2520vol.5.mp3 HTTP/1.1
host: public-bn1305.files.1drv.com
accept-encoding: gzip
```

- second response
```
HTTP/1.1 200 OK
Cache-Control: public
Content-Length: 59254808
Content-Type: audio/mpeg
Content-Location: https://public-bn1305.files.1drv.com/y3m__vhVBcNYu3QbHC3v8WKZpfGOnZaIVKr67cXLkzAceY0vsfTSYQcicYorR0Oh4eDTcqHSVanfVkcowjtxg3_XW6Bei8lY4DCr-VsOPDV4TDXs7MIRrRCz1fFSjQiutvCQx7D0HlfZUN0Hd2R8S3gjhQeqotpeNXeHTfBK2fGWDX1z0aKh_vDVq0VaJLheaGUaHueTwkhujO9gUGhJnnpfNV5TeJjsvMWZnBlObCTI7Y
Expires: Thu, 16 Mar 2017 09:59:26 GMT
Last-Modified: Sun, 24 Jul 2016 04:25:59 GMT
Accept-Ranges: bytes
ETag: aRDRGRDgyQ0E2REY5NkE0NyEyNDk5OC4x
Server: Microsoft-IIS/8.5
P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
X-MSNSERVER: BN2BAP64238E8BE
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-SqlDataOrigin: S
CTag: aYzpENEZEODJDQTZERjk2QTQ3ITI0OTk4LjI1Nw
X-PreAuthInfo: rv;poba;
Content-Disposition: attachment; filename*=UTF-8''%5b%25EC%2588%2598%25EC%25A0%2595%5d%2520vol.5.mp3
X-Content-Type-Options: nosniff
X-StreamOrigin: X
X-AsmVersion: UNKNOWN; 11.1.0.0
X-MSEdge-Ref: Ref A: D0094296968F482C9822EF32CD394651 Ref B: 0D99FE6BF2058BE0806F072AA7FF1DCC Ref C: Fri Dec 16 01:59:26 2016 PST
Date: Fri, 16 Dec 2016 09:59:26 GMT
```

-------

I have a question. In [first response](#first-response), `[` and `]` are included in `Location`. is that valid URL? I just wondered because [JAVA's URI api](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html) throws Exception while constructing instance with the URL.

**Comment by ificator** [comment] 2016-12-16 18:50
Thanks @isac322! I'll investigate further today and see what I find

**Comment by ificator** [comment] 2016-12-16 18:56
Actually I can see something strange already. The location header return from the request against `/content` was:
> https://public-bn1305.files.1drv.com/y3mptgQ3ZRYDAQz2PVfKL5hIfaGlNDV7C2JANIklzqntZKxoGBN2DXINAkT4fQ8sZPYoRXjUH3Tx-H13UByIcBEiC2uCacXPO25boiWtRcWcLRhJ7hPVPJA-iH0jRmOenHkEIeUInryLVNFlcHN5kIGyrbqjOcMP-OTsF6HDlJ0k0aToLxf3gsG96Drr_antZvjpRRXw5cfm9SSuCyYkH9gOpiJkBWtLGQ1TXIP5r0WY8dtCkpHI3npOnXz1zU83iYw/[%EC%88%98%EC%A0%95]%20vol.5.mp3

While the request made to fetch the binary data was to:
> https://public-bn1305.files.1drv.com/y3mIEW5v_Wcmm33qIyr9wI8BcL_2xmNyrMrQdM0i11Ae1d8Xd9_BAKuT4-nIXKoGZCPxMtYfKKy4GP-k1wbjxylerA9rc1GGKe_U6bp4NgaXRAYyDmGJ-YsGdsWCy_LQm3MwFw721O-HoPUgSM5vnM0FU2GYv0zq_Gi4Ev5dK0ZekDrLqPvm6MjFIVICitJCpRu56-KDNhCMajpH-sFYMcYGlTYtSy-rOPewh3wwFOZlMOaungvAN68C2RJ83j-cd2S/%5B%25EC%2588%2598%25EC%25A0%2595%5D%2520vol.5.mp3

So it looks like something on the client is encoding the URL while handling the redirect. Can you check your code and see if you can spot what's doing that?

**Comment by isac322** [comment] 2016-12-16 19:37
Oh the difference actually because I translated.
I'm using netty and netty's default http request/response decoder. And I menually redirected (extract the `Location` from first response and send another request to it) because netty doesn't support auto redirect. In that extract processing, because the `Location` contains invalid character `[`, `]` (according to java URI api) I had to encode that part. That's why those two are different.

By the way, I think you could right. Let me check raw request/response not filtered by any library.

**Comment by isac322** [comment] 2016-12-16 20:08
You are right @ificator !

- first request command

```bash
curl -vH "authorization: bearer EwAYA61DBAAUGCCXc8wU..." https://api.onedrive.com/v1.0/drive/items/{Item-ID}/content
```

- first response

```
HTTP/1.1 302 Found
Content-Length: 0
Location: https://public-bn1305.files.1drv.com/y3mZ66G6CWqJfk-P-bmracBJpFHLDH9UHeD9J4dFKxgcyENwDvc28mJyYW1TYQ0y9rDIZCHtmrrsLqBaCawKao1_7nmTThNnv2oDKQSllODgsLihL3JMe3NdB7EWeoj1c86zKlacdLPjcqYpAC4xQqmDkpiOUixMUwkXowBzzfMx5FEZ0EE64Vz6pvHkOXliCH8jRHj_m72xchAe1Ps3ac1t462pWoZBwgwSB8sFKMBurqe5Hd4ZhBMql4qf2fNrciM/[%EC%88%98%EC%A0%95]%20vol.5.mp3
Server: Microsoft-IIS/8.5
P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
X-MSNSERVER: BN2BAP00130A298
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-AsmVersion: UNKNOWN; 11.1.0.0
X-MSEdge-Ref: Ref A: 9AC17865F0F44CDEAE31D5564E1C1AB7 Ref B: F3334BA5711E499FFBF9CD682D09A7AE Ref C: Fri Dec 16 11:46:19 2016 PST
Date: Fri, 16 Dec 2016 19:46:19 GMT
```

- second request command

    - replace `[` to `%5B`, `]` to `%5D` from `Location` of first request

```bash
curl -vH "accept-encoding: gzip" https://public-bn1305.files.1drv.com/y3mVi8GNYO0615urrD5h6mXfb6w6HdFp9mo4kRJKgFcgCPeNvrLnDa0ekpV3p3lekz8FYzBQt4D7KIFmfg9W7aqEBqVSBAtcP14klx4siwyendLwx4OFvr0clvcjrs55k-sel8DlbNh7KcU_9YZDwhZ30R4HXOlkonYeuBDDT9TOIqx35aYTnK8ca3Z_GR2AAnNCGu7NIFvotygkbFu_4IxW7b7W0oXva_GAXLATqJ2DGFcFCyOESjIZM2UoJAiBZ3P/%5B%EC%88%98%EC%A0%95%5D%20vol.5.mp3
```

- second response

```
HTTP/1.1 200 OK
Cache-Control: public
Content-Length: 59254808
Content-Type: audio/mpeg
Content-Location: https://public-bn1305.files.1drv.com/y3mo2qeq7UEKYd1sCweaNc1HsYuZF8sVANAiVTqDDIP9dl_Veg9R-7Jst17pBSPxav_sJElheoaL6uwNgbCRGOLNj9-NjJUoJPi24UqYrmvrltu2NTY1tmD49nfSdRAJkHwEyoqmFNwqvDsbChGbquF52hlf1JBC9xQatYN9ffTlQ0LXpt68C5XQBLvP-AqasSLwMvQM6JXuCmOpRtSOwCGSVszrk8qXnc51eiv9MzYsLw
Expires: Thu, 16 Mar 2017 19:44:25 GMT
Last-Modified: Sun, 24 Jul 2016 04:25:59 GMT
Accept-Ranges: bytes
ETag: aRDRGRDgyQ0E2REY5NkE0NyEyNDk5OC4x
Server: Microsoft-IIS/8.5
P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
X-MSNSERVER: BN2BAP00130A298
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-SqlDataOrigin: S
CTag: aYzpENEZEODJDQTZERjk2QTQ3ITI0OTk4LjI1Nw
X-PreAuthInfo: rv;poba;
Content-Disposition: attachment; filename*=UTF-8''%5b%ec%88%98%ec%a0%95%5d%20vol.5.mp3
X-Content-Type-Options: nosniff
X-StreamOrigin: X
X-AsmVersion: UNKNOWN; 11.1.0.0
Date: Fri, 16 Dec 2016 19:44:24 GMT
```

`%5b%ec%88%98%ec%a0%95%5d%20vol.5.mp3` in `Content-Disposition` is `[수정] vol.5.mp3` and it's encoded only once.

Sorry @ificator double encoded string is my fault.. TT

**Comment by isac322** [comment] 2016-12-16 20:10
But the second bug that I firstly mentioned ("2. totally wrong name") is still going on.

- first request command
    - the item that named `%2f%2e.txt`

```bash
curl -vH "authorization: bearer EwAYA61DBAAUGCCXc8wU..." https://api.onedrive.com/v1.0/drive/items/{Item-ID}/content
```

- first response
```
HTTP/1.1 302 Found
Content-Length: 0
Location: https://public-bn1305.files.1drv.com/y3miLlUqjxEyL_nMKj6hMv4LQEQQC1ZSeDVlmcaVRV496W6tQmQRbPpHgQzhtgtpD3KETDo5MoJyavcvOIlyeq1xVIJ5tG-W6clOpkPDUWtyFce_EyJMiIf02uJTVXAtz9PRA4_9F43JkOVBSP3b1_9oy7CV3KZuvwLWVGDVQ47Pt3EQkwbHUhQVR-38Lb8myeH0g45blBWLYXzL2V9j3zZIkYN0inEE4JUO6eHmeAzq6SxA_D1B77Zcxug6YQlAqcw/%2f..txt
Server: Microsoft-IIS/8.5
P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
X-MSNSERVER: BN2BAPC8903DF2B
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-AsmVersion: UNKNOWN; 11.1.0.0
X-MSEdge-Ref: Ref A: 42C98B2FA1CA45B99525AEB91D9CE65B Ref B: B1C1A8F2D99ECE6127A305C95BAE5E46 Ref C: Fri Dec 16 12:03:46 2016 PST
Date: Fri, 16 Dec 2016 20:03:45 GMT
```

- second request command
```bash
curl -v https://public-bn1305.files.1drv.com/y3mU3WWXk3WuB56bmMayuqFt7iAN2-Ku4zdkf2MOSB6Lc5nMy4wEfgWae-QWzz9G_EKRYKB0Pbc4CcjGcstPKhjz1Ja6-bHmkH86PLajq4rf7QL18xs8iuej4Uq4aRHEIL7W4NLsw2a_Ai3F7wMDfXlYlS_iipkuJmrIh9DTyL7XmcIRG-u-AM4dRkhC0B8TVwLATop8P9sIAa36ZtP1d7hiEzo2FlCyZyLGSiIxh_rFjrkYbF8iqacdY8HDm9b2dsk/%2f..txt
```

- second response
```
HTTP/1.1 200 OK
Cache-Control: public
Content-Type: text/plain
Content-Location: https://public-bn1305.files.1drv.com/y3mNmuFFeoitGMtilBrK_Fgnn5ijOYoREsnxWldig9tCbCdoVF-_IGexJXLhNtYz2N2_7uo9ulgeR8_C7kJvcL-2nws4lheapLVr0Emz0JzUqwe-OAO18fI4L51khpj418mhOXVaqkt2fc4ejgXfxj2vyHiQsYwqzna1pGlIZ0OeY7m7F8PFdgzLoHuUWUvi_WEVrNouRys5uGSX324ClLC5DYufQjRySe_EMhEE_-d6A8
Expires: Thu, 16 Mar 2017 19:46:55 GMT
Last-Modified: Sat, 03 Dec 2016 14:34:01 GMT
Accept-Ranges: bytes
ETag: aRDRGRDgyQ0E2REY5NkE0NyEyNjAzNy4y
Server: Microsoft-IIS/8.5
P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
X-MSNSERVER: BN2BAP4C5955DD3
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-SqlDataOrigin: S
CTag: aYzpENEZEODJDQTZERjk2QTQ3ITI2MDM3LjI1OA
X-PreAuthInfo: rv;poba;
Content-Disposition: attachment; filename="..txt"
X-Content-Type-Options: nosniff
X-StreamOrigin: X
X-AsmVersion: UNKNOWN; 11.1.0.0
Date: Fri, 16 Dec 2016 19:46:54 GMT
Content-Length: 6
```

`Content-Disposition` of second response represent that `filename="..txt"`

**Comment by ificator** [comment] 2016-12-16 21:21
Great news for your first issue!

Also for the second - I can reproduce that one :). We'll work on a fix.

**Comment by ificator** [comment] 2016-12-29 16:49
I just wanted to quickly follow up to let you know that the fix is checked in, but due to the holiday season it'll take longer than normal to ship. I'll update this thread once it's out.

**Comment by ificator** [comment] 2017-02-11 02:52
This fix has now been deployed. Please reactivate the issue if you're still seeing issues.

**Closed by ificator** 2017-02-11 02:52 UTC
Labels: bug
