### ISSUE TITLE
RestoreVersion API seems to be Broken

### ISSUE THREAD

**Issue by nk-gears** [OneDrive/onedrive-api-docs#1086] opened 2019-06-26 05:56 UTC
#### Category
- [x] Bug

#### Expected or Desired Behavior
- When we restore a Version of a Drive Item file, then it should restore the actual version specified in the EndPoint Url instead of restoring the (currentVersion - 1) file.

https://graph.microsoft.com/v1.0/sites/{siteId}/drives/{driveId}/list/items/2244/versions/15.0/restoreVersion

#### Observed Behavior

Issue:
restoreVersion API seems to be broken. When we restore a specific version using POST, the API restoring the major version again and again instead of the actual version specified in the Url.

End Point :
https://graph.microsoft.com/v1.0/sites/{siteId}/drives/{driveId}/list/items/2244/versions/15.0/restoreVersion

Article:
https://docs.microsoft.com/en-us/graph/api/driveitemversion-restore?view=graph-rest-1.0&tabs=cs to

Note : Since the data are confidential, I am unable to share the RequestId. If its mandatory, then i need to simulate this with a separate developer account. 
 
#### Steps to Reproduce
 
- Create a Excel file in Sharepoint Library
- Update the Excel file manually couple of times so that we have 4 Versions (V1,V2,V3,V4)
- Use the API to restore the Version V2.
- But it was restoring V3 instead of V2.

**Comment by JeremyKelley** [comment] 2019-06-26 20:17
@nk-gears The request ID shouldn't contain any confidential information, it's just a GUID returned in the response headers.  In order for us to look at what's actually happening we'll need both the request ID and the timestamp of the call.

**Comment by nk-gears** [comment] 2019-06-27 07:20
@JeremyKelley , Here the details for investigation.

# Restoring version 3.0
client-request-id: d6250ae3-a31e-48ca-9656-9a570297fadd
content-type: text/plain
cache-control: private
request-id: d6250ae3-a31e-48ca-9656-9a570297fadd

# Restoring version 2.0
client-request-id: 99a72131-3f6f-450b-8874-5e6cff18e017
content-type: text/plain
cache-control: private
request-id: 99a72131-3f6f-450b-8874-5e6cff18e017

Note :
I Created  a New Excel Online file and manually edited to create 5 versions.

- Used this End Point to restore the 3rd Version. But when i opened the file, it shows me the 4th version.
- Again i tried to restore the 2nd Version, But it still stays in the 4th version

Hope this helps.

FYI :
Due to this bug, we decided to remove automated API based restoring in our app.

**Comment by D4N14L** [comment] 2019-07-10 21:27
Hey @nk-gears unfortunately I'm unable to reproduce the scenario on my end (using your flow as well), and the correlation IDs you sent do not provide a timestamp, which is necessary for me to query our logs for this. Could you repro and provide a fresh correlation ID and timestamp?

**Comment by nk-gears** [comment] 2019-07-15 11:04
Here the fresh details


client-request-id: b3542a2c-6773-489c-817a-38f0439a50fb
content-type: text/plain
cache-control: private
request-id: b3542a2c-6773-489c-817a-38f0439a50fb

Timestamp : 4:34 PM IST

**Comment by D4N14L** [comment] 2019-08-08 20:56
Looking at the logs, it appears to be possible that the list (or the fields on the list) is mis-configured. We attempted to see if we could determine what exactly was mis-configured, however it appears that the list was also deleted, which complicates things on our end.

Could you validate that this happens in a brand new document library without any changes from stock? If it does still occur, could you provide us with the same info (request-id and timestamp+date) for this case? I apologize that this is taking a while to troubleshoot, however it seems that this issue is narrowly scoped, as we have seen no other reports of this and are unable to reproduce on our end.

**Comment by nk-gears** [comment] 2019-08-09 03:07
Hi @D4N14L 

Thanks for the follow up.

I am ready to  walkthrough over a live screen-share instead of these multiple round trips to troubleshoot this. Please let me know if that helps. I am in IST Timezone.

**Comment by patrick-rodgers** [comment] 2023-02-17 20:31
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:31 UTC
Labels: Needs: Attention :wave:, automation:Closed
