### ISSUE TITLE
Could not find a property named 'photoStreamPostReactionByCaller' on type 'oneDrive.uploadSession'

### ISSUE THREAD

**Issue by akih** [OneDrive/onedrive-api-docs#1529] opened 2021-09-09 11:46 UTC
I'm getting bad request -response with following message when trying to create upload session: **Could not find a property named 'photoStreamPostReactionByCaller' on type 'oneDrive.uploadSession'**. I am not able to find any documentation about this property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d409f771-fd62-e549-d581-aac009e79e8c
* Version Independent ID: fe646b3a-06f5-a269-47e6-b4ee693e5410
* Content: [Resumable file upload - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_createuploadsession.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_createuploadsession.md)
* Product: **onedrive**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKe**

**Comment by ificator** [comment] 2021-09-09 14:34
What query string parameters are you passing in with the request?

**Comment by akih** [comment] 2021-09-10 05:14
Sorry for incomplete info. We are using Microsoft Graph SDK for Java (2.5.0) with Android and request is done by doing `POST https://graph.microsoft.com/v1.0/drive/root:/ZX1/dummy.txt:/microsoft.graph.createUploadSession?%40microsoft.graph.conflictBehavior=rename`. I just figured out that using `conflicBehavior` is causing this. When it is left out the upload session is created as expected. This has been working before so apparently something has changed at some point.

**Comment by akih** [comment] 2021-09-10 05:33
Moved `conflicBehaviour` to request body and everything seems to be working. Not sure why it was not in the request body originally. Strange though what was causing need for `photoStreamPostReactionByCaller` property..

**Comment by ificator** [comment] 2021-09-10 09:11
Thanks for the information - there is a regression in `createUploadSession` when a query string is provided. A fix is rolling out, but the mitigation is, as you've observed, to remove the query string.

**Comment by kateyeo** [comment] 2021-09-20 23:10
Hi, I’m working on the [Data Transfer Project with Google](https://github.com/google/data-transfer-project) with @seehamrun and have been running into the same issue, is there an ETA on when a fix for this issue will roll out?

**Comment by ificator** [comment] 2021-09-21 15:24
It's rolling out as we speak, so I'd estimate roughly a week to be fully complete.

Looking at your code it looks like you're passing the `@microsoft.graph.conflictBehavior` as a query string parameter, and so one work around you have is to shift that to the request body:

```
{
  "item": {
    "@microsoft.graph.conflictBehavior": "rename"
  }
}
```

**Comment by patrick-rodgers** [comment] 2023-02-17 20:43
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:43 UTC
Labels: type:bug, area:DriveItem Content, automation:Closed
