### ISSUE TITLE
"overwrite" doesn't work, but "replace" does.

### ISSUE THREAD

**Issue by lockelost** [OneDrive/onedrive-api-docs#925] opened 2018-10-17 20:02 UTC
Hi,
I am testing on the OneDrive for Business and "@microsoft.graph.conflictBehavior" option "overwrite" gives "Bad Command" error. But "replace" works.

This is very critical if the behavior changes silently in the future. So I think it's good for you to consider making both option string works. 

Anyway, this official document should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d409f771-fd62-e549-d581-aac009e79e8c
* Version Independent ID: fe646b3a-06f5-a269-47e6-b4ee693e5410
* Content: [Resumable file upload - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online)
* Content Source: [docs/rest-api/api/driveitem_createuploadsession.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/api/driveitem_createuploadsession.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by ificator** [comment] 2018-10-17 20:06
Replace should work - when it fails for you there should be "requestguid" and "date" headers in the response, could you provide those to us so we can take a look and figure out what's going on?

**Comment by lockelost** [comment] 2018-10-17 20:33
**Request**

`
POST https://graph.microsoft.com/v1.0/users/test1@cvdevtenant.onmicrosoft.com/drive/root:/aaa%20-%20Copy%20(2)%20-%20Copy%20-%20Copy.txt:/createUploadSession HTTP/1.1
User-Agent: NONISV|Commvault|b19da128-14a9-4521-8ecd-7941009e9979/1.0
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6IkFRQUJBQUFBQUFDNXVuYTBFVUZnVElGOEVsYXh0V2pUWHBYUVdib1duUHpDa2lybGFjM2JSZlNBQjZqa2lZbTk4c24zdWNiTWt0M0RYeThSSk0zSHdSX0tTX0M1VDlYXzBha2hxWTFpMHlRZUhiTGZtcERvZlNBQSIsImFsZyI6IlJTMjU2IiwieDV0IjoiaTZsR2szRlp6eFJjVWIyQzNuRVE3c3lISmxZIiwia2lkIjoiaTZsR2szRlp6eFJjVWIyQzNuRVE3c3lISmxZIn0.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zYjkyYzM1ZS1hZDYwLTRmMDItYjBhMC05MmU5OWM5OTkxYjAvIiwiaWF0IjoxNTM5ODA3OTkxLCJuYmYiOjE1Mzk4MDc5OTEsImV4cCI6MTUzOTgxMTg5MSwiYWlvIjoiNDJSZ1lNaHBYNzV1SWRQRDlGWnVyMEw1aFo2VkFBPT0iLCJhcHBfZGlzcGxheW5hbWUiOiJvbmVkcml2ZXRlc3QiLCJhcHBpZCI6ImIxOWRhMTI4LTE0YTktNDUyMS04ZWNkLTc5NDEwMDllOTk3OSIsImFwcGlkYWNyIjoiMSIsImVfZXhwIjoyNjI4MDAsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzNiOTJjMzVlLWFkNjAtNGYwMi1iMGEwLTkyZTk5Yzk5OTFiMC8iLCJvaWQiOiIyZDZmNjNiYi1lNDBkLTRiYTUtOTczZC1mMzEyYTE2MzliNDAiLCJyb2xlcyI6WyJDaGF0LlVwZGF0ZVBvbGljeVZpb2xhdGlvbi5BbGwiLCJDYWxscy5Kb2luR3JvdXBDYWxsLkFsbCIsIkVkdVJvc3Rlci5SZWFkLkFsbCIsIk9ubGluZU1lZXRpbmdzLlJlYWQuQWxsIiwiTWFpbC5SZWFkV3JpdGUiLCJPbmxpbmVNZWV0aW5ncy5SZWFkV3JpdGUuQWxsIiwiRGV2aWNlLlJlYWRXcml0ZS5BbGwiLCJVc2VyLlJlYWRXcml0ZS5BbGwiLCJEb21haW4uUmVhZFdyaXRlLkFsbCIsIkFwcGxpY2F0aW9uLlJlYWRXcml0ZS5Pd25lZEJ5IiwiU2VjdXJpdHlFdmVudHMuUmVhZC5BbGwiLCJDYWxlbmRhcnMuUmVhZCIsIkVkdUFzc2lnbm1lbnRzLlJlYWRXcml0ZS5BbGwiLCJQZW9wbGUuUmVhZC5BbGwiLCJBcHBsaWNhdGlvbi5SZWFkV3JpdGUuQWxsIiwiQ2FsbHMuSW5pdGlhdGVHcm91cENhbGwuQWxsIiwiR3JvdXAuUmVhZC5BbGwiLCJEaXJlY3RvcnkuUmVhZFdyaXRlLkFsbCIsIkVkdUFzc2lnbm1lbnRzLlJlYWRXcml0ZUJhc2ljLkFsbCIsIk1haWxib3hTZXR0aW5ncy5SZWFkIiwiRWR1QWRtaW5pc3RyYXRpb24uUmVhZC5BbGwiLCJDYWxscy5Kb2luR3JvdXBDYWxsQXNHdWVzdC5BbGwiLCJTaXRlcy5SZWFkLkFsbCIsIlNpdGVzLlJlYWRXcml0ZS5BbGwiLCJDb250YWN0cy5SZWFkV3JpdGUiLCJHcm91cC5SZWFkV3JpdGUuQWxsIiwiU2l0ZXMuTWFuYWdlLkFsbCIsIlNlY3VyaXR5RXZlbnRzLlJlYWRXcml0ZS5BbGwiLCJOb3Rlcy5SZWFkLkFsbCIsIlVzZXIuSW52aXRlLkFsbCIsIkVkdVJvc3Rlci5SZWFkV3JpdGUuQWxsIiwiRmlsZXMuUmVhZFdyaXRlLkFsbCIsIkRpcmVjdG9yeS5SZWFkLkFsbCIsIlVzZXIuUmVhZC5BbGwiLCJFZHVBc3NpZ25tZW50cy5SZWFkQmFzaWMuQWxsIiwiRWR1Um9zdGVyLlJlYWRCYXNpYy5BbGwiLCJGaWxlcy5SZWFkLkFsbCIsIk1haWwuUmVhZCIsIkNoYXQuUmVhZC5BbGwiLCJDaGFubmVsTWVzc2FnZS5SZWFkLkFsbCIsIkVkdUFzc2lnbm1lbnRzLlJlYWQuQWxsIiwiQ2FsZW5kYXJzLlJlYWRXcml0ZSIsIkVkdUFkbWluaXN0cmF0aW9uLlJlYWRXcml0ZS5BbGwiLCJNYWlsLlNlbmQiLCJDaGFubmVsTWVzc2FnZS5VcGRhdGVQb2xpY3lWaW9sYXRpb24uQWxsIiwiTWFpbGJveFNldHRpbmdzLlJlYWRXcml0ZSIsIkNvbnRhY3RzLlJlYWQiLCJJZGVudGl0eVJpc2tFdmVudC5SZWFkLkFsbCIsIkF1ZGl0TG9nLlJlYWQuQWxsIiwiTWVtYmVyLlJlYWQuSGlkZGVuIiwiQ2FsbHMuQWNjZXNzTWVkaWEuQWxsIiwiU2l0ZXMuRnVsbENvbnRyb2wuQWxsIiwiUmVwb3J0cy5SZWFkLkFsbCIsIkNhbGxzLkluaXRpYXRlLkFsbCIsIk5vdGVzLlJlYWRXcml0ZS5BbGwiXSwic3ViIjoiMmQ2ZjYzYmItZTQwZC00YmE1LTk3M2QtZjMxMmExNjM5YjQwIiwidGlkIjoiM2I5MmMzNWUtYWQ2MC00ZjAyLWIwYTAtOTJlOTljOTk5MWIwIiwidXRpIjoiRS11WVhzSWtYMG05eXVkY3hhSXNBUSIsInZlciI6IjEuMCIsInhtc190Y2R0IjoxNDk1NzI5MzQ0fQ.gFtYLPkFZ3g-Gfita7-AaTF_TsbkLITqbyRZsIMT_Gy4iJeW0MTzvM5vOrHXiH1oGorfP4zg4UD1vEOxSVgqxMOdR3jt-oRrjYe3bcba0wlaFuT7H3LdBk9eX7pVboUod-XIPJsiV5QN_UctjMWU9vId6VM6Os3_aeGoZcW7OrPMdRobt0I_-HyVpburD0NOR6iVeZhy6oBS8JxVFULFCcjq3Yx_SIkRd52HC8uqEvu5UhUkPxp13K71qfpKxgcp5vjrXbaO_T8nWCNCTglkcaF3F_2_VEwN5V_-Xh9xzL91ZKO8c7VJo8BL9PZdFXnKM_Yz2uRH1RV-1Wp8krDGBg
Content-Type: application/json; charset=utf-8
Host: graph.microsoft.com
Content-Length: 60
Expect: 100-continue
Accept-Encoding: gzip, deflate

{"item": {"@microsoft.graph.conflictBehavior": "overwrite"}}
`

**Response**
`
HTTP/1.1 400 Bad Request
Cache-Control: private
Transfer-Encoding: chunked
Content-Type: application/json
request-id: e8859f2b-12da-4f42-8c3d-5307f8746940
client-request-id: e8859f2b-12da-4f42-8c3d-5307f8746940
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"SliceC","Ring":"5","ScaleUnit":"001","Host":"AGSFE_IN_88","ADSiteName":"EUS"}}
Duration: 329.7538
Strict-Transport-Security: max-age=31536000
Date: Wed, 17 Oct 2018 20:31:33 GMT

fc
{
  "error": {
    "code": "invalidRequest",
    "message": "NameConflictBehavior must be fail, replace or rename",
    "innerError": {
      "request-id": "e8859f2b-12da-4f42-8c3d-5307f8746940",
      "date": "2018-10-17T20:31:33"
    }
  }
}
0


`

**Comment by ificator** [comment] 2018-10-18 21:35
Oh thanks for that - it looks like the docs are just outright wrong, as you suspected it should be "replace".

**Comment by alfaunits** [comment] 2018-10-23 15:30
Peculiar, I have been working with "overwrite" for the past few days, and it worked as a string.
I did not test overwriting files in particular, but the call did not fail with "overwrite".

**Comment by ificator** [comment] 2018-10-23 17:35
Thanks for calling that out - I wonder if there was a change in error handling. @katahir can take a look to confirm.

**Comment by chackman** [comment] 2018-10-30 19:42
The docs have been updated - now they are consistently saying "replace" in both the OneDrive dev center and on Microsoft Graph.

I verified that the following POST body fails validation (and there have been no recent error handling changes); @alfaunits could you please provide more information about your requests, and whether "overwrite" still appears to succeed?
  {"item": {"@microsoft.graph.conflictBehavior": "overwrite"}}

**Comment by alfaunits** [comment] 2018-10-31 08:52
I can confirm it not working via Graph Explorer. Gimme a day to check via
code directly.

**Comment by alfaunits** [comment] 2018-11-02 10:54
Confirmed. It is no longer working for ODB, via app as well.

**Comment by chackman** [comment] 2018-11-05 18:10
OK, thanks.  I'll close this out now that the docs have been fixed.

**Closed by chackman** 2018-11-05 18:10 UTC
Labels: investigating
