### ISSUE TITLE
[Question] OneDrive for Business with Move an item on OneDrive

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#132] opened 2015-06-09 03:04 UTC
hello,

I tried to patch my file by requesting "PATCH /drive/items/{item-id}".
here is the whole request:

```http
PATCH https://onedrivedev-my.sharepoint.com/_api/v2.0/me/drive/items/file_id
Authorization: Bearer accesstoken
Content-Type: application/json
if-match: *

{
  "name": "new_name.jpg",
  "parentReference": {"id" : "new_parent_id"}
}
```

it looks work so fine. 
But when i replace the new_parent_id to root_id, it returns this error:
```json
{
"error": {
  "code": "InvalidArgument",
  "message": "The argument is invalid, missing, or has an incorrect format"
  }
}
```

as same as the  "parentReference": {"path": "/drive/root:/Documents"}

Is it a bug? or other issues?

thanks!

**Comment by bscharm** [comment] 2015-06-11 15:14
I am also seeing this error on PATCH by path (/drive/root:/{item-path}). Renaming/moving to any folder but root will work, but root causes error. Here are my responses headers-

```
{
  "Date": "Thu, 11 Jun 2015 15:11:41 GMT",
  "X-Content-Type-Options": "nosniff",
  "X-Aspnet-Version": "4.0.30319",
  "X-Powered-By": "ASP.NET",
  "P3p": "CP=\"ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI\"",
  "X-Sharepointhealthscore": "0",
  "X-Sp-Serverstate": "ReadOnly=0",
  "Connection": "keep-alive",
  "Request-Id": "a0550f9d-b0b0-2000-0d9e-fa6a60c4a5c3",
  "Vary": "Accept-Encoding",
  "Content-Length": "175",
  "Microsoftsharepointteamservices": "16.0.0.4107",
  "Odata-Version": "4.0",
  "X-Ms-Invokeapp": "1; RequireReadOnly",
  "Last-Modified": "Thu, 11 Jun 2015 15:11:39 GMT",
  "Server": "nginx/1.6.3",
  "Sprequestguid": "a0550f9d-b0b0-2000-0d9e-fa6a60c4a5c3",
  "Etag": "\"{8573FAAE-5DCF-4DF1-8306-E5C3D8308ACE},3\"",
  "X-Frame-Options": "SAMEORIGIN",
  "Content-Type": "application/json; odata.metadata=minimal; odata.streaming=true; ieee754compatible=false;charset=utf-8",
  "Access-Control-Allow-Origin": "https://cloud.ngrok.com",
  "Cache-Control": "private, max-age=0",
  "Spclientservicerequestduration": "224",
  "Expires": "Wed, 27 May 2015 15:11:39 GMT"
}
```

**Comment by rgregg** [comment] 2016-02-26 07:12
Closing out old issues. If this is still an issue, please let us know.

**Closed by rgregg** 2016-02-26 07:12 UTC
Labels: bug, OneDrive for Business
