### ISSUE TITLE
Uploading file to DocumentLibrary using Graph SDK results in 409 response; Code: resourceModified

### ISSUE THREAD

**Issue by spmanjunath** [OneDrive/onedrive-api-docs#1415] opened 2020-12-17 11:14 UTC
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
I am using Microsoft Graph SDK to upload a file to SharePoint's DocumentLibrary (..DocumentSet) using the below code,
```
var created = await _graphServiceClientFactory.GetClient().Drives[driveId].Root.ItemWithPath($"{id}/{fileName}").Content.Request().PutAsync<DriveItem>(stream);
```
Expectation is that the file should be uploaded irrespective of whether the file already exists (default -[replace](https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0#instance-attributes)) and there shouldn't be reason for conflicts.

#### Observed Behavior
The file is uploaded successfully most of the time, irrespective of whether the file already exists.  However, once in a while there has been 409 errors with the below message,

> Code: resourceModified
> Message: The resource has changed since the caller last read it; usually an eTag mismatch
> Inner error:
> 	AdditionalData:
> 	date: 2020-12-17T09:28:17
> 	request-id: 96a4b01f-f2f5-40a4-aafc-7fea08a94bf5
> 	client-request-id: 96a4b01f-f2f5-40a4-aafc-7fea08a94bf5
> ClientRequestId: 96a4b01f-f2f5-40a4-aafc-7fea08a94bf5

Flow as observed in Application insight:
![image](https://user-images.githubusercontent.com/7764072/102480525-66d59200-4086-11eb-9e58-d512dc21c1ed.png)

I am unable to determine the root cause of this issue? How can this issue be resolved?

Thank you.

**Comment by k-tsoi** [comment] 2021-01-08 18:27
@spmanjunath are you making concurrent uploads to the same file?

**Comment by spmanjunath** [comment] 2021-01-13 05:35
@k-tsoi i checked the logs there are no concurrent requests, even the multiple different files are uploaded sequentially.

**Comment by k-tsoi** [comment] 2021-02-01 17:35
@spmanjunath are you still seeing this issue, there was a bug in the documentSet that should be fixed now.

**Comment by spmanjunath** [comment] 2021-02-05 05:19
The mentioned issue is still occurring, below is one of the several incidents that occurred yesterday.  Please note that the issues are intermittent.
```
Code: resourceModified
Message: The resource has changed since the caller last read it; usually an eTag mismatch
Inner error:
	AdditionalData:
	date: 2021-02-04T15:47:50
	request-id: e8e861d4-cfab-41a5-9abd-f8a8278f521e
	client-request-id: e8e861d4-cfab-41a5-9abd-f8a8278f521e
ClientRequestId: e8e861d4-cfab-41a5-9abd-f8a8278f521e
```
![image](https://user-images.githubusercontent.com/7764072/106992988-bc354200-679f-11eb-8ac0-e6cd1f332563.png)

**Comment by chackman** [comment] 2021-02-08 17:30
Thanks. Was this case happening to a new file, or a replacement of an existing file?

**Comment by spmanjunath** [comment] 2021-02-09 04:37
It is replacement of an existing file, i see that the same file is updated successfully thrice before, and in the 4th attempt the upload has failed.  There is about 20 mins difference between the previous file update and the 4th file upload.

**Comment by joewutaiwan** [comment] 2021-02-20 07:20
Hi folks,

I also have the same issues with upload files to OneDrive with option:
`name.conflictBehavior=replace`

And this happens randomly, it will succeed after a retry.

Maybe it is the same throttle issue like
https://github.com/OneDrive/onedrive-api-docs/issues/1390

**Comment by joewutaiwan** [comment] 2021-03-09 01:34
Hi @chackman,

Is any update to this issue?

Keep encountering this error while the request count increasing.

Thanks!

**Comment by chackman** [comment] 2021-03-11 20:33
The appropriate thing to do is to retry if this happens.

**Closed** 2021-04-08 20:00 UTC
Labels: Needs: Author Feedback, no-recent-activity

**Comment by joymon** [comment] 2022-11-23 22:46
@chackman ,
We are getting the same issue consistently when using the LargeFileUploadTask so retry is not an option for us. Below is the environment
.Net 4.8
<PackageReference Include="Microsoft.Graph" Version="4.48.0" />

The interesting thing is the issue is not happening for all the files. Some particularly large files (~750MB) are failing consistently.  Till now Excel and PDF are the types we checked.

**Comment by spmanjunath** [comment] 2023-02-28 10:47
I started noticing this error again, the code used to upload the file is as below,

`await _graphServiceClientFactory.GetClient().Drives[driveId].Root.ItemWithPath($"{id}/{fileName}").Content.Request().PutAsync<DriveItem>(stream);`

Additional information:
1) The file is uploaded to a DocumentSet/Folder in SharePoint's.
2) The file with the same name already exists; the last modified date of the file was few days before.
3) At the time of the error there was only one call targeting this file.
4) There was one other call that uploaded a different file to the same DocumentSet few milliseconds before.
5) The file being uploaded is below 100kB.

Error Show:
```
Code: resourceModified
Message: The resource has changed since the caller last read it; usually an eTag mismatch
Inner error:
	AdditionalData:
	date: 2023-02-28T07:45:02
	request-id: 51606c90-3a24-4fea-8205-521a9efbb0a1
	client-request-id: 51606c90-3a24-4fea-8205-521a9efbb0a1
ClientRequestId: 51606c90-3a24-4fea-8205-521a9efbb0a1
```

I am not sure if there is mechanism to use `name.conflictBehavior=replace` with the above call, if so, please suggest how to use it.
