### ISSUE TITLE
ODB/SPO: Add permissions for a group on a drive item 

### ISSUE THREAD

**Issue by dluces** [OneDrive/onedrive-api-docs#805] opened 2018-03-06 22:46 UTC
I have been trying to add permissions for a group on a drive item following the [documentation](https://docs.microsoft.com/en-ca/onedrive/developer/rest-api/api/driveitem_invite). The [`DriveReceipient`](https://docs.microsoft.com/en-ca/onedrive/developer/rest-api/resources/driverecipient) docs say:
> When using invite to add permissions, the DriveRecipient can specify email, alias, or objectId. Only one of these values is required.*

However, sending the following request does not work:
```json
{
	"requireSignIn": true,
	"sendInvitation": false,
	"roles": [ "read"],
	"recipients": [
		{ "objectId": {group_guid} }
	]
}
```

Response:
```
SPClientServiceRequestDuration →163
SPRequestDuration →197
SPRequestGuid →22fa509e-40dc-5000-5289-2c2e4c383d55
request-id →22fa509e-40dc-5000-5289-2c2e4c383d55

{
    "error": {
        "code": "itemNotFound",
        "message": "One of the provided recipients could not be found"
    }
}
```

The group GUID that I'm using is what I obtain using the Graph API `/groups` endpoint, the `id` field for the group. Using `alias: {group_name}` does not work either.

Is sharing to groups supported by the unified API? If so, what should I change to implement it properly? We're trying to move away from the SPO API and to use the unified API and this is a big blocker. Thank you.

\* by the way, it's not just that only one of these values is required, but it is required to send one and only one value (sending two will make it error--I tried adding both alias and objectId to see if the endpoint would find the group, but it didn't work).

**Comment by smotti** [comment] 2018-03-12 07:42
This not only affects groups but also users.

**Comment by katahir** [comment] 2018-03-21 19:41
Thanks for reporting this issue. This is indeed a bug. I am working on fixing it.

**Comment by katahir** [comment] 2018-04-23 17:39
Hi guys,
We made an attempted fix. Can you please try again and let me know what you see?

**Comment by smotti** [comment] 2018-05-14 03:56
> katahir <notifications@github.com>
Hi guys,
We made an attempted fix. Can you please try again and let me know what you see?

Received that mail above on 24th April. Don't know why it doesn't show up here or if it has been removed. But the issue is still not fixed.

**Comment by patrick-rodgers** [comment] 2023-02-17 20:24
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:24 UTC
Labels: type:bug, automation:Closed
