### ISSUE TITLE
Copy file to the root of drive fails with 400 Bad Request

### ISSUE THREAD

**Issue by igokoro** [OneDrive/onedrive-api-docs#108] opened 2015-05-08 13:57 UTC
I'm trying to fix a problem in my application where file copy to the root of drive would fail with ```400 Bad Request```.

The app issues the following request:
```
HTTP POST https://api.onedrive.com/v1.0/drive/items/{file_id}/action.copy
Prefer: respond-async
Accept-Encoding: identity
Authorization: bearer EwB4...
Content-Type: application/json
Content-Length: 54

{
    "name" : "filename.jpg",
    "parentReference" : {
        "id" : "root"
    }
}
```
OneDrive server responds with the following error:
```
Via: 1.1 DM2301____PAP162 (wls-colorado)
Content-Length: 194
Content-Type: application/json
Server: Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
X-WLSPROXY: DM2301____PAP162
Strict-Transport-Security: max-age=31536000; includeSubDomains
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-MSNSERVER: DM2303____PAP219
X-QosStats: {"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}
X-ThrowSite: 5ce0.eb9a
X-AsmVersion: UNKNOWN; 19.18.0.0
P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
Date: Fri, 08 May 2015 13:40:49 GMT

{  
   "error":{  
      "code":"invalidArgument",
      "message":"ObjectHandle is Invalid",
      "innererror":{  
         "code":"badArgument",
         "innererror":{  
            "code":"invalidObjectHandle",
            "innererror":{  
               "code":"invalidResourceId"
            }
         }
      }
   }
}
```

If I try to reference the root folder via parent reference's path as follows, I'm getting ```404 Not Found```.
```
{  
    "error":{  
        "code":"itemNotFound",
        "message":"Item Does Not Exist",
        "innererror":{  
            "code":"itemDoesNotExist",
            "innererror":{  
                "code":"folderDoesNotExist"
            }
        }
    }
}
```
Apparently neither id "root" nor path "/drive/root:" are valid in the context of the copy operation. 

But both id "root" and path "/drive/root:" work perfectly for ```HTTP GET  https://api.onedrive.com/v1.0/drive/items/root``` and ```HTTP GET https://api.onedrive.com/v1.0/drive/root:```.

So, I wonder if this is some kind of bug in the copy operation.
Also I wonder if there is a way to copy a file into the root of drive without knowing its exact id - via "root" name/id/path?

**Comment by peternied** [comment] 2015-05-09 04:08
Thanks for providing all of that detail, you have certainly found a bug! It looks like we are not properly translating "id":"root" or "path":"/drive/root:" into the proper part of our system and it is giving you that error.  I don't have a work around right now, but I'm looking into it.  Thanks for reporting this issue.

**Comment by ificator** [comment] 2015-05-09 04:32
This is partly a duplicate of https://github.com/OneDrive/onedrive-api-docs/issues/73, but the fix for that issue did not include anything for supporting the "root" id. Part of me wants to say we shouldn't since it's not a proper id (I.e. it's not an id we return), but I can see how it's a little inconsistent to say that when /drive/items/root works.

**Comment by rgregg** [comment] 2015-06-26 18:55
@ificator Does copy to path: "/drive/root" work now, just not ID?

**Comment by ificator** [comment] 2015-06-26 19:36
Correct.

**Comment by rgregg** [comment] 2015-06-26 19:52
Great. I'll update the docs to mention that when moving a file to root you can use Path or you can use the actual root ID, but not the keyword "root".

**Closed by rgregg** 2015-06-26 19:52 UTC
Labels: bug
