### ISSUE TITLE
Get contents error "You cannot get the content of the current version."

### ISSUE THREAD

**Issue by lockelost** [OneDrive/onedrive-api-docs#1112] opened 2019-07-29 20:01 UTC
Hi,
If you check with Graph Explorer, you can not get content data of the latest version.
So for most of files that have only 1 version, GET /drive/items/{item-id}/versions/{version-id}/content always fails

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5702e83-3445-5213-1840-0ccf27ed1512
* Version Independent ID: 49d186d8-c02a-4a74-95da-d8c4421b4a39
* Content: [DriveItemVersion - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitemversion?view=odsp-graph-online)
* Content Source: [docs/rest-api/resources/driveitemversion.md](https://github.com/OneDrive/onedrive-api-docs/blob/live/docs/rest-api/resources/driveitemversion.md)
* Product: **onedrive**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by JeremyKelley** [comment] 2019-07-31 20:41
Hi @lockelost we'll update our docs to reflect accordingly.  The feature is by design that for the most recent version's content you should access the drive item directly without using the versions API.

**Comment by patrick-rodgers** [comment] 2023-02-17 20:32
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:32 UTC
Labels: area:Docs, automation:Closed
