### ISSUE TITLE
[ODB] fail to get uploadUrl for an existed file name

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#1286] opened 2020-05-25 07:57 UTC
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

Step 1.
Upload a file to OneDrive for Business named "test.file"

Step 2.
Create a upload session for the same file "test.file"

Step 3.
Request for the uploadUrl and then got an error.

> GET uploadUrl 

```
{
    "error": {
        "code": "-1, Microsoft.SharePoint.Client.InvalidClientQueryException",
        "message": "運算式 \"drive/items('01VY6VLMTBMCZYLMN7MBFYZO5UMNEADZHE')/getUploadStatus(guid='70bc8977-30ae-42be-91c9-659c5c5fb987',path=)\" 無效。"
    }
}
```

Step 4.
More information is below
```
request-id →dbcf559f-80da-b000-5d96-b47ee56d2b78
date →Mon, 25 May 2020 07:51:43 GMT
```

I also try different options like rename | fail | replace, and all of them are the same.

Thank you for help.

**Comment by ificator** [comment] 2020-05-25 17:45
We made a fix recently that stopped include the parent id in the upload URL for a file update, however it looks like this regressed the `GET` scenario. We've disabled the change for now - can you confirm that the issue is resolved for you?

**Comment by joewutaiwan** [comment] 2020-05-26 02:52
Hi @ificator ,

Thanks for reply and have quick fix, everything works fine right now.

**Comment by ificator** [comment] 2020-05-26 17:38
Thanks for confirming @joewutaiwan - I'm going to close this issue out but feel free to reopen if you notice anything strange.

**Closed by ificator** 2020-05-26 17:38 UTC
Labels: type:bug
