### ISSUE TITLE
OneDrive for Business - approot (special folder) naming

### ISSUE THREAD

**Issue by rpassis** [OneDrive/onedrive-api-docs#338] opened 2016-04-08 02:19 UTC
Hi all,

We have an application that integrates seamlessly with OneDrive Personal accounts, and have started making changes to cater for OneDrive for Business accounts as well.

Syncing works as expected however we are experiencing an issue with Business accounts where the first call to **<endpoint//drive/special/children>** creates a folder using some sort of UUID sequence instead of the application name i.e. "Apps/12345-6789-1234-abcd-efghjklmxyz" instead of "Apps/My App Name". The same call works as expected with OneDrive Personal accounts.

The URL generated for the request above is https://mydomain.sharepoint.com/_api/v2.0/me/drive/special/approot/children which looks correct.

The app settings on ActiveDirectory seem correct i.e. the app name is "My app name".

Any ideas of why this might be happening?

Many thanks in advance.
Rog

**Comment by rpassis** [comment] 2016-04-13 00:14
Hi again,

Further to the below, I've been able to do some manual testing to confirm the behaviour described above so here are my findings:

After authenticating, discovering my own api endpoint and successfully receiving an authentication token, 

Staring from _an empty_ Apps folder, I make the below requests in the order they are described:

*1) List all the items under my Apps folder*
`GET https://{my_end_point}/_api/v2.0/me/drive/items/{apps_folder_id}/children`
This returns a JSON object with a `value` node that is an empty array (as expected).

*2) Try to access my approot special folder* (this call has a side effect of creating the approot folder if it doesn't exist yet)
`GET https://{my_end_point}/_api/v2.0/me/drive/special/approot`

*3) List all the items under my Apps folder (again)*
`GET https://{my_end_point}/_api/v2.0/me/drive/items/{apps_folder_id}/children`
This time the value node contains one item (as expected) however the naming convention used is not as per what is described in the documentation. It uses a combination of client_id@random?_uuid as the folder name instead of the actual application name.

I've included the 3 JSON payloads with full headers for your review, as well as a screenshot of how the app is configured under Active Directory.

Please let me know if you need any other details from me.
Thanks,
Rog

[03_list_all_files_in_apps_folder_again.json.txt](https://github.com/OneDrive/onedrive-api-docs/files/216174/03_list_all_files_in_apps_folder_again.json.txt)
[02_list_all_files_in_approot_folder.json.txt](https://github.com/OneDrive/onedrive-api-docs/files/216176/02_list_all_files_in_approot_folder.json.txt)
[01_list_all_files_in_apps_folder.json.txt](https://github.com/OneDrive/onedrive-api-docs/files/216175/01_list_all_files_in_apps_folder.json.txt)
![screen shot 2016-04-13 at 10 12 12 am](https://cloud.githubusercontent.com/assets/387079/14479282/4dfd8996-0160-11e6-9329-0e1fae54c0d8.png)

**Comment by rgregg** [comment] 2016-04-13 17:13
Hi @rpassis. This is definitely not by design, there seems to a bug with how we're recording your application's name that's resulting in the poorly name app folder. We're investigating.

**Comment by patrick-rodgers** [comment] 2023-02-17 20:20
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:20 UTC
Labels: type:bug, automation:Closed
