### ISSUE TITLE
[ODB] multi-upload encounter 401 when upload file name length bigger than 86

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#588] opened 2017-04-11 02:24 UTC
Hello,

It is a little strange that the api is sensitive to the file length.
But I do not know what exactly caused it.
thank you for help

**[case1]: length = 87**
```
file name: Training Presentation - Make the switch to the qqqq 2010 user interface_ZD1025512.docx
dst: root
http code :401
---
Connection: close
Content-Length: 0
Date: Tue, 11 Apr 2017 02:18:02 GMT
HTTP/1.1 401 Unauthorized
MicrosoftSharePointTeamServices: 16.0.0.6330
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
SPRequestGuid: a8cfe69d-f0fb-3000-a2ad-47db09886134
Server: Microsoft-IIS/8.5
Strict-Transport-Security: max-age=31536000
WWW-Authenticate: Bearer realm="dcb0ac15-0be0-44fe-9662-e578d2178b94",client_id="00000003-0000-0ff1-ce00-000000000000",trusted_issuers="00000001-0000-0000-c000-000000000000@*,https://sts.windows.net/*/,00000003-0000-0ff1-ce00-000000000000@90140122-8516-11e1-8eff-49304924019b",authorization_uri="https://login.windows.net/common/oauth2/authorize"
X-Content-Type-Options: nosniff
X-FRAME-OPTIONS: SAMEORIGIN
X-MS-InvokeApp: 1; RequireReadOnly
X-Powered-By: ASP.NET
request-id: a8cfe69d-f0fb-3000-a2ad-47db09886134
x-ms-suspended-features: features=""
```
**[case2] length = 86**
```
file name: Training Presentation - Make the switch to the qqqq 2010 user interface_ZD102551.docx
dst: root
success
```

**Comment by ificator** [comment] 2017-04-11 19:59
Hi @joewutaiwan, can you provide us with the url, headers, and body for the request so we have a little more context? Thanks!

**Comment by joewutaiwan** [comment] 2017-04-25 02:19
hi @ificator thanks for reply
This issue occurs when we request the next expected range for upload
```
url: (encounter 401)
https://synologydst-my.sharepoint.com/personal/jackiel_synologydst_onmicrosoft_com/_api/v2.0/drives/b!WSWlJL1W9kyaAvz7NLW_npCY43r3-FhEj6kFGpp_XlOf_XMCDYtgRIV4u2G9zBWb/items/01FLIMP2N6Y2GOVW7725BZO354PWSELRRZ/uploadSession?guid='ce88b61f-771d-4f07-b91d-4fb19447baaf'&path='~tmp26_Training%20Presentation%20-%20Make%20the%20switch%20to%20the%20qqqq%202010%20user%20interface_Zsadasd.pdf'&overwrite=True&rename=False&access_token=[my_access_token]
```
```
header: 
Authorization: Bearer [my_access_token]
```
```
body
random 100M file
```

additional
```
url: (do not encounter 401)
https://synologydst-my.sharepoint.com/personal/jackiel_synologydst_onmicrosoft_com/_api/v2.0/drives/b!WSWlJL1W9kyaAvz7NLW_npCY43r3-FhEj6kFGpp_XlOf_XMCDYtgRIV4u2G9zBWb/items/01FLIMP2N6Y2GOVW7725BZO354PWSELRRZ/uploadSession?guid='ce88b61f-771d-4f07-b91d-4fb19447baaf'&path='~tmp26_Training%20Presentation%20-%20Make%20the%20switch%20to%20the%20qqqq%202010%20user%20interface_Zsadasd.pdf'&overwrite=True&rename=False&access_token=[my_access_token]
```

**Comment by ificator** [comment] 2017-04-25 15:57
Thanks @joewutaiwan, that's useful. Could you let me know the total length of the URL including the query parameters?

**Comment by desmondyeung** [comment] 2017-04-25 22:19
I've also recently started hitting a similar issues receiving 401 when using resumable uploads. My app has been using resumable uploads for a few months without any problems, but this recently started occurring.

In my case, I can reproduce this with a simple file name such as `test.txt`

The `access_token` and `proof_token` query parameters add almost 2000 characters to the url.

```
https://[TENANT]-my.sharepoint.com/personal/user_domain_onmicrosoft_com/_api/v2.0/drives/b!Qs6wFhq5F02aN7uvAEFontu31USLKAJGl3t44dfvOGZrDpiYd1N4S7AONDPHvLrV/items/01WEKZHRCOZMZEZ75GANF2BG7XVUTATACX/uploadSession?guid='[MY_GUID]'&path='~tmpC0_test.txt'&overwrite=True&rename=False&access_token=[ACCESS_TOKEN]&prooftoken=[PROOF_TOKEN]
```

**Comment by frenchdonah** [comment] 2017-04-28 07:39
Hi, I've the same problem on ODB, this is my url (URL length : 2233)

(https://[TENANT]-my.sharepoint.com/personal/tecnoconference_tecnoconference1_onmicrosoft_com/_api/v2.0/drive/items/01YS2LNEH4C4TWLS23OVA2T7KMPRJJ76V7/uploadSession?guid=[MY_GUID]&path='~tmp73_daricordare.pptx'&overwrite=True&rename=False&access_token=[my_access_token])

**Comment by ificator** [comment] 2017-04-29 16:23
I believe this is another variant of the investigation we're doing on #593 so I'm going to close this one since the other has more details. Feel free to reactivate if you feel otherwise.

**Closed by ificator** 2017-04-29 16:23 UTC
Labels: investigating
