### ISSUE TITLE
Permission Denied when using Graph API service to call Sharepoint with an Azure AD Guest account

### ISSUE THREAD

**Issue by deck05** [OneDrive/onedrive-api-docs#1039] opened 2019-04-03 21:40 UTC
My app is using Azure AD as an entry point to access both Sharepoint and website. 

Good Case Scenario:
I login as an AD user, the app runs as it should. I can use both Graph Api and PNP SP to retrieve data from Sharepoint. 

Issue:
If an external user (i.e. gmail, yahoo accounts) is used, the Graph Api throws permission denied error. I added the account on both the Azure AD and added it to the Sharepoint users. If I login to Sharepoint manually as an external user, the site will run perfectly fine. My guess is that the token that Graph API uses does not have the correct permissions to consume Sharepoint services. Can you please help?

#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

**Comment by chackman** [comment] 2019-04-04 02:38
The issue that you are encountering is not clear.

Please provide more information about what type of [consent is used](https://docs.microsoft.com/en-us/graph/permissions-reference#delegated-permissions-application-permissions-and-effective-permissions), what [permissions it has been granted to in Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference#sites-permissions), and how the application is getting a token from AAD.  Also are the expected permissions returned in the [token](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens)?

**Comment by mahpour** [comment] 2019-04-04 11:46
We use admin consent and we have Sites.Read.All, Sites.ReadWrite.All on SharePoint node. We get the tokens using code flow for Accessing Microsoft Graph APIs. 

The problem is all calls work for internal organization users and token provided for those can perform all expected operations. The token is not provided when a guest AAD user which is invited into O365 group makes a request. It simply returns null. But if the same guest logs in to SharePoint UI directly once then the token is issued on next attempt and user can interact with SharePoint Graph API through our SPA app.

**Comment by chackman** [comment] 2019-04-09 00:51
This sounds like a potential question for AAD.  Could you please help clarify if I have understood the steps properly?

1. Your AAD application has specified a set of required permissions for the Microsoft Graph resource, including Sites.Read.All and Sites.ReadWrite.All permission scopes.
2. The admin has consented on behalf of all users in their organization.
3. The admin invites a new guest user to the organization.
Question: how is the new guest user invited to the organization?  Is it via the AAD portal, as [referenced by the "Invite guests" topic here](https://docs.microsoft.com/en-us/office365/admin/create-groups/manage-guest-access-in-groups?view=o365-worldwide#invite-guests)?
4. Your application gets a token with [delegated permissions](https://docs.microsoft.com/en-us/graph/permissions-reference#delegated-permissions-application-permissions-and-effective-permissions) targeting the Microsoft Graph resource.
4a. If the user is internal to the organization, then the token has the Sites.Read.All and Sites.ReadWrite.All permission scopes.
4b. If the user is a guest user to the organization, and _has_ [redeemed the invitation](https://docs.microsoft.com/en-us/azure/active-directory/b2b/what-is-b2b#invite-guest-users-with-a-simple-invitation-and-redemption-process), then the token has the Sites.Read.All and Sites.ReadWrite.All permission scopes.
4c. If the user is a new guest user to the organization, and _has not_ redeemed the invitation, then the token is empty.

**Comment by mahpour** [comment] 2019-04-09 02:54
It’s almost correct. 

3. We use SharePoint package for Azure AD to perform the guest invitations. Then we add those users to the Office 365 group that is linked to our particular SharePoint site group. 

Step 4b. Is the scenario that guest users can authenticate via SSO but cannot access the SharePoint resources within that O365 group. But if they login to SharePoint UI directly using their guest account then they are able to access the SharePoint apis via Graph. 

4c. Is not an issue since users don’t have a Microsoft account to pass authentication step.

**Comment by mahpour** [comment] 2019-04-19 03:06
We have provided details on this issue and have not received any updates. @chackman has anyone looked at this ?

**Comment by chackman** [comment] 2019-04-19 19:08
Sorry, the bot didn't notice since the author did not respond.
Have you verified that the token has the appropriate scopes?
If you have please provide the request ID and date/time as requested in the issue template.

**Comment by mahpour** [comment] 2019-04-19 19:42
Yes, I don’t think the problem is about token, all internal org users can access the APIs with no problem. If the external user logs in to SharePoint interface directly once, then all API calls via graph or SharePoint APIs start working normally within our app domain. That’s very strange.

**Comment by chackman** [comment] 2019-04-20 01:44
As requested in the issue template, please provide the request ID and date/time.

**Comment by mahpour** [comment] 2019-04-24 16:56
Request is made via Sharepoint API with the Bearer token in the header.
```
Url: https://graph.microsoft.com/v1.0/sites/ontariogov.sharepoint.com,5c14b972-274c-4be8-a75c-89c11332e1d3,61d820a4-7d1c-48ac-a2e5-825d35ac751f/lists/Program%20List/items?$filter=&$select=fields&$expand=fields
```
```
Date: Wed, 24 Apr 2019 16:47:47 GMT
request-id: c73536c8-560c-429a-aff9-d6c9851341b0
I do not get the SPRequestGuid in the headers
```

Response Body:
```
{
  "error": {
    "code": "accessDenied",
    "message": "There has been an error authenticating the request.",
    "innerError": {
      "request-id": "c73536c8-560c-429a-aff9-d6c9851341b0",
      "date": "2019-04-24T16:47:48"
    }
  }
}
```

**Comment by chackman** [comment] 2019-04-26 19:14
Yes, that should help.

**Comment by chackman** [comment] 2019-05-02 23:16
Thanks for your feedback.  This looks like a bug; we are currently investigating it further.

**Comment by Thibaultce** [comment] 2020-02-06 10:26
I have the same issue as @mahpour : _If the external user logs in to SharePoint interface directly once, then all API calls via graph or SharePoint APIs start working normally within our app domain. That’s very strange._

Any update on that matter ?

**Comment by jeffcloudscale** [comment] 2020-02-21 07:20
I can confirm this exact same issue.  Also confirmed, after logging in via web, graph api auth started working again.... with the same token previously denied.

**Comment by jeffcloudscale** [comment] 2020-02-26 17:57
I seem to have found a fix:
`var result = await authContext.AcquireTokenAsync(resource, clientCred, userAssertion);`
resource = 'https://[contoso].sharepoint.com'

Then make a simple request to Sharepoint with the token:
string.Format("{0}{1}/_api/web/lists(guid'{2}')/items({3})", [resource], [sitepath], listid);

This process wakes up the Sharepoint side of the authentication.
Now just make your graph call.

**Comment by gabrielnovoa** [comment] 2020-05-01 14:37
You are probably receiving an Acces Denied message because Root Site Collection (https://tenant.sharepoint.com) has External Sharing Disabled. Try to select one of the options based on the following article: https://docs.microsoft.com/en-us/sharepoint/change-external-sharing-site

**Comment by ramumesh** [comment] 2020-06-22 06:03
@gabrielnovoa We also having the same problem and I checked and verified that the "Root Site Collection (https://tenant.sharepoint.com) has External Sharing Disabled". But if this is the root cause, then all API calls via graph or SharePoint APIs should not work normally within our application when the external user once logs in to SharePoint interface directly.

**Comment by Bortronx** [comment] 2020-07-16 18:36
I am experiencing the same issue. When I the GET request https://graph.microsoft.com/v1.0/sites/{sitename}.sharepoint.com in Microsoft Graph Explorer I get an OK status and a response like this:

```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites/$entity",
    "createdDateTime": "...",
    "description": "",
    "id": "...",
    "lastModifiedDateTime": "...",
    "name": "",
    "webUrl": "...",
    "displayName": "Communication site",
    "root": {},
    "siteCollection": {
        "hostname": "..."
       }
}
```

But when I use a guest account (that has access to the share point through the web interface in the website) it responds with a Not Found -404

`{
    "error": {
        "code": "ResourceNotFound",
        "message": "Resource not found.",
        "innerError": {
            "date": "..",
            "request-id": "..."
        }
    }
}`

**Comment by Thibaultce** [comment] 2020-09-24 08:43
@chackman can we have an update on the bug ? It does not seem to be resolved.

**Comment by fainaszar** [comment] 2020-11-25 05:55
We are facing same issue. If a guest user visits the sharepoint site via UI, they are able to access it but when we call it via Graph API it responds with "Resource Not Found", While it perfectly works for internal users.
@chackman Please update on the issue.

**Comment by Thibaultce** [comment] 2021-01-06 12:44
Any chance to have some feedback from MS on this ?

**Comment by MSchutt** [comment] 2021-03-02 22:11
I am also experiencing this same bug right now. Are there any statusupdates about this issue?

**Comment by 4straction** [comment] 2021-03-26 08:25
We are experiencing the same issue. We have many clients where we read Excel files from Graph. Authorization is done to our "service user" for individual files so we are guest users in their instance. One client is experiencing issue described above. So:

1. Authorizing to external instance works
2. Token is generated and it works for 1 hour
3. After 1 hour, we get below error
4. If we visit this shared file from a browser via external link, previously received token starts to work (for one hour)

{
  "error": {
    "code": "accessDenied",
    "message": "There has been an error authenticating the request.",
    "innerError": {
      "date": "2021-03-25T04:46:57",
      "request-id": "62a5624d-01f3-456c-836f-ac269dee06b3",
      "client-request-id": "62a5624d-01f3-456c-836f-ac269dee06b3"
    }
  }
}

So.. waiting for a fix/workaround

**Comment by darrenprunty** [comment] 2021-07-07 09:34
Anyone in Microsoft with an update on this?

**Comment by k-tsoi** [comment] 2021-08-06 17:46
The current workaround is to allow external sharing, we are still working on this.

**Comment by 4straction** [comment] 2021-09-06 09:21
> The current workaround is to allow external sharing, we are still working on this.

Can you elaborate what means "allow external sharing"? External sharing settings have "new and existing guests" on. What other settings need to be set?

![image](https://user-images.githubusercontent.com/37075391/132192960-9b884ba9-ff1f-4504-953c-5f69b9253c6d.png)

**Comment by meischj** [comment] 2021-09-20 09:33
@k-tsoi Can you give us a feedback ?  Thank you !

**Comment by k-tsoi** [comment] 2021-09-20 22:47
Unfortunately, a straight answer can not be given without knowing the exact scenarios.
I would recommend referring to this document on how to [turn external sharing on or off](https://docs.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off), and work with your organization to decide the appropriate settings required for your scenarios.

**Comment by arins** [comment] 2021-11-28 19:28
> I seem to have found a fix: `var result = await authContext.AcquireTokenAsync(resource, clientCred, userAssertion);` resource = 'https://[contoso].sharepoint.com'
> 
> Then make a simple request to Sharepoint with the token: string.Format("{0}{1}/_api/web/lists(guid'{2}')/items({3})", [resource], [sitepath], listid);
> 
> This process wakes up the Sharepoint side of the authentication. Now just make your graph call.

Worked for me! Very ugly but it works. I got a 400 response but that did not matter because after that I could make graph api calls. Really strange!

**Comment by Thibaultce** [comment] 2022-05-17 09:50
By any chances, can we have an update ? This issue is still there ...

**Comment by web265p3** [comment] 2022-06-15 20:37
I noticed the same. Even with correct permissions, guest users do not have access to ie search or download files.
Exactly the same operation is working for an internal user. We have external sharing enabled - on many site collections including the root. This does not fix it. Please provide help, Microsoft.

**Comment by patrick-rodgers** [comment] 2023-02-17 20:30
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:30 UTC
Labels: type:bug, status:investigating, automation:Closed
