### ISSUE TITLE
An Issue on updating modified time of a drive item

### ISSUE THREAD

**Issue by like9515** [OneDrive/onedrive-api-docs#1600] opened 2022-06-24 06:59 UTC
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

I used this [API](https://docs.microsoft.com/zh-tw/onedrive/developer/rest-api/api/driveitem_update?view=odsp-graph-online
) to update `lastModifiedDateTime` of a drive item. I expect both `lastModifiedDateTime` in [DriveItem](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem?view=odsp-graph-online) resource and [FileSystemInfo](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/filesysteminfo?view=odsp-graph-online) facet will be updated.

#### Observed Behavior
The API works well for accounts in a tenant (Ex: tom@cosmos.onmicrosofot.com).
However, when it comes to individual account (Ex: tom@outlook.com),  `lastModifiedDateTime` in DriveItem resource is not updated.

#### Steps to Reproduce
```
curl -v -X PATCH 'https://graph.microsoft.com/v1.0/me/drive/items/5A62BAAC76843344!148' --header 'Content-Type: application/json' --header 'Authorization: Bearer <access_token>' --data-raw '{
"fileSystemInfo": {
"lastModifiedDateTime": "2010-06-23T02:57:20Z"
}
}'

< HTTP/1.1 200 OK
< Cache-Control: private
< Transfer-Encoding: chunked
< Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
< Strict-Transport-Security: max-age=31536000
< request-id: 1bf47c05-220e-4852-90f8-bd9cc0d0967b
< client-request-id: 1bf47c05-220e-4852-90f8-bd9cc0d0967b
< x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Korea Central","Slice":"E","Ring":"3","ScaleUnit":"002","RoleInstance":"SE1PEPF00002FDD"}}
< OData-Version: 4.0
< Date: Fri, 24 Jun 2022 06:55:21 GMT
<
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('cat1pioneer%40outlook.com')/drive/items/$entity",
  "@microsoft.graph.downloadUrl": "https://xar2ig.sn.files.1drv.com/y4prjfGoXiZlta1zMgF5C4E2_Pn6APm14uHy9y9f2kcGWcqNgVvwykk04VxkC6dUGjNd3-S_llaVIGMv_Jcl_rQAdSOAMiLEJhYmvL_uuZObswxVe5z6mwhJaynxbVkZjic36ucdqI28RcCqXt4JtZee-gwEjc_WhzkHkjckwcjcc3-stF3PKlk-XaHgvSLbKlvWUaK-3DTb1BojOpa1FcCT8wTC0VWRCbJ-O74XPuPPhHQcwkQ2eEyiW7u1i5ZqHw_OLrVmNrvG9lw8Lzhy--_o6gKcueaWZnvPAURRdF-X9ogbJL-0qndvQfLcbmRfXOX",
  "createdDateTime": "2022-06-23T03:12:22.393Z",
  "cTag": "aYzo1QTYyQkFBQzc2ODQzMzQ0ITE0OC4yNTg",
  "eTag": "aNUE2MkJBQUM3Njg0MzM0NCExNDguMTA",
  "id": "5A62BAAC76843344!148",
  "lastModifiedDateTime": "2022-06-24T06:55:21.477Z",
  "name": "v1.txt",
  "size": 6,
  "webUrl": "https://1drv.ms/t/s!AEQzhHasumJagRQ",
  "reactions": {
    "commentCount": 0
  },
  "createdBy": {
    "application": {
      "displayName": "OneDrive",
      "id": "481710a4"
    },
    "user": {
      "displayName": "cat 1",
      "id": "5a62baac76843344"
    }
  },
  "lastModifiedBy": {
    "application": {
      "displayName": "Graph Explorer",
      "id": "4c1ad1* Connection #0 to host graph.microsoft.com left intact 00"
    },
    "user": {
      "displayName": "cat 1",
      "id": "5a62baac76843344"
    }
  },
  "parentReference": {
    "driveId": "5a62baac76843344",
    "driveType": "personal",
    "id": "5A62BAAC76843344!101",
    "path": "/drive/root:"
  },
  "file": {
    "mimeType": "text/plain",
    "hashes": {
      "quickXorHash": "MZDBDGhQAxsAAAAABgAAAAAAAAA=",
      "sha1Hash": "7C4A8D09CA3762AF61E59520943DC26494F8941B",
      "sha256Hash": "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92"
    }
  },
  "fileSystemInfo": {
    "createdDateTime": "2022-06-23T03:12:22.393Z",
    "lastModifiedDateTime": "2010-06-23T02:57:20Z"
  }
}
```

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by chackman** [comment] 2022-06-24 17:42
We're tracking this item internally

**Comment by ificator** [comment] 2022-06-25 20:56
I think this is by design - in the consumer endpoint lastModifiedDateTime is the system modified timestamp while file.lastModifiedDateTime is the value provided by the client. In SharePoint they are the same value because of a system limitation, but in the consumer service there is no limitation and the values are as documented.

**Comment by like9515** [comment] 2022-06-27 06:00
> I think this is by design - in the consumer endpoint lastModifiedDateTime is the system modified timestamp while file.lastModifiedDateTime is the value provided by the client. In SharePoint they are the same value because of a system limitation, but in the consumer service there is no limitation and the values are as documented.

OK. Thanks for your reply.

**Comment by patrick-rodgers** [comment] 2023-02-21 20:31
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Closed by patrick-rodgers** 2023-02-21 20:31 UTC
Labels: type:bug
