### ISSUE TITLE
createUploadProvider method is missing !

### ISSUE THREAD

**Issue by fiasko131** [OneDrive/onedrive-api-docs#644] opened 2017-06-30 09:37 UTC
Hello,
i use SDK for Android :
My code:

				`       final` String itemPath = "documents/file to copy.txt";
					final Option uploadOptions = new QueryOption("@name.conflictBehavior", "fail");
					final int chunkSize = 640 * 1024; //must be the multiple of 320KiB
					final int maxRetry = 5;

					final IProgressCallback<com.onedrive.sdk.extensions.Item> callback = new IProgressCallback<com.onedrive.sdk.extensions.Item>() {
						@Override
						public void progress(long current, long max) {

						}

						@Override
						public void success(com.onedrive.sdk.extensions.Item item) {
						}

						@Override
						public void failure(ClientException error) {

						}
					};

					CloudActivity.mOneDriveClient
							.getDrive()
							.getRoot()
							.getItemWithPath(itemPath)
							.getCreateSession(sessionDescriptor)
							.buildRequest()
							.post()
	can't resolve method------->	.createUploadProvider(mOneDriveClient, input, poidOfFile, com.onedrive.sdk.extensions.Item.class)
							.upload(Collections.singletonList(uploadOptions),
									callback,
									chunkSize,
									maxRetry);`
My dependencies in my build.gradle:

> compile ('com.onedrive.sdk:onedrive-sdk-android:1.2+') {
        transitive = false
    }
    compile ('com.google.code.gson:gson:2.3.1')
    compile ('com.microsoft.services.msa:msa-auth:0.8.+')
    compile ('com.microsoft.aad:adal:1.1.+')
>
I have the same issue if i try to compile the same dependencies in the new android project.
Any ideas?
Thanks

**Comment by daboxu** [comment] 2017-07-14 16:42
hi @fiasko131 , the chunked upload is out with release [version 1.3.1](https://github.com/OneDrive/onedrive-sdk-android/releases/tag/1.3.1), try bump your version.

testes with
```
    compile 'com.onedrive.sdk:onedrive-sdk-android:1.3+'
    compile 'com.google.code.gson:gson:2.3.1'
    compile 'com.microsoft.services.msa:msa-auth:0.8.4'
    compile 'com.microsoft.aad:adal:1.1.+'
```

and it works for me.

**Comment by fiasko131** [comment] 2017-07-15 18:53
Hi @daboxu , i've updated my dependencies and it works now.
The method works great with local file, but with an inputstream for another cloud provider...it's very slow or fail!?
Is there a method with this sdk to upload from an inputStream from URL?
Or for example, does GoogleDrive provide an inputstream for uploading to Onedrive?

And I take the opportunity to go up an issue I posted on the sdk github for android:
https://github.com/OneDrive/onedrive-sdk-android/issues/124

Thank you for spending time.

Regards

**Comment by daboxu** [comment] 2017-07-17 16:57
@fiasko131 sorry in the SDK I think we don't support that. The large file uploader is designed for uploading local large files. I looked up the [Google Drive's documents](https://developers.google.com/drive/android/files) and it seems they are the bottle neck of the uploading. I would suggest you download the Google Drive's file to local and then upload it to OneDrive. Thanks for letting me know there is a inputStream interface for Google Drive on Android, we will consider utilize it for future stories.

**Comment by fiasko131** [comment] 2017-07-18 08:53
@daboxu for my application I use sdks for Android of DropBox, Googledrive, and box. With these three sdks I can upload a file directly from a URL and therefore from an InputStream.
- For googleDrive for example:
`InputStreamContent mediaContent = null;
					com.google.api.services.drive.model.File body = new com.google.api.services.drive.model.File();
					body.setTitle(name);
					body.setParents(
							Arrays.asList(new ParentReference().setId(mCurrentDriveFolderId)));
					Drive.Files.Insert insert;
					mediaContent = new InputStreamContent("", new BufferedInputStream(input) {
						@Override
						public int read() throws IOException {

							return 0;
						}
						@Override
						public int read(byte[] buffer,
										int byteOffset, int byteCount)
								throws IOException {

							return super.read(buffer, byteOffset, byteCount);
						}
					});
					mediaContent.setLength(length);
					insert = googleDriveService.files().insert(body, mediaContent);
					MediaHttpUploader uploader = insert.getMediaHttpUploader();
					CustomProgressListener listener = new CustomProgressListener();
					uploader.setProgressListener(listener);
					uploader.setDirectUploadEnabled(false).setChunkSize(MediaHttpUploader.MINIMUM_CHUNK_SIZE);
					com.google.api.services.drive.model.File f = insert.execute();`
- for Box:
`BoxFile f = mFileApi.getUploadRequest(input,checkedName,mCurrentBoxFolderId ).send();`
etc ...
In each case inputstream (input) is from a cloud provider or a URL.
By this way, I can easily copy a file from one account (same provider or not) to another without going through an outputstream buffer. This is not a good solution for a mobile application.
I find it curious that the ondrive sdk does not offer this possibility, it's annoying for the user.
Thank you for your support.

**Comment by daboxu** [comment] 2017-07-18 16:39
@fiasko131 as far as I can read from your example of Box and Dropbox, they both provides the interface as an inputStream as the OneDriveSDK does. The problem is that the inputStream reading bytes from another cloud storage provider is very slow so that's why I proposed you use local storage as a cache. I am wondering have you tested with Box and DropBox with the same input stream? Looking forward for a performance test result.

**Comment by fiasko131** [comment] 2017-07-19 09:23
Hi @daboxu ,
Here is video 3 videos showing:
-upload onedrive to box
https://1drv.ms/v/s!Aotc-z6VC9w4gq0M4Vx35566wLPtqA
-upload onedrive to googledrive
https://1drv.ms/v/s!Aotc-z6VC9w4gq0N-ZuOchH6Pe6vkw
-upload box to onedrive
https://1drv.ms/v/s!Aotc-z6VC9w4gq0M4Vx35566wLPtqA
As you can see the transfers are very correct except in the case of onedrive with uploadProvider.
In other cases there are no buffer files during the upload.

Performed in 4g (download 7mb / s upload 4mb / s)

Regards.

**Comment by daboxu** [comment] 2017-07-19 16:24
@fiasko131 thanks for the video, what's your chunksize passed in? That could be a bottleneck I guess.

```java
.createUploadProvider(mOneDriveClient, input, poidOfFile, com.onedrive.sdk.extensions.Item.class)
						.upload(Collections.singletonList(uploadOptions),
								callback,
								chunkSize,
								maxRetry);
```

**Comment by fiasko131** [comment] 2017-07-19 16:34
@daboxu  i try 320,640,1280 but no way....??

**Comment by daboxu** [comment] 2017-07-19 16:39
320 Bytes? The server side supports max 60 * 1024 * 1024 which is 60 MiB.

**Comment by fiasko131** [comment] 2017-07-19 16:51
Sorry 320*1024, 640*1024, 1280*1024

**Comment by daboxu** [comment] 2017-07-19 17:01
thanks for clarifying that, I will take a look to see how to uplaod from another cloud provider. Another approach you can try is the upload from uri API which is under preview, https://dev.onedrive.com/items/upload_url.htm. Unfortunately we don't have a plan to integrate it into SDK yet, so you need write the HttpRequest part by your self, while you can get the access token from the oneDrive client.

**Comment by patrick-rodgers** [comment] 2023-02-17 20:22
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:22 UTC
Labels: automation:Closed
