### ISSUE TITLE
Forbidden to access camera roll

### ISSUE THREAD

**Issue by ddurdle** [OneDrive/onedrive-api-docs#110] opened 2015-05-08 18:38 UTC
I always get an error 403 Forbidden when trying to access the camera roll through the API.

https://api.onedrive.com/v1.0/drive/special/cameraroll/children

I've tried with the following scopes:
wl.contacts_photos
wl.contacts_skydrive
wl.skydrive
wl.photos

**Comment by peternied** [comment] 2015-05-08 18:46
The scopes between OneDrive and the LiveConnect APIs are different, you can see the full list under the authentication and scope section, https://dev.onedrive.com/auth/msa_oauth.htm

For your scenario where you want to read from the camera roll if you added the onedrive.readonly scope you will be able to access that folder, you shouldn't need the rest of the scopes (Saved for wl.signin & wl.offline_access which your application might be using)

**Comment by ddurdle** [comment] 2015-05-08 19:07
I tried with onedrive.readonly as well

I used the following to authorize:
https://login.live.com/oauth20_authorize.srf?client_id=000000004412F032&scope=wl.offline_access%20onedrive.readonly&response_type=code&redirect_uri=https://login.live.com/oauth20_desktop.srf

I still get a 403 Forbidden.  I even tried subbing in the access token on the apigee console and it produces the 403 there.  It's very unclear which scope is required to access the Camera Roll.

The documentation for special folders doesn't indicate any special requires scopes  https://dev.onedrive.com/items/special_folders.htm

**Comment by peternied** [comment] 2015-05-08 19:10
@ddurdle would you mind including the the full response headers so I can better understand what system is acting up as I'm unable to reproduce this problem locally.

**Comment by ddurdle** [comment] 2015-05-08 19:15
Hopefully this helps:

HTTP/1.1 403 Forbidden
X-MSNSERVER:
DM2303____PAP184
Content-Length:
96
X-AsmVersion:
UNKNOWN; 19.18.0.0
Connection:
keep-alive
Server:
Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
X-QosStats:
{"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}
Strict-Transport-Security:
max-age=31536000; includeSubDomains
Strict-Transport-Security:
max-age=31536000; includeSubDomains
Date:
Fri, 08 May 2015 19:14:42 GMT
X-ThrowSite:
022b.92e9
P3P:
CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
Via:
1.1 BY3301____PAP187 (wls-colorado)
Content-Type:
application/json
X-WLSPROXY:
BY3301____PAP187

{
  "error":  {
    "code": "accessDenied",
    "message": "Access Denied",
    "innererror":  {
      "code": "accessDenied"
    }
  }
}

**Comment by ddurdle** [comment] 2015-05-08 19:16
I also tried the other special folders -- documents, photos, music -- same 403 error.  I can access folders and files using drive/root or drive/items, but I cannot seem to access anything through drive/special

**Comment by peternied** [comment] 2015-05-08 19:19
Aha! Thanks so much for that trace, I understand what is going wrong, we attempt to auto-create the app folders if they don't exist, and since you are using readonly permissions you don't have the rights to create them.  Thanks for finding this bug, we'll let you know when we get this resolved.

Until that time, you could work around this issue by adding the onedrive.readwrite scope.

**Comment by ddurdle** [comment] 2015-05-08 19:29
Perfect, thx!  I can live with that workaround for now.

Great support and a great turnaround time.  Users will be happy.

**Comment by tipa** [comment] 2015-09-17 11:27
when will this be resolved?

**Comment by amanghag** [comment] 2015-09-17 18:31
Have you tried using the onedrive.appfolder scope?  this provides access only to the specific app in question and no read/write access to other parts of a users OneDrive.  This should be working as expected currently.

**Comment by tipa** [comment] 2015-09-18 06:42
Like the OP, I am trying to access the Camera Roll, not the app folder in OneDrive

**Comment by amanghag** [comment] 2015-09-25 18:10
Tipa, accessing Camera Roll will require using onedrive.readwrite, this is by design.  If there is another issue can you please update with that for us to look into it?

**Comment by tipa** [comment] 2015-09-25 21:00
If this is by design - what is pretty strange as I do not need write access - I have no other issues, thanks!

**Comment by rgregg** [comment] 2015-09-30 06:37
To clarify, if you have read-only access to OneDrive and you try to access a special folder that doesn't exist (say, the user hasn't enabled camera roll backup) then you'll get an error that the folder doesn't exist. Today that is returned as a 403 Forbidden, and should instead be returned as a 404 Not Found (this is a bug). If the folder does already exist, read access is all you need to be able to consume the content of the folder.

**Comment by Joel95** [comment] 2015-10-12 21:47
Sorry,I'm having the same issue reported here and the only possibility to access special folders (documents, photos and cameraroll) is to get a token using onedrive.readwrite scope.

**Comment by daspek** [comment] 2015-10-13 02:24
Hi @Joel95, the issue is when the camera roll folder doesn't already exist for the user. If it doesn't exist and you have the readonly scope, OneDrive returns 403. This is a bug. It should return 404. If it doesn't exist and you have the readwrite scope, it will auto-create the folder and return an empty folder. For now, your code can assume that 403 means the camera roll folder doesn't exist (and is empty).

**Comment by Joel95** [comment] 2015-10-13 06:00
Let me describe the test done.

1 - I do a get token using scope "onedrive.readonly onedrive.appfolder wl.photos wl.offline_access".
OneDrive return 403 on special/photos, special/documents, special/cameraroll.

2- I do a get token using scope "onedrive.readwrite onedrive.appfolder wl.photos wl.offline_access".
OneDrive return 200 Ok with all informations about special folders.

Second step shows that folders already exist and onedrive.readonly is no enough to get access...
I need onedrive.appfolder to be able to write in App folder.
I use wl.photos because I need access to photos only in other folders.
Now, I did a test with scope "onedrive.readonly wl.offline_access", same result...

I hope this help and you will find the root cause.
Regards

**Comment by daspek** [comment] 2015-10-14 06:03
Hi @Joel95, we deployed a fix for the 403 error when a special folder doesn't exist. Can you try again? Also, the wl.photos scope is for the old LiveConnect API, and isn't used by the new OneDrive API, so you don't need to include it.

**Comment by Joel95** [comment] 2015-10-14 19:51
Hello Daspek,
I did the test and it works now.
I've a question about LiveConnect API but I'll open another case.
Thank you very much.

**Comment by ginach** [comment] 2015-10-29 19:12
Reopening since we reverted the fix.

**Comment by tipa** [comment] 2015-10-29 22:09
Seriously??? Now my app, which is live, will not work because I have the "onedrive.readonly" capability only? What will be the desired behaviour of the camera roll?

**Comment by Joel95** [comment] 2015-10-29 22:26
Same problem on my side.

**Comment by daspek** [comment] 2015-10-29 22:50
@tipa, @Joel95, firstly we're really sorry about all this. We know how frustrating it is for a fix to stop working for a live app. Our fix for this was part of a larger change, and after turning it on we discovered that it broke something else and we had to turn it off. We're working to turn it back on as soon as we can.

To clarify, though, the only expected difference between the current behavior and the fix is the error code that it returns. Without the fix (right now), it returns 403 if the user does not have a camera roll. With the fix, it returns 404. If the user does have a camera roll, their data is returned and accessible.

So as long as your app treats 403 the same as 'no camera roll available' you should be okay. In the meantime, we're working to put the fix back as soon as we can.

Thanks for your patience.

daron

**Comment by tipa** [comment] 2015-10-29 23:38
"If the user does have a camera roll, their data is returned and accessible." - this is all I need, thank you! :) :+1:

**Comment by daspek** [comment] 2015-10-30 01:06
That wasn't actually the case before. There was some confusion. You need onedrive.readwrite to get a new cameraroll auto-created if there isn't one already. But if there already is one, you only need onedrive.readonly.

**Comment by amanghag** [comment] 2015-11-24 21:15
This issue of returning 404 is now resolved - thank you for your patience.

**Closed by amanghag** 2015-11-24 21:15 UTC
Labels: bug
