### ISSUE TITLE
Upload button missing from filepicker UI

### ISSUE THREAD

**Issue by LindsPY** [OneDrive/onedrive-api-docs#1190] opened 2019-11-20 14:57 UTC
- [] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
When filepicker is loaded 'Upload' should be displayed alongside 'New folder' option on top toolbar
![image](https://user-images.githubusercontent.com/57997733/69248772-c96b0e80-0ba4-11ea-8418-8db607eccefa.png)

#### Observed Behavior
NOTE: using Chrome this issue is seen every time; using Edge or Firefox the appearance of the Upload button is inconsistent - sometimes it is present as expected , other times not.
'Upload' option is missing from top toolbar
![image](https://user-images.githubusercontent.com/57997733/69248840-e56eb000-0ba4-11ea-96bf-db09d9800316.png)

#### Steps to Reproduce
Filepicker is loaded from JS as below
`odOptions = {
                    clientId: "@Startup.ClientId",
                    action: "query",
                    multiSelect: true,
                    viewType: "all",
                    advanced: {
                        endpointHint: endpoint,
                        accessToken: token,
                        navigation: {
                            sourceTypes: "Sites"
                        }
                    },
                    success: ProcessSharepointResponse
}
OneDrive.open(odOptions);`

Upload option can be forced to appear if site is selected from left hand navigation menu after picker has loaded. 
Can something be changed in the options to force the Upload button to be displayed straight away
Thank you.

**Comment by mbrzakala** [comment] 2020-12-23 17:24
I have the same problem with disappearing Upload button. In my case it depends on an account type of the user. I support both individual and organization accounts and problem appears only with organization type. My configuration is
{          
     clientId: '#clientId',     action: "share",
     multiSelect: true,
     accountSwitchEnabled: true,
     advanced: {
        redirectUri: "#redirectUrl",
        createLinkParameters: {
           type:'view', 
           scope:'organization'
         }
     }
}
I've been using it in production since march/april and everything was fine until december. Clicking on the left hand navigation menu does not help in my case. Drag&drop still works, only the top Upload button is missing. Our users are used to Upload button, we have a lot of reports about this case every day. I would appreciate any help. Thank you in advance.

**Comment by mgifp** [comment] 2021-02-03 04:45
I have same problem, attaching video with reproducing. Any plans for fixing it?

https://user-images.githubusercontent.com/73522503/106699299-a7b44680-65f3-11eb-9e3d-201d8a74de98.mp4

**Comment by patrick-rodgers** [comment] 2023-02-17 20:35
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:35 UTC
Labels: area:Picker, Needs: Investigation, automation:Closed
