### ISSUE TITLE
Download file By server relative url in hebrew

### ISSUE THREAD

**Issue by yuribb** [OneDrive/onedrive-api-docs#470] opened 2016-11-09 16:59 UTC
Hello. I use service account authentication to work with drive.
I tried to download file with name in hebrew by link:

"https://tenant.sharepoint.com/sites/mySite/_api/web/GetFileByServerRelativeUrl('/sites/mySite/%D7%91%D7%99%D7%95%D7%AA%D7%A8%2C%20%D7%A2%D7%9C%20%D7%90%D7%A3%20%D7%A9%D7%94%D7%90%D7%96%D7%95%D7%A8%D7%99%D7%9D/456/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%20%D7%97%D7%93%D7%A9.txt')/$value"

But i've got an Internal Server Error with response:

"<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-2130247151, Microsoft.SharePoint.SPException</m:code><m:message xml:lang="he-IL">אין אפשרות לפתוח את הקובץ "סמך טקסט חדש.txt".</m:message></m:error>'". How can i download this file?

**Comment by yuribb** [comment] 2016-11-15 16:23
I Created  4 Links with file name in hebrew:

https://tenant.sharepoint.com/sites/mySite/_api/web/GetFileByServerRelativeUrl('/sites/mySite/Documents/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%20%D7%97%D7%93%D7%A9.txt')/$value

https://tenant.sharepoint.com/sites/mySite/_api/web/GetFileByServerRelativeUrl(@v)/$value?@v='/sites/mySite/Documents/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%20%D7%97%D7%93%D7%A9.txt'

https://tenant.sharepoint.com/sites/mySite/_api/web/GetFileByServerRelativeUrl('/sites/mySite/Documents/סמך טקסט ‫חדש.txt')/$value

https://tenant.sharepoint.com/sites/mySite/_api/web/GetFileByServerRelativeUrl(@v)/$value?@v='/sites/mySite/Documents/סמך טקסט ‫חדש.txt'

All these links return the error, which i have in previous comment.

**Comment by ificator** [comment] 2016-11-16 19:27
I tried to repro this on my dev box and was unable - everything seemed to work as expected. Therefore, to help get to the bottom of what's going on I'll need the `request-id` header from one of the failure responses.

**Comment by ificator** [comment] 2016-11-16 19:30
Actually, the error code (`-2130247151`) actually maps to `SPErrorCode.V_FILE_EXISTS`. That really shouldn't occur on a `GET`, so can you confirm you aren't issuing a `PUT`/`PATCH`/`POST`?

**Comment by yuribb** [comment] 2016-11-17 09:48
Headers: 
Transfer-Encoding: chunked
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
DATASERVICEVERSION: 3.0
SPClientServiceRequestDuration: 105
SPRequestDuration: 162
SPRequestGuid: 8aaab79d-d038-3000-a6cd-fb82469d9dbe
request-id: 8aaab79d-d038-3000-a6cd-fb82469d9dbe
Content-Type: application/xml;charset=utf-8

**Comment by ificator** [comment] 2017-02-11 02:59
I apologize for dropping the ball on this issue - are you still seeing it? If so, I'll need another `request-id` and `date` value from one of the responses.

**Comment by yuribb** [comment] 2017-02-21 12:53
Get File info: 
https://tenant-my.sharepoint.com//personal/email_tenant_onmicrosoft_com/_api/web/GetFileByServerRelativeUrl(@v)?@v='/personal/email_tenant_onmicrosoft_com/Documents/סמך טקסט ‫חדש.txt'

Works fine. Result:
{
  "odata.metadata": "https://tenant-my.sharepoint.com/personal/email_tenant_onmicrosoft_com/_api/$metadata#SP.ApiData.Files12/@Element",
  "odata.type": "SP.File",
  "odata.id": "https://tenant-my.sharepoint.com/personal/email_tenant_onmicrosoft_com/_api/Web/GetFileByServerRelativeUrl('/personal/email_tenant_onmicrosoft_com/Documents/סמך טקסט חדש.txt')",
  "odata.editLink": "Web/GetFileByServerRelativeUrl('/personal/email_tenant_onmicrosoft_com/Documents/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%20%D7%97%D7%93%D7%A9.txt')",
  "CheckInComment": "",
  "CheckOutType": 2,
  "ContentTag": "{uniqueId},1,1",
  "CustomizedPageStatus": 0,
  "ETag": "\"{uniqueId},1\"",
  "Exists": true,
  "IrmEnabled": false,
  "Length": "5194",
  "Level": 1,
  "LinkingUri": null,
  "LinkingUrl": "",
  "MajorVersion": 1,
  "MinorVersion": 0,
  "Name": "סמך טקסט חדש.txt",
  "ServerRelativeUrl": "/personal/email_tenant_onmicrosoft_com/Documents/סמך טקסט חדש.txt",
  "TimeCreated": "2017-02-21T12:05:20Z",
  "TimeLastModified": "2017-02-21T12:05:20Z",
  "Title": null,
  "UIVersion": 512,
  "UIVersionLabel": "1.0",
  "UniqueId": "uniqueId"
}



Get varsions info:
https://tenant-my.sharepoint.com//personal/email_tenant_onmicrosoft_com/_api/web/GetFileByServerRelativeUrl(@v)/Versions?@v='/personal/email_tenant_onmicrosoft_com/Documents/סמך טקסט ‫חדש.txt'

Works fine.Result:
{
	"odata.metadata":"https://tenant-my.sharepoint.com/personal/email_tenant_onmicrosoft_com/_api/$metadata#SP.ApiData.FileVersions",
	"value":[]
}


Get file content: 
https://tenant-my.sharepoint.com//personal/email_tenant_onmicrosoft_com/_api/web/GetFileByServerRelativeUrl(@v)/$value?@v='/personal/email_tenant_onmicrosoft_com/Documents/סמך טקסט ‫חדש.txt'


Not working. Error response result:

Message: 
'The remote server returned an error: (500) Internal Server Error.
StatusCode:InternalServerError
Response:
<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-2130247151, Microsoft.SharePoint.SPException</m:code><m:message xml:lang="en-US">Cannot open file "סמך טקסט חדש.txt".</m:message></m:error>'

Headers: 
Transfer-Encoding: chunked
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
DATASERVICEVERSION: 3.0
SPClientServiceRequestDuration: 78
SPRequestDuration: 141
SPRequestGuid: 202ed79d-b09e-3000-d6c2-25e0b086c3ca
request-id: 202ed79d-b09e-3000-d6c2-25e0b086c3ca
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
MicrosoftSharePointTeamServices: 16.0.0.6209
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
Cache-Control: private, max-age=0
Content-Type: application/xml;charset=utf-8
Date: Tue, 21 Feb 2017 12:46:11 GMT
Expires: Mon, 06 Feb 2017 12:46:11 GMT
Last-Modified: Tue, 21 Feb 2017 12:46:11 GMT
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET

Response: 
'<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-2130247151, Microsoft.SharePoint.SPException</m:code><m:message xml:lang="en-US">Cannot open file "סמך טקסט חדש.txt".</m:message></m:error>'

**Comment by yuribb** [comment] 2017-02-21 13:01
https://tenant-my.sharepoint.com//personal/email_tenant_onmicrosoft_com/_api/web/GetFileByServerRelativeUrl(@v)/$value?@v='/personal/email_tenant_onmicrosoft_com/Documents/סמך טקסט חדש.txt'

Not working. Error response result:

Message: 
'The remote server returned an error: (500) Internal Server Error.
StatusCode:InternalServerError
Response:
<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-2130247151, Microsoft.SharePoint.SPException</m:code><m:message xml:lang="en-US">Cannot open file "סמך טקסט חדש.txt".</m:message></m:error>'

Headers: 
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
DATASERVICEVERSION: 3.0
SPClientServiceRequestDuration: 113
SPRequestDuration: 246
SPRequestGuid: df2ed79d-1011-3000-d6c2-2c9e3bcb51db
request-id: df2ed79d-1011-3000-d6c2-2c9e3bcb51db
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
MicrosoftSharePointTeamServices: 16.0.0.6209
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
Connection: close
Cache-Control: private, max-age=0
Content-Type: application/xml;charset=utf-8
Date: Tue, 21 Feb 2017 12:59:11 GMT
Expires: Mon, 06 Feb 2017 12:59:12 GMT
Last-Modified: Tue, 21 Feb 2017 12:59:12 GMT
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET

Response: 
'<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-2130247151, Microsoft.SharePoint.SPException</m:code><m:message xml:lang="en-US">Cannot open file "סמך טקסט חדש.txt".</m:message></m:error>'

**Comment by ificator** [comment] 2017-02-21 16:47
Thanks @yuribb!

**Comment by ificator** [comment] 2017-02-22 15:57
Hi @yuribb, I have a couple of follow up questions:
1. Is this specific file the only one that has the issue?
2. If you rename the file to, say, an English name does the request for the content work?
3. If you use the OneDrive API to get the file content does that work (when the file has the original name)?

**Comment by yuribb** [comment] 2017-02-22 17:16
1. This works with any files. Works with Hebrew names (but doesn't work with Hebrew characters, this requires a word written from right to left). 
2. If I rename a file to English then this file is downloadable. If I rename a file with English name to hebrew then this file is not downloadable. 
3. Downloading via OneDrive API doesn't work with Service Account https://github.com/OneDrive/onedrive-api-docs/issues/280.

**Comment by ificator** [comment] 2017-02-22 17:39
Definitely strange!

Can you provide the URL that is going across the wire (i.e. that's URL encoded etc.)?

When I'm trying to repro I'm using a URL that looks like:

    https://tenant-my.sharepoint.com//personal/email_tenant_onmicrosoft_com/_api/web/GetFileByServerRelativeUrl(@v)/$value?@v='/personal/email_tenant_onmicrosoft_com/Documents/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%20%D7%97%D7%93%D7%A9.txt'

**Comment by yuribb** [comment] 2017-02-24 14:53
this URL doesn't work too. WIth the same result.

**Comment by yuribb** [comment] 2017-02-27 16:51
https://tenant-my.sharepoint.com//personal/email_tenant_onmicrosoft_com/_api/web/GetFileByServerRelativeUrl(@v)/$value?@v='/personal/email_tenant_onmicrosoft_com/Documents/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%20%E2%80%AB%D7%97%D7%93%D7%A9.txt'

Not working. Error response result:

Message: 'The remote server returned an error: (500) Internal Server Error.'
StatusCode: InternalServerError
Status: ProtocolError

Headers: 
Transfer-Encoding: chunked
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
DATASERVICEVERSION: 3.0
SPClientServiceRequestDuration: 46
SPRequestDuration: 91
SPRequestGuid: 672ad99d-40ef-2000-da9e-3fb4ad4fea51
request-id: 672ad99d-40ef-2000-da9e-3fb4ad4fea51
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
MicrosoftSharePointTeamServices: 16.0.0.6202
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
Cache-Control: private, max-age=0
Content-Type: application/xml;charset=utf-8
Date: Mon, 27 Feb 2017 16:48:59 GMT
Expires: Sun, 12 Feb 2017 16:49:00 GMT
Last-Modified: Mon, 27 Feb 2017 16:49:00 GMT
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET

Response: 
'<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-2130247151, Microsoft.SharePoint.SPException</m:code><m:message xml:lang="en-US">Cannot open file "סמך טקסט חדש.txt".</m:message></m:error>'

**Comment by ificator** [comment] 2017-02-27 17:14
Hi @yuribb, I appreciate your patience while we try to figure this out!

Since you mentioned that the requests without `$value` work I'd be curious to see the response headers for one of those requests. Can you hit the following and then dump the headers from the response?

https://tenant-my.sharepoint.com//personal/email_tenant_onmicrosoft_com/_api/web/GetFileByServerRelativeUrl(@v)?@v='/personal/email_tenant_onmicrosoft_com/Documents/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%20%E2%80%AB%D7%97%D7%93%D7%A9.txt'

Thanks!

**Comment by yuribb** [comment] 2017-02-27 17:31
'https://tenant-my.sharepoint.com//personal/email_tenant_onmicrosoft_com/_api/web/GetFileByServerRelativeUrl(@v)?@v='/personal/email_tenant_onmicrosoft_com/Documents/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%20%E2%80%AB%D7%97%D7%93%D7%A9.txt'

Headers:

Transfer-Encoding: chunked
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
DATASERVICEVERSION: 3.0
SPClientServiceRequestDuration: 31
SPRequestDuration: 196
SPRequestGuid: ac2cd99d-200a-2000-72a5-5c1e161cc0b9
request-id: ac2cd99d-200a-2000-72a5-5c1e161cc0b9
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
MicrosoftSharePointTeamServices: 16.0.0.6216
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
Cache-Control: private, max-age=0
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
Date: Mon, 27 Feb 2017 17:28:36 GMT
Expires: Sun, 12 Feb 2017 17:28:36 GMT
Last-Modified: Mon, 27 Feb 2017 17:28:36 GMT
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET

Response:

{
  "odata.metadata": "https://tenant-my.sharepoint.com/personal/email_tenant_onmicrosoft_com/_api/$metadata#SP.ApiData.Files12/@Element",
  "odata.type": "SP.File",
  "odata.id": "https://tenant-my.sharepoint.com/personal/email_tenant_onmicrosoft_com/_api/Web/GetFileByServerRelativeUrl('/personal/email_tenant_onmicrosoft_com/Documents/סמך טקסט חדש.txt')",
  "odata.editLink": "Web/GetFileByServerRelativeUrl('/personal/email_tenant_onmicrosoft_com/Documents/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%20%D7%97%D7%93%D7%A9.txt')",
  "CheckInComment": "",
  "CheckOutType": 2,
  "ContentTag": "{21FD11D4-A304-4944-BC7B-093C14A37C17},11,3",
  "CustomizedPageStatus": 0,
  "ETag": "\"{21FD11D4-A304-4944-BC7B-093C14A37C17},11\"",
  "Exists": true,
  "IrmEnabled": false,
  "Length": "4134",
  "Level": 1,
  "LinkingUri": null,
  "LinkingUrl": "",
  "MajorVersion": 7,
  "MinorVersion": 0,
  "Name": "סמך טקסט חדש.txt",
  "ServerRelativeUrl": "/personal/email_tenant_onmicrosoft_com/Documents/סמך טקסט חדש.txt",
  "TimeCreated": "2017-02-21T12:05:20Z",
  "TimeLastModified": "2017-02-27T17:20:59Z",
  "Title": null,
  "UIVersion": 3584,
  "UIVersionLabel": "7.0",
  "UniqueId": "21fd11d4-a304-4944-bc7b-093c14a37c17"
}

**Comment by ificator** [comment] 2017-02-28 02:10
Hi @yuribb, can you try this URL instead and see if it works?

    https://tenant-my.sharepoint.com/personal/email_tenant_onmicrosoft_com/_api/web/GetFileByServerRelativeUrl(@v)/$value?@v='/personal/email_tenant_onmicrosoft_com/Documents/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%E2%80%AB%20%D7%97%D7%93%D7%A9.txt'

**Comment by yuribb** [comment] 2017-02-28 16:04
https://tenant-my.sharepoint.com//personal/email_tenant_onmicrosoft_com/_api/web/GetFileByServerRelativeUrl(@v)/$value?@v='/personal/email_tenant_onmicrosoft_com/Documents/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%20%D7%97%D7%93%D7%A9.txt'

Message: The remote server returned an error: (500) Internal Server Error.
StatusCode: InternalServerError
Status: ProtocolError

Response:
'<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-2130247151, Microsoft.SharePoint.SPException</m:code><m:message xml:lang="en-US">Cannot open file "סמך טקסט חדש.txt".</m:message></m:error>'

Headers: 
Transfer-Encoding: chunked
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
DATASERVICEVERSION: 3.0
SPClientServiceRequestDuration: 45
SPRequestDuration: 97
SPRequestGuid: 2b7ad99d-c0d2-2000-da9e-363e5548389d
request-id: 2b7ad99d-c0d2-2000-da9e-363e5548389d
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
MicrosoftSharePointTeamServices: 16.0.0.6216
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
Cache-Control: private, max-age=0
Content-Type: application/xml;charset=utf-8
Date: Tue, 28 Feb 2017 16:03:00 GMT
Expires: Mon, 13 Feb 2017 16:03:00 GMT
Last-Modified: Tue, 28 Feb 2017 16:03:00 GMT
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET

**Comment by ificator** [comment] 2017-02-28 17:44
Ok, finally some good news... I have a repro!

There's actually a *slight* difference between the persisted name and the name being requested - here's what I did.

Created the file
> PUT http://host/_api/v2.0/drive/root:/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%20%D7%97%D7%93%D7%A9.txt:/content
> 201 Created (application/json)

Retrieved the file metadata - success!
> GET http://host/personal/me/_api/web/GetFileByServerRelativeUrl(@v)?@v='/personal/me/Documents/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%20%D7%97%D7%93%D7%A9.txt'
> 200 OK (application/atom+xml)

Retrieved the file content - success!
> GET http://host/personal/me/_api/web/GetFileByServerRelativeUrl(@v)/$value?@v='/personal/me/Documents/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%20%D7%97%D7%93%D7%A9.txt'
> 200 OK (application/octet-stream)

Now here's where it gets tricky... we'll make the same request but include the special `U+202B` character that signifies right-to-left!

Retrieve the file metadata - success!
> GET http://sp-my.devinstall/personal/bcleaver/_api/web/GetFileByServerRelativeUrl(@v)?@v='/personal/bcleaver/Documents/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%E2%80%AB%20%D7%97%D7%93%D7%A9.txt'
> 200 OK (application/atom+xml)

Retrieve the file content - failure?
> GET http://sp-my.devinstall/personal/bcleaver/_api/web/GetFileByServerRelativeUrl(@v)/$value?@v='/personal/bcleaver/Documents/%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%E2%80%AB%20%D7%97%D7%93%D7%A9.txt'
> 500 Internal Server Error (application/xml)

Comparing the two names side-by-side so it's a little clearer:
```
%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98         %20%D7%97%D7%93%D7%A9.txt
%D7%A1%D7%9E%D7%9A%20%D7%98%D7%A7%D7%A1%D7%98%E2%80%AB%20%D7%97%D7%93%D7%A9.txt
```

So essentially, the name being used to retrieve the contents isn't the same name that was used to create the file, and so we're failing out. The confusing part is that the name is "close enough" that the metadata fetch works.

I can confirm, however, that the OneDrive API does work for both metadata and content, and so once daemon/apponly support is available I'd definitely recommend switching over.

**Comment by ificator** [comment] 2017-03-07 20:41
I'm going to close this out as the "OneDrive API" that is documented by this repo works as expected. It's unlikely there will be any fixes to the older REST API at this point.

**Closed by ificator** 2017-03-07 20:41 UTC

**Comment by yuribb** [comment] 2017-03-13 14:57
I'm sorry, but it doesn't work.

Message: 'The remote server returned an error: (500) Internal Server Error.'
StatusCode:InternalServerError
Status:ProtocolError
Response: '<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-2130247151, Microsoft.SharePoint.SPException</m:code><m:message xml:lang="en-US">Cannot open file "סמך טקסט חדש.txt".</m:message></m:error>'

Headers: 
Transfer-Encoding: chunked
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
DATASERVICEVERSION: 3.0
SPClientServiceRequestDuration: 51
SPRequestDuration: 111
SPRequestGuid: 6da5dd9d-d015-3000-72a5-5613e8ef1a90
request-id: 6da5dd9d-d015-3000-72a5-5613e8ef1a90
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
MicrosoftSharePointTeamServices: 16.0.0.6302
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
Cache-Control: private, max-age=0
Content-Type: application/xml;charset=utf-8
Date: Mon, 13 Mar 2017 14:54:37 GMT
Expires: Sun, 26 Feb 2017 15:54:38 GMT
Last-Modified: Mon, 13 Mar 2017 14:54:38 GMT
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET

**Comment by yuribb** [comment] 2017-03-21 11:57
@ificator  I'm sorry, but it doesn't work.

Message: 'The remote server returned an error: (500) Internal Server Error.'
StatusCode:InternalServerError
Status:ProtocolError
Response: '<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-2130247151, Microsoft.SharePoint.SPException</m:code><m:message xml:lang="en-US">Cannot open file "סמך טקסט חדש.txt".</m:message></m:error>'

Headers: 
Transfer-Encoding: chunked
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0
DATASERVICEVERSION: 3.0
SPClientServiceRequestDuration: 51
SPRequestDuration: 111
SPRequestGuid: 6da5dd9d-d015-3000-72a5-5613e8ef1a90
request-id: 6da5dd9d-d015-3000-72a5-5613e8ef1a90
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
MicrosoftSharePointTeamServices: 16.0.0.6302
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
Cache-Control: private, max-age=0
Content-Type: application/xml;charset=utf-8
Date: Mon, 13 Mar 2017 14:54:37 GMT
Expires: Sun, 26 Feb 2017 15:54:38 GMT
Last-Modified: Mon, 13 Mar 2017 14:54:38 GMT
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET

**Comment by yuribb** [comment] 2017-06-26 15:24
I found an issue https://github.com/OneDrive/onedrive-api-docs/issues/280
