### ISSUE TITLE
Support fallback for localStorage unavailable in Safari Private Browsing mode

### ISSUE THREAD

**Issue by pradeepshastry** [OneDrive/onedrive-api-docs#897] opened 2018-07-27 20:47 UTC
There seems to be a weird issue with the iOS private browsing on Safari. When we try to launch the file picker using the v7.0 Javascript SDK, we do see the list of files and are able to make a file selection. But on clicking on "Open", it just loads the spinner which runs forever. This is because of an error thrown by the  SDK. 

This issue happens in both Mac OS Safari & iPad in private browsing only. However, this works fine in all other browsers and non-private safari browser. Attached are the screenshots of the error.

This works fine in v7.2 SDK. But we are unable to use the latest version of the SDK because of this [open bug](https://github.com/OneDrive/onedrive-api-docs/issues/891) 

Is this an expected behavior or an issue with the SDK? [Here](https://pradeepshastry.github.io/onedrive/app/index.html) is a small POC where the issue can be reproduced. 
![ipadnew2](https://user-images.githubusercontent.com/11092448/43345759-8ecd960c-91a3-11e8-809a-d157b77af9af.png)

**Comment by KevinTCoughlin** [comment] 2018-08-02 21:12
Looks related to token parsing (the access token error that is). The others seem unrelated to the root issue, but are cross-domain related on your side. So I'll treat this as a duplicate of #891 unless I hear otherwise.

**Comment by pradeepshastry** [comment] 2018-08-02 23:51
I wouldn't consider this as a duplicate of #891 as this issue is related to the access_token not being stored in localStorage due to the limitation of Safari not supporting localStorage in private browsing. Due to the absence of access_token, the authentication is failing. I would suggest that the SDK should have a fallback mechanism when a browser doesn't support localStorage. However, if we can get #891 out sooner than this, I am ok to not have this addressed.

**Comment by KevinTCoughlin** [comment] 2018-08-03 19:26
That was my initial reaction, but couldn't tell from the screenshot above. We'll need to support fallback i.e. store the token in a cookie for this scenario. Will see if that's possible once the larger issue is addressed in #891.

**Comment by patrick-rodgers** [comment] 2023-02-17 20:26
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:26 UTC
Labels: type:enhancement, area:Picker, automation:Closed
