### ISSUE TITLE
[Bug] - Searching for items a user can access in one drive

### ISSUE THREAD

**Issue by NarangAshish** [OneDrive/onedrive-api-docs#1235] opened 2020-03-05 10:37 UTC
Following API is returning result only in my drive, files present in folder shared with me are not returned.

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_search?view=odsp-graph-online#searching-for-items-a-user-can-access

**Comment by chackman** [comment] 2020-03-11 17:11
Thanks for your feedback. A couple questions:
- could you clarify whether this is an issue with OneDrive Personal or OneDrive for Business?  Also could you provide a request ID?
- how long ago were the missing items shared with you?
I'll tag w/ a label that our helpful bot will fill in w/ some more information about correlation id.

**Comment by NarangAshish** [comment] 2020-03-12 17:08
request Id- 76e30e2a-fff1-42d6-bf2e-89ff668028e2
Tried directly from graph-explore

https://developer.microsoft.com/en-us/graph/graph-explorer

URL:
https://graph.microsoft.com/v1.0/me/drive/search(q='file_4March')

2 records are returned (Only from own drive)

![image](https://user-images.githubusercontent.com/24694736/76546719-02135880-64b2-11ea-9fcd-cc38d534d498.png)

Where as more files are present

![image](https://user-images.githubusercontent.com/24694736/76546858-3850d800-64b2-11ea-9c3d-200ea85a5c01.png)

**Comment by Manoj46kumaar** [comment] 2020-04-23 20:01
I'm facing the same issue. I am using the same api Ashish mentioned above. 
I guess the problem is with shared files. They're not searchable in the api. Weirdly those files are returned when using me/drive/sharedWithMe meaning i have access to them.
FYI, the account is a business account.

**Comment by chackman** [comment] 2020-04-24 17:11
Thanks for your feedback.  This is an API enhancement that is on our backlog.

**Comment by ssapa** [comment] 2020-10-14 08:48
@chackman  I am observing similar kind of issue when i use Application permissions. When i search for an item using client credentials grant type, I am getting empty results. The same is working fine with delegated permissions. Is this similar to above issue?

**Comment by chackman** [comment] 2020-10-16 19:18
Application permissions are a separate issue, please open a separate item for that.

**Comment by patrick-rodgers** [comment] 2023-02-17 20:36
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:36 UTC
Labels: type:enhancement, status:investigating, automation:Closed
