### ISSUE TITLE
OneDrive File Picker JavaScript SDK v7.2 unable to select documents using the file picker

### ISSUE THREAD

**Issue by kverhoef** [OneDrive/onedrive-api-docs#1055] opened 2019-04-26 10:10 UTC
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior
On opening the file picker on a iPad you should be able to directly select a file.

#### Observed Behavior
On opening the file picker on a iPad you are not able to select any files. You do get a button (that you don't get in other browsers) to enable file selection (see screenshot). Since where using the file picker it's weird that the user has to click a button first to pick a file. 

<img width="1139" alt="Screen Shot 2019-04-26 at 11 52 44 AM copy" src="https://user-images.githubusercontent.com/1089029/56800433-460a5a00-681b-11e9-81fe-50b6d5ea6eff.png">

#### Steps to Reproduce
To reproduce you should open the filepicker on any iPad device. I used below configuration for the filepicker.

```html
<script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js"></script>

<script type="text/javascript">
    function launchOneDrivePicker(){
        var odOptions = {
             clientId: "***",
                action: "query",
                multiSelect: false,
                advanced: {
                    filter: "",
                    scopes: ['https://graph.microsoft.com/User.Read', 'https://graph.microsoft.com/Files.ReadWrite', 'https://graph.microsoft.com/Sites.Read.All'],
                    isConsumerAccount: false,
                    endpointHint: "***"
                },
                success: (response) => {
                    console.log(response)
                },
                error: (response) => {
                    console.log(response)
                },
                cancel: () => {

        }
                }
        OneDrive.open(odOptions);
    }
</script>
<button onClick="launchOneDrivePicker()">Open from OneDrive</button>
```

**Comment by KevinTCoughlin** [comment] 2019-04-26 18:12
Thanks for reporting this @kverhoef, this looks like an issue with the host page and perhaps special mobile behavior. We'll investigate and get back to you.

cc: @ThomasMichon @margoflynn

**Comment by KevinTCoughlin** [comment] 2019-05-10 05:38
We have a fix in-flight for this @kverhoef. It was inadvertently caused by https://github.com/OfficeDev/office-ui-fabric-react/pull/8605. Thanks for the report.

I will check roll-out status and get back to you.

**Comment by patrick-rodgers** [comment] 2023-02-17 20:31
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:31 UTC
Labels: type:bug, area:Picker, automation:Closed
