### ISSUE TITLE
OneDrive for Business Search Broken?

### ISSUE THREAD

**Issue by JaredBanyard** [OneDrive/onedrive-api-docs#207] opened 2015-10-07 15:30 UTC
/_api/v2.0/me/drive/root/view.search?q=test
```json
  "error": {
    "code": "-1, Microsoft.SharePoint.Client.InvalidClientQueryException",
    "message": "The query string \"q\" is missing or invalid."
  }```

**Comment by rgregg** [comment] 2015-10-07 19:59
There's a bug in the current implementation that requires single quotes (') around the query string. Can you try something like /me/drive/root/view.search?q='test' and see if that works?

**Comment by JaredBanyard** [comment] 2015-10-07 20:04
No error, but nothing is matching.  I get the same response as:
```json
/_api/v2.0/me/drive/root/view.search
```

**Comment by ksheode** [comment] 2015-10-09 18:03
This is a bug where search queries in the personal site are returning empty. The issue is fixed now and is rolling out worldwide. Just to make sure you are running into the same issue, let me check if the fix has rolled out to your tenant. Could you share your tenant url?

**Comment by JaredBanyard** [comment] 2015-10-09 18:12
@ksheode `https://getluatechnologies-my.sharepoint.com/_api/v2.0/me`

**Comment by JaredBanyard** [comment] 2015-10-09 18:16
@ksheode I'm still not seeing any results

**Comment by danjarvis** [comment] 2015-10-26 14:40
@ksheode While the search is working for me... the results are a bit wonky.

For example, I have 5 folders at various locations in my hierarchy named 'Folder-001' through 'Folder-005'. If I search on the exact name I will get back an expected search result (1 result matching the exact folder specified). However, If I specify a partial search like 'folder' I am not getting back any results.

Also, the `@search.approximateCount` parameter is not in the response.

My tenant URL is: https://kmbsus-my.sharepoint.com/_api/v2.0/me

**Comment by rgregg** [comment] 2015-11-24 18:27
Closing out this old thread since the original bug was resolved. If search is continuing to provide incorrect results, please open a new issue.

**Closed by rgregg** 2015-11-24 18:27 UTC
