### ISSUE TITLE
Unable to see shared file in file picker

### ISSUE THREAD

**Issue by pradeepshastry** [OneDrive/onedrive-api-docs#904] opened 2018-08-15 20:45 UTC
We are unable to see the shared file in the OneDrive file picker window when. Ideally, since we have access to these files, we should be able to see them in the file picker. The same shared files are available / visible when viewed separately in onedrive portal.

**Comment by KevinTCoughlin** [comment] 2018-08-15 20:51
Duplicate of #887 so let's track that one.

**Closed by KevinTCoughlin** 2018-08-15 20:51 UTC
Labels: duplicate
