### ISSUE TITLE
WARNING: OneDrive API inconsistency - this file does not have any hash

### ISSUE THREAD

**Issue by pablobass** [OneDrive/onedrive-api-docs#1706] opened 2023-06-23 18:46 UTC
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

Since upgrade onedrive client to version 2.4.25 when I run onedrive --monitor it starts to show a lot of "Onedrive API Inconsistency".

WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142036
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142040
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142041
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142042
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142043
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142044
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142045
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142046
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142047
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142048
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142049
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142050
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142051
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142052
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142053
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142054
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142055
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142056
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142057
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142058
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142037
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142038
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142039
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142060
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142061
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142063
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142064
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142065
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142066
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142067
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142068
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142069
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142070
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142071
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142072
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142073
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142074
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142075
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142076
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142077
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142078
WARNING: OneDrive API inconsistency - this file does not have any hash: AE5743BBBE307D0B!142079

This doesn't happened before the upgrade and I can't identify wich files are referring to, even using --verbose --verbose option.

Anyone with the same problem?

I did a --resync and it still happening.

Don't know what else to do.

Thanks!

**Comment by ificator** [comment] 2023-06-23 19:41
Duplicate of https://github.com/OneDrive/onedrive-api-docs/issues/1704

**Closed** 2023-06-23 19:43 UTC
Labels: status:duplicate

**Comment by srlennon** [comment] 2024-05-03 06:08
Would this deprecation of sha1hash for one drive personal have anything to do with it? I still see some of these errors even now.
https://devblogs.microsoft.com/microsoft365dev/deprecation-of-sha1hash-on-onedrive-personal/
