### ISSUE TITLE
Multipart upload to OneDrive fails to update fileSystemInfo.lastModifiedDateTime

### ISSUE THREAD

**Issue by mvisionsinc** [OneDrive/onedrive-api-docs#754] opened 2017-12-15 17:57 UTC
I am trying to update a file and eventually I want to change the filesysteminfo lastmodifieddatetime at the same time. But when just trying to update the file, I receive {"error":{"code":"invalidRequest","message":"Bad Argument"}}.  
Please tell me what I am doing wrong.  Thanks for your help.

Request

{Method: POST, RequestUri: 'https://api.onedrive.com/v1.0/drive/special/approot/:children', Version: 2.0, Content: System.Net.Http.StringContent, Headers:
{
  Authorization: Bearer Ew...
  Content-Type: multipart/related; boundary="e5994346-7313-423b-8cfa-2272ae22dc6f"
  Content-Length: 359
}}

Request.Content

--e5994346-7313-423b-8cfa-2272ae22dc6f
Content-ID: metadata in angle brackets goes here - would not display here correctly
Content-Type: application/json

{
"name": "test.txt",
"file": {},
"@content.sourceUrl": "cid:content",
"@name.conflictBehavior": "replace"
}

--e5994346-7313-423b-8cfa-2272ae22dc6f
Content-ID: content in angle brackets goes here - would not display here correctly
Content-Type: text/plain

test data

--e5994346-7313-423b-8cfa-2272ae22dc6f--

**Comment by ificator** [comment] 2017-12-15 18:47
Hi @mvisionsinc, it looks like your request is mostly correct - the only thing that stands out is the `:` in front of children.

The way to think about the use of `:` is that it lets you switch from referencing the model to referencing a path (and vice versa). In this case `/drive/special/approot` is referencing the model, and `children` is also part of the model, and so the colon is not required. By specifying it you're actually asking for an item called `children` under the `approot` special folder, and that isn't a valid target for a POST.

Hopefully that makes sense... long story short, send your POST to the following instead:

`https://api.onedrive.com/v1.0/drive/special/approot/children`

**Comment by mvisionsinc** [comment] 2017-12-15 19:49
@ificator thanks for the fast reply.  That was it, removing the colon allowed the file to update. Now, I have changed the request to update the filesysteminfo lastmodifieddatetime using the same request with the below change but it does not return the datetime that I am sending with the request. When I download the app folder children metadata filesysteminfo lastmodifieddatetime, it sends another datetime, any ideas what I am doing wrong?

{"name": "test.txt","file" {},"@content.sourceUrl": "cid:content","@name.conflictBehavior": "replace",
"fileSystemInfo": {"lastModifiedDateTime": "2017-12-15T19:32:42Z"}}

**Comment by ificator** [comment] 2017-12-18 21:20
Hi @mvisionsinc just to confirm, you make the request with your `lastModifiedDateTime` and the value in the response matches what you provided. And then later on you make another request and get back a different `lastModifiedDateTime`?

**Comment by mvisionsinc** [comment] 2017-12-19 15:04
@ificator Yes, that is correct. I send the fileSystemInfo: lastModifiedDateTime as shown above and the response contains the fileSystemInfo: lastModifiedDateTime that I sent and later it has changed but not by me.  

To make it even crazier, I can see my app make the change by viewing my app's folder using windows explorer and I can see the correct change and then after a few seconds it changes to the current time or something close. It looks like onedrive is making the correct change but then it updates the file data sent in the same request and changes the fileSystemInfo: lastModifiedDateTime to the current time. 

Before I updated fileSystemInfo: lastModifiedDateTime and file data in the same request, I updated them with two different requests and I saw the same result. When I only updated fileSystemInfo: lastModifiedDateTime, the fileSystemInfo: lastModifiedDateTime change worked.

**Comment by ificator** [comment] 2017-12-19 16:26
That does sound strange - I'm going to update the title of this issue to reflect what we're currently discussing, and I'll see if I can get a local repro.

**Comment by mvisionsinc** [comment] 2017-12-19 17:29
@ificator Not sure if this will help but here is a little more information: 
This only stopped working recently. Not sure when or for how long. As I stated previously, in my app I was updating the file data and then the fileSystemInfo: lastModifiedDateTime in separate requests and it worked for at least several months.  I noticed it was not working when I would update the file in my app, update onedrive and then my app would update the app local file from onedrive within a short period of time and I knew that I had not updated onedrive outside my app.  So I changed to updating both in same request to try and fix this problem.  Thanks for your help.

**Comment by tipa** [comment] 2017-12-19 19:18
I have the exact same issue as @mvisionsinc. In my app I realized a syncing mechanism based on the 'lastModifiedDateTime' and it worked from April '16 until about 2 weeks ago.
In my app I am uploading a file, then in a second update call I write the lastModifiedDateTime. When I query this info right after that, the correct timestamp is returned but just a few seconds after, a more recent timestamp was written into the facet, which basically breaks my syncing mechanism.
I also closed all my other OneDrive clients (on my PC/phone) to go sure no other app updates that field. Also, I am working in a private app folder so there should be just me having access to that file.

**Comment by ificator** [comment] 2017-12-19 21:48
Hi @mvisionsinc and @tipa 

I haven't been able to reproduce this, so I wanted to show what I've tried in hopes that you can show me where I'm deviating from your steps.

First I created a file (I used `PUT .../children/test.txt/content`):

```
{
  "createdDateTime": "2017-12-19T21:42:57.57Z",
  "lastModifiedDateTime": "2017-12-19T21:42:57.57Z",
  "fileSystemInfo": {
    "createdDateTime": "2017-12-19T21:42:57.57Z",
    "lastModifiedDateTime": "2017-12-19T21:42:57.57Z"
  }
}
```

Then I immediately updated the item (`PATCH .../children/test.txt`):

```
{
  "createdDateTime": "2017-12-19T21:42:57.57Z",
  "lastModifiedDateTime": "2017-12-19T21:42:57.867Z",
  "fileSystemInfo": {
    "createdDateTime": "2017-12-19T21:42:57.57Z",
    "lastModifiedDateTime": "2017-12-13T00:00:00Z"
  }
}
```

Then I waited some time and retrieved the current metadata (`GET .../children/test.txt`):

```
{
  "createdDateTime": "2017-12-19T21:42:57.57Z",
  "lastModifiedDateTime": "2017-12-19T21:43:01.523Z",
  "fileSystemInfo": {
    "createdDateTime": "2017-12-19T21:42:57.57Z",
    "lastModifiedDateTime": "2017-12-13T00:00:00Z"
  }
}
```

In each case there's a change in `lastModifiedDateTime`, but no change in `fileSystemInfo.lastModifiedDateTime` which is what I would expect.

**Comment by tipa** [comment] 2017-12-19 22:16
Thanks for your fast reponse!
I am using this lib, maybe that matters: https://github.com/OneDrive/onedrive-sdk-csharp

This is what I do, maybe it helps to reproduce it:
```
await oneDriveClient.Drive.Special.AppRoot.ItemWithPath("test.file").Content.Request().PutAsync<Item>(contentStream);
await oneDriveClient.Drive.Special.AppRoot.ItemWithPath("test.file").Request().UpdateAsync(new Item { FileSystemInfo = new Microsoft.OneDrive.Sdk.FileSystemInfo() { LastModifiedDateTime = uploadDate } });
```
Immediately after:
```
remoteFile = await oneDriveClient.Drive.Special.AppRoot.ItemWithPath("test.file").Request().Select("fileSystemInfo").GetAsync();
remoteFile.FileSystemInfo.LastModifiedDateTime == uploadDate // correct!_
```
Another minute or so later:
```
remoteFile = await oneDriveClient.Drive.Special.AppRoot.ItemWithPath("test.file").Request().Select("fileSystemInfo").GetAsync();
remoteFile.FileSystemInfo.LastModifiedDateTime == uploadDate + some seconds // incorrect!
```

Let me know if there is anything else I can do to help

**Comment by mvisionsinc** [comment] 2017-12-20 14:44
@ificator Are you updating file data when you change the lastmodifieddatetime? 
I am using http below to retrieve the files metadata:
````
Method: GET, RequestUri: 'https://api.onedrive.com/v1.0/drive/special/approot/children?select=name,fileSystemInfo', Version: 2.0, Content: <null>, Headers:
{
}
````
And this to update the file data and metadata:
````
{Method: POST, RequestUri: 'https://api.onedrive.com/v1.0/drive/special/approot/children', Version: 2.0, Content: System.Net.Http.StringContent, Headers:
{
  Authorization: Bearer Ew...
  Content-Type: multipart/related; boundary="e5994346-7313-423b-8cfa-2272ae22dc6f"
  Content-Length: 359
}}

--e5994346-7313-423b-8cfa-2272ae22dc6f
Content-ID: <metadata>
Content-Type: application/json

{"name": "test.txt","file": {},"@content.sourceUrl": "cid:content","@name.conflictBehavior": "replace","fileSystemInfo": {"lastModifiedDateTime": "2017-12-18T19:32:42Z"}}

--e5994346-7313-423b-8cfa-2272ae22dc6f
Content-ID: <content>
Content-Type: application/json

file data

--e5994346-7313-423b-8cfa-2272ae22dc6f--
````

**Comment by ificator** [comment] 2017-12-20 16:57
Thanks @tipa, here's what I get when I use that code:

```
Creating file...
Updating timestamps...
Getting current metadata...
2017-12-20T16:51:35.2340000+00:00
Waiting 60s...
Getting current metadata...
2017-12-20T16:51:35.2340000+00:00
```

So at this point it seems likely that there's something else active on the account that's triggering the timestamp bump. One thing that might help narrow it down is to also select `lastModifiedBy` in your repro and see the value for the `application` identity changes.

**Comment by mvisionsinc** [comment] 2017-12-20 18:07
@ificator If I update the file metadata fileSystemInfo: lastModifiedDateTime only and not the file data, I do not have this problem, it works perfectly.  

Only when I update the metadata and the file data either in the same request or the file data in one request and the metadata in the next request (immediately following) do I get the fileSystemInfo: lastModifiedDateTime changed to something other than the fileSystemInfo: lastModifiedDateTime that I sent with the metadata request.

**Comment by ificator** [comment] 2017-12-20 21:07
Good news, I managed to get a repro on a different account! I'm drilling in now, but at first glance it what I see seems to confirm it's a bug.

**Comment by ificator** [comment] 2017-12-20 21:55
Found the issue and we'll fix it with our next release. Unfortunately due to the time of year that won't be before January :(

**Comment by mvisionsinc** [comment] 2017-12-20 22:31
@ificator Thanks for finding this problem. I really appreciate your help. Do you know the January date for the next release ?

**Comment by ificator** [comment] 2018-01-04 17:44
The fix for this has been deployed - please let us know if you still see the unexpected behavior.

**Closed** 2018-01-11 22:24 UTC
Labels: resolved
