### ISSUE TITLE
File Handler does not show actions available for all files

### ISSUE THREAD

**Issue by enerdgumen** [OneDrive/onedrive-api-docs#1124] opened 2019-08-26 08:25 UTC
#### Category
- [ ] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

I've registered the following file handler:
```
{
    "type": "FileHandler",
    "properties": [
      {
        "key": "version",
        "value": "2"
      },
      {
        "key": "actions",
        "value": "[{\"type\":\"custom\",\"url\":\"https://localhost:3000/api/compress\",\"displayName\":\"Compress\",\"availableOn\":{\"file\":{\"extensions\":[\"*\"]},\"folder\":{},\"allowMultiSelect\":true}},{\"type\":\"custom\",\"url\":\"https://localhost:3000/api/compress/parent\",\"displayName\":\"Compress current folder\",\"availableOn\":{\"file\":{\"extensions\":[\"*\"]},\"folder\":{}}},{\"type\":\"custom\",\"url\":\"https://localhost:3000/api/open/local\",\"displayName\":\"Open locally\",\"availableOn\":{\"file\":{\"extensions\":[\".linkdocument\",\".linkworksheet\",\".linkpresentation\",\".linkpdf\",\".linktext\",\".linkimage\",\".linkvideo\",\".linkaudio\",\".linkcad\",\".linkmsnote\",\".linkpsd\",\".linkvisio\",\".linkproject\",\".linkmail\",\".linkepub\",\".linkxml\",\".linkxps\",\".link\",\".zipdocument\",\".zipworksheet\",\".zippresentation\",\".zippdf\",\".ziptext\",\".zipimage\",\".zipvideo\",\".zipaudio\",\".zipcad\",\".zipmsnote\",\".zippsd\",\".zipvisio\",\".zipproject\",\".zipmail\",\".zipepub\",\".zipxml\",\".zipxps\",\".zip\"]}}},{\"type\":\"custom\",\"url\":\"https://localhost:3000/api/share\",\"displayName\":\"Share\",\"availableOn\":{\"file\":{\"extensions\":[\".linkdocument\",\".linkworksheet\",\".linkpresentation\",\".linkpdf\",\".linktext\",\".linkimage\",\".linkvideo\",\".linkaudio\",\".linkcad\",\".linkmsnote\",\".linkpsd\",\".linkvisio\",\".linkproject\",\".linkmail\",\".linkepub\",\".linkxml\",\".linkxps\",\".link\"]}}},{\"type\":\"custom\",\"url\":\"https://localhost:3000/api/unshare\",\"displayName\":\"Unshare\",\"availableOn\":{\"file\":{\"extensions\":[\".linkdocument\",\".linkworksheet\",\".linkpresentation\",\".linkpdf\",\".linktext\",\".linkimage\",\".linkvideo\",\".linkaudio\",\".linkcad\",\".linkmsnote\",\".linkpsd\",\".linkvisio\",\".linkproject\",\".linkmail\",\".linkepub\",\".linkxml\",\".linkxps\",\".link\"]}}},{\"type\":\"custom\",\"url\":\"https://localhost:3000/api/attributes\",\"displayName\":\"Attributes\",\"availableOn\":{\"file\":{\"extensions\":[\".linkdocument\",\".linkworksheet\",\".linkpresentation\",\".linkpdf\",\".linktext\",\".linkimage\",\".linkvideo\",\".linkaudio\",\".linkcad\",\".linkmsnote\",\".linkpsd\",\".linkvisio\",\".linkproject\",\".linkmail\",\".linkepub\",\".linkxml\",\".linkxps\",\".link\",\".zipdocument\",\".zipworksheet\",\".zippresentation\",\".zippdf\",\".ziptext\",\".zipimage\",\".zipvideo\",\".zipaudio\",\".zipcad\",\".zipmsnote\",\".zippsd\",\".zipvisio\",\".zipproject\",\".zipmail\",\".zipepub\",\".zipxml\",\".zipxps\",\".zip\"]}}},{\"type\":\"custom\",\"url\":\"https://localhost:3000/api/uncompress\",\"displayName\":\"Uncompress\",\"availableOn\":{\"file\":{\"extensions\":[\".linkdocument\",\".linkworksheet\",\".linkpresentation\",\".linkpdf\",\".linktext\",\".linkimage\",\".linkvideo\",\".linkaudio\",\".linkcad\",\".linkmsnote\",\".linkpsd\",\".linkvisio\",\".linkproject\",\".linkmail\",\".linkepub\",\".linkxml\",\".linkxps\",\".link\",\".zipdocument\",\".zipworksheet\",\".zippresentation\",\".zippdf\",\".ziptext\",\".zipimage\",\".zipvideo\",\".zipaudio\",\".zipcad\",\".zipmsnote\",\".zippsd\",\".zipvisio\",\".zipproject\",\".zipmail\",\".zipepub\",\".zipxml\",\".zipxps\",\".zip\"]},\"folder\":{},\"allowMultiSelect\":true}},{\"type\":\"custom\",\"url\":\"https://localhost:3000/api/uncompress/parent\",\"displayName\":\"Uncompress current folder\",\"availableOn\":{\"file\":{\"extensions\":[\".linkdocument\",\".linkworksheet\",\".linkpresentation\",\".linkpdf\",\".linktext\",\".linkimage\",\".linkvideo\",\".linkaudio\",\".linkcad\",\".linkmsnote\",\".linkpsd\",\".linkvisio\",\".linkproject\",\".linkmail\",\".linkepub\",\".linkxml\",\".linkxps\",\".link\",\".zipdocument\",\".zipworksheet\",\".zippresentation\",\".zippdf\",\".ziptext\",\".zipimage\",\".zipvideo\",\".zipaudio\",\".zipcad\",\".zipmsnote\",\".zippsd\",\".zipvisio\",\".zipproject\",\".zipmail\",\".zipepub\",\".zipxml\",\".zipxps\",\".zip\"]}}}]"
      },
      {
        "key": "strings it-IT",
        "value": "{\"Compress\":\"Comprimi\",\"Compress current folder\":\"Comprimi cartella corrente\",\"Attributes\":\"Attributi\",\"Open locally\":\"Apri localmente\",\"Share\":\"Condividi\",\"Unshare\":\"Rimuovi condivisione\",\"Uncompress\":\"Decomprimi\",\"Uncompress current folder\":\"Decomprimi cartella corrente\"}"
      }
    ]
  },
```

It includes actions available on any type of files (i.e. "Compress") and actions available on specific extensions (i.e. "Share"). So I expect me the "Compress" action available on any extension, including files without extension.

#### Observed Behavior

The actions defined with the `availableOn\":{\"file\":{\"extensions\":[\"*\"]}, ...` are not shown in the contextual menu of the user interface, the other ones are shown on the expected files.

I also tried to define the actions with `availableOn\":{\"file\":{\"extensions\":{}}, ...` without any effect  (assuming the refresh worked).

#### Steps to Reproduce

1. Register the above file handler to a specific app registration.
2. Enable the app on a OneDrive for Business account.
3. Go to OneDrive on cloud: select a file with a unknown extension (or without extension) and open the contextual menu.

Thank you.

**Comment by maurocchi** [comment] 2019-09-23 07:36
Have you any feedback about this issue?

My application id is `94097542-d2db-4568-a7b9-ac7f4fab4f1b`.

**Comment by maurocchi** [comment] 2019-09-23 09:18
To help you in the troubleshooting, I reproduced this problem with your official [markdown file handler sample](https://github.com/OneDrive/o365-markdown-file-handler-v2).

As you can see, the file handler is enabled since the file `https.md` has the expected custom icon, but the menu has no custom menu with the action "Add to ZIP file - debug" on the file `cert.pem`:

![image](https://user-images.githubusercontent.com/240925/65413229-49693800-ddf1-11e9-9459-3e0592c4ebde.png)

[This](https://github.com/OneDrive/onedrive-api-docs/files/3641422/apps.txt) is the result for `GET /_api/v2.0/drive/apps?select=*,promoted&expand=actions`.

**Comment by chackman** [comment] 2019-09-24 20:53
The markdown file handler is not associated with pem files - did you create a new file handler that is associated with pem files?

**Comment by maurocchi** [comment] 2019-09-25 07:07
Yes, but as stated on the README

> This sample also illustrates a custom action, with the Add to ZIP action added to all files.

the following custom action contained in the `addin-schema-debug.json` should be visible for any type of file:
```
 {
      "type": "FileHandler",
      "properties": [
        {
          "key": "actions",
          "value": "[{\"type\":\"custom\",\"displayName\":\"Add to ZIP file - debug\",\"url\":\"https://localhost:44362/filehandler/compressFiles\",\"availableOn\":{\"file\":{},\"folder\":{},\"allowMultiSelect\":true}}]"
        },
        {
          "key": "version",
          "value": "2"
        }
      ]
    },
```

**Comment by chackman** [comment] 2019-09-26 20:05
Could you please provide the output of this query (`{tenant}` is your ODB tenant name):
   `https://{tenant}-my.sharepoint.com/_api/v2.0/drive/apps?select=*,promoted&expand=actions`
And also are you seeing the same behavior as issue #1136 ?

This will help us with investigating and potentially getting information to a partner team looking at the other issue.

**Comment by maurocchi** [comment] 2019-09-27 07:30
@chackman I've already attached the output in my previous comment:
> This is the result for `GET /_api/v2.0/drive/apps?select=*,promoted&expand=actions`.

About the #1136, yes they are correlated. If I open the pem file in preview, I can see the action:
![image](https://user-images.githubusercontent.com/240925/65750687-45972780-e109-11e9-890f-b7f71b8c434a.png)

**Comment by chackman** [comment] 2019-09-30 16:51
OK thanks we are already following up with a partner team on issue 1136.

**Comment by patrick-rodgers** [comment] 2023-02-17 20:32
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:32 UTC
Labels: Needs: Attention :wave:, area:File Handlers, automation:Closed
