### ISSUE TITLE
Any plans to support adding view permission?

### ISSUE THREAD

**Issue by ryazonjr** [OneDrive/onedrive-api-docs#1154] opened 2019-09-27 20:06 UTC
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

#### Expected or Desired Behavior

Currently the roles are read and write. I'm wondering if there's any plan to support view role which could map to sharepoint view permission.
 
Also what's the resolution on #471?

**Comment by chackman** [comment] 2019-09-30 16:47
Thanks for your feedback.
Since you are sharing a new feature request (enhancement / suggestion) about SharePoint, could you please add this via the SharePoint Developer Platform UserVoice at http://aka.ms/sp-dev-uservoice?

**Comment by chackman** [comment] 2019-09-30 16:49
Regarding 471 this is an old issue that should be closed out.  If the issue still reproduces please create a new issue.

**Comment by ryazonjr** [comment] 2019-09-30 20:36
I'm not asking for a sharepoint feature, it already has a view permission; issue 471 talks about querying the "SP.View Only" role for example which btw doesn't show up in my tests, I can make a new issue.

What I'm asking for is a onedrive feature to support adding/deleting the "SP.View Only" role on an item.

**Comment by patrick-rodgers** [comment] 2023-02-17 20:34
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:34 UTC
Labels: type:enhancement, automation:Closed
