### ISSUE TITLE
[ODB] view.delta 'top' param not working

### ISSUE THREAD

**Issue by pedroandreletra** [OneDrive/onedrive-api-docs#402] opened 2016-07-06 16:21 UTC
Hi,

Requesting the delta for an OneDrive for Business account that has about 2000 changes, the view.delta always returns only 7 changes at a time (always 7), for any top value that I pass (I tried passing 20, 100, etc...).

This is a big problem because causes the processing of the 2000 changes to require almost 300 request to view.delta, what takes way to long.

Can somebody help me?

Thanks in advance,

Pedro Letra

**Comment by rgregg** [comment] 2016-07-06 16:34
Hi Pedro, I wasn't able to reproduce this behavior. Can you include provide the full request you are making (URL) and the request-id and date header values in the response that is incorrect?

**Comment by pedroletra-topdocs** [comment] 2016-07-06 16:43
Request:
host: 'luisteste-my.sharepoint.com'
method: 'GET',
path: '/_api/v2.0/me/drive/root/view.delta?token=1;%234;%231;3;1d41007a-c4f9-4f2a-b452-e861f9e06e4d;636034136816970000;38218558;%23Paged_CT=1;3;1d41007a-c4f9-4f2a-b452-e861f9e06e4d;636034131846630000;38217186&top=100' 

Response:
{ '@odata.context': 'https://luisteste-my.sharepoint.com/_api/v2.0/$metadata#items',
  '@odata.deltaLink': 'https://luisteste-my.sharepoint.com/personal/pedrocoiso_luisteste_onmicrosoft_com/_api/v2.0/drive/root/view.delta(token=\'1;%234;%231;3;1d41007a-c4f9-4f2a-b452-e861f9e06e4d;636034136816970000;38218558;%23Paged_CT=1;3;1d41007a-c4f9-4f2a-b452-e861f9e06e4d;636034131849830000;38217192\')',
  '@delta.token': '1;%234;%231;3;1d41007a-c4f9-4f2a-b452-e861f9e06e4d;636034136816970000;38218558;%23Paged_CT=1;3;1d41007a-c4f9-4f2a-b452-e861f9e06e4d;636034131849830000;38217192',
  value: 
   [ { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZ56Y2GOVW7725BZO354PWSELRRZ',
       '@odata.editLink': 'drive/items/01QQQNVZ56Y2GOVW7725BZO354PWSELRRZ',
       createdDateTime: '2016-05-15T18:46:51Z',
       folder: [Object],
       id: '01QQQNVZ56Y2GOVW7725BZO354PWSELRRZ',
       lastModifiedDateTime: '2016-07-06T14:53:43Z',
       name: 'root',
       root: {},
       size: 0,
       specialFolder: [Object],
       webUrl: 'https://luisteste-my.sharepoint.com/personal/pedrocoiso_luisteste_onmicrosoft_com/Documents' },
     { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZYVKS5G5R3ZVNFZBEP3JKNJB7QG',
       '@odata.editLink': 'drive/items/01QQQNVZYVKS5G5R3ZVNFZBEP3JKNJB7QG',
       createdDateTime: '0001-01-01T00:00:00-08:00',
       deleted: [Object],
       file: {},
       id: '01QQQNVZYVKS5G5R3ZVNFZBEP3JKNJB7QG',
       lastModifiedDateTime: '0001-01-01T00:00:00-08:00',
       parentReference: [Object],
       size: 0 },
     { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZ57IAR3DEQOIFAYGTFV7UW3DYYG',
       '@odata.editLink': 'drive/items/01QQQNVZ57IAR3DEQOIFAYGTFV7UW3DYYG',
       createdDateTime: '0001-01-01T00:00:00-08:00',
       deleted: [Object],
       file: {},
       id: '01QQQNVZ57IAR3DEQOIFAYGTFV7UW3DYYG',
       lastModifiedDateTime: '0001-01-01T00:00:00-08:00',
       parentReference: [Object],
       size: 0 },
     { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZ6EU4AX5SVBHFDJKZ47RVCDFQIH',
       '@odata.editLink': 'drive/items/01QQQNVZ6EU4AX5SVBHFDJKZ47RVCDFQIH',
       createdDateTime: '0001-01-01T00:00:00-08:00',
       deleted: [Object],
       file: {},
       id: '01QQQNVZ6EU4AX5SVBHFDJKZ47RVCDFQIH',
       lastModifiedDateTime: '0001-01-01T00:00:00-08:00',
       parentReference: [Object],
       size: 0 },
     { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZ3KT737S4HL35C2E4NTA63JFBLH',
       '@odata.editLink': 'drive/items/01QQQNVZ3KT737S4HL35C2E4NTA63JFBLH',
       createdDateTime: '0001-01-01T00:00:00-08:00',
       deleted: [Object],
       file: {},
       id: '01QQQNVZ3KT737S4HL35C2E4NTA63JFBLH',
       lastModifiedDateTime: '0001-01-01T00:00:00-08:00',
       parentReference: [Object],
       size: 0 },
     { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZ7CNRHA7NKMMZGIFWZENBTV7CYT',
       '@odata.editLink': 'drive/items/01QQQNVZ7CNRHA7NKMMZGIFWZENBTV7CYT',
       createdDateTime: '0001-01-01T00:00:00-08:00',
       deleted: [Object],
       file: {},
       id: '01QQQNVZ7CNRHA7NKMMZGIFWZENBTV7CYT',
       lastModifiedDateTime: '0001-01-01T00:00:00-08:00',
       parentReference: [Object],
       size: 0 },
     { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZ5LUQ5JKR7WCBCZ273KDJM4E7JZ',
       '@odata.editLink': 'drive/items/01QQQNVZ5LUQ5JKR7WCBCZ273KDJM4E7JZ',
       createdDateTime: '0001-01-01T00:00:00-08:00',
       deleted: [Object],
       file: {},
       id: '01QQQNVZ5LUQ5JKR7WCBCZ273KDJM4E7JZ',
       lastModifiedDateTime: '0001-01-01T00:00:00-08:00',
       parentReference: [Object],
       size: 0 } ] }

There you go

**Comment by pedroletra-topdocs** [comment] 2016-07-06 17:34
{ 'cache-control': 'private, max-age=0',
     'transfer-encoding': 'chunked',
     'content-type': 'application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8',
     expires: 'Tue, 21 Jun 2016 17:32:12 GMT',
     'last-modified': 'Wed, 06 Jul 2016 17:32:12 GMT',
     server: 'Microsoft-IIS/8.5',
     'x-sharepointhealthscore': '0',
     'x-sp-serverstate': 'ReadOnly=0',
     'odata-version': '4.0',
     spclientservicerequestduration: '101',
     'x-aspnet-version': '4.0.30319',
     sprequestguid: '13378d9d-c0bf-3000-9481-4532407da0e1',
     'request-id': '13378d9d-c0bf-3000-9481-4532407da0e1',
     'strict-transport-security': 'max-age=31536000',
     'x-frame-options': 'SAMEORIGIN',
     'x-powered-by': 'ASP.NET',
     microsoftsharepointteamservices: '16.0.0.5423',
     'x-content-type-options': 'nosniff',
     'x-ms-invokeapp': '1; RequireReadOnly',
     p3p: 'CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"',
     date: 'Wed, 06 Jul 2016 17:32:12 GMT',
     connection: 'close' }

I forgot the response headers ;)

**Comment by rgregg** [comment] 2016-07-06 17:52
Do you get only 7 items when you make the initial request (view.token without any query string parameters)?

**Comment by pedroletra-topdocs** [comment] 2016-07-07 09:42
I got 8 items (excluding the first one, the 'root' reference

`{ '@odata.context': 'https://luisteste-my.sharepoint.com/_api/v2.0/$metadata#items',
  '@odata.deltaLink': 'https://luisteste-my.sharepoint.com/personal/pedrocoiso_luisteste_onmicrosoft_com/_api/v2.0/drive/root/view.delta(token=\'1;%234;%231;3;1d41007a-c4f9-4f2a-b452-e861f9e06e4d;636034811450570000;38319923;%23\')',
  '@delta.token': '1;%234;%231;3;1d41007a-c4f9-4f2a-b452-e861f9e06e4d;636034811450570000;38319923;%23',
  value: 
   [ { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZ56Y2GOVW7725BZO354PWSELRRZ',
       '@odata.editLink': 'drive/items/01QQQNVZ56Y2GOVW7725BZO354PWSELRRZ',
       createdDateTime: '2016-05-15T18:46:51Z',
       folder: [Object],
       id: '01QQQNVZ56Y2GOVW7725BZO354PWSELRRZ',
       lastModifiedDateTime: '2016-07-06T18:11:42Z',
       name: 'root',
       root: {},
       size: 0,
       specialFolder: [Object],
       webUrl: 'https://luisteste-my.sharepoint.com/personal/pedrocoiso_luisteste_onmicrosoft_com/Documents' },
     { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZ2U3QV3ZWROVFDJBICJ3JT2JR5F',
       '@odata.editLink': 'drive/items/01QQQNVZ2U3QV3ZWROVFDJBICJ3JT2JR5F',
       createdDateTime: '2016-06-16T15:57:40Z',
       eTag: '"{BC2BDC54-2EDA-46A9-90A0-49DA67A4C7A5},2"',
       folder: [Object],
       id: '01QQQNVZ2U3QV3ZWROVFDJBICJ3JT2JR5F',
       lastModifiedDateTime: '2016-06-16T16:24:06Z',
       name: 'pasta',
       parentReference: [Object],
       size: 71238,
       webUrl: 'https://luisteste-my.sharepoint.com/personal/pedrocoiso_luisteste_onmicrosoft_com/Documents/pasta3/pasta' },
     { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZYUUK3HAUJQVBHKVYSUYZRVIOYR',
       '@odata.editLink': 'drive/items/01QQQNVZYUUK3HAUJQVBHKVYSUYZRVIOYR',
       createdDateTime: '2016-06-15T14:40:14Z',
       eTag: '"{70B6A214-3051-4EA8-AAE2-54C663543B11},2"',
       file: {},
       id: '01QQQNVZYUUK3HAUJQVBHKVYSUYZRVIOYR',
       lastModifiedDateTime: '2016-06-16T15:58:58Z',
       name: 'Imagem.png',
       parentReference: [Object],
       size: 71238,
       webUrl: 'https://luisteste-my.sharepoint.com/personal/pedrocoiso_luisteste_onmicrosoft_com/Documents/pasta3/pasta/Imagem.png' },
     { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZZKXABMPXL2H5F3KEANNEIZPYU6',
       '@odata.editLink': 'drive/items/01QQQNVZZKXABMPXL2H5F3KEANNEIZPYU6',
       createdDateTime: '2016-06-16T16:14:54Z',
       eTag: '"{C702B82A-7ADD-4B3F-B510-0D691197E29E},9"',
       file: {},
       id: '01QQQNVZZKXABMPXL2H5F3KEANNEIZPYU6',
       lastModifiedDateTime: '2016-07-01T14:01:46Z',
       name: 'excelteste.xlsx',
       parentReference: [Object],
       size: 19125,
       webUrl: 'https://luisteste-my.sharepoint.com/personal/pedrocoiso_luisteste_onmicrosoft_com/Documents/excelteste.xlsx' },
     { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZ7I2SP3VRVKHRBLFTW3XUYOB3F5',
       '@odata.editLink': 'drive/items/01QQQNVZ7I2SP3VRVKHRBLFTW3XUYOB3F5',
       createdDateTime: '2016-06-16T16:23:54Z',
       eTag: '"{BA9FD4E8-AAC6-423C-B2CE-DBBD30E0ECBD},1"',
       folder: [Object],
       id: '01QQQNVZ7I2SP3VRVKHRBLFTW3XUYOB3F5',
       lastModifiedDateTime: '2016-06-16T16:23:54Z',
       name: 'pasta3',
       parentReference: [Object],
       size: 150544,
       webUrl: 'https://luisteste-my.sharepoint.com/personal/pedrocoiso_luisteste_onmicrosoft_com/Documents/pasta3' },
     { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZ2ISRMOIATCWFCJNNPTLQLEAH7U',
       '@odata.editLink': 'drive/items/01QQQNVZ2ISRMOIATCWFCJNNPTLQLEAH7U',
       createdDateTime: '2016-07-01T14:01:17Z',
       eTag: '"{E4589448-6202-44B1-96B5-F35C16401FF4},3"',
       file: {},
       id: '01QQQNVZ2ISRMOIATCWFCJNNPTLQLEAH7U',
       lastModifiedDateTime: '2016-07-04T11:26:51Z',
       name: 'topdox_bot_iconn.png',
       parentReference: [Object],
       size: 52134,
       webUrl: 'https://luisteste-my.sharepoint.com/personal/pedrocoiso_luisteste_onmicrosoft_com/Documents/topdox_bot_iconn.png' },
     { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZ54MY4VKK3CHNC3HCOVT3UNPWSR',
       '@odata.editLink': 'drive/items/01QQQNVZ54MY4VKK3CHNC3HCOVT3UNPWSR',
       createdDateTime: '2016-07-01T16:14:32Z',
       eTag: '"{553966BC-622B-453B-B389-D59EE8D7DA51},2"',
       folder: [Object],
       id: '01QQQNVZ54MY4VKK3CHNC3HCOVT3UNPWSR',
       lastModifiedDateTime: '2016-07-01T16:14:32Z',
       name: 'pasta coisas dentro',
       parentReference: [Object],
       size: 79306,
       webUrl: 'https://luisteste-my.sharepoint.com/personal/pedrocoiso_luisteste_onmicrosoft_com/Documents/pasta3/pasta%20coisas%20dentro' },
     { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZZIXPLSC3J6ZZAIVDMFGXAROZMH',
       '@odata.editLink': 'drive/items/01QQQNVZZIXPLSC3J6ZZAIVDMFGXAROZMH',
       createdDateTime: '2016-07-01T16:14:50Z',
       eTag: '"{21D7BB28-3E6D-40CE-8A8D-8535C1176587},1"',
       file: [Object],
       id: '01QQQNVZZIXPLSC3J6ZZAIVDMFGXAROZMH',
       lastModifiedDateTime: '2016-07-01T16:14:50Z',
       name: 'tips.docx',
       parentReference: [Object],
       size: 79306,
       webUrl: 'https://luisteste-my.sharepoint.com/personal/pedrocoiso_luisteste_onmicrosoft_com/Documents/pasta3/pasta%20coisas%20dentro/tips.docx' },
     { '@odata.type': '#oneDrive.item',
       '@odata.id': 'https://luisteste-my.sharepoint.com/_api/v2.0/drive/items/01QQQNVZ7BEMBO2N5NGFEZPSSSBCPRPPUI',
       '@odata.editLink': 'drive/items/01QQQNVZ7BEMBO2N5NGFEZPSSSBCPRPPUI',
       createdDateTime: '2016-07-06T18:11:30Z',
       eTag: '"{ED0223E1-AD37-4931-97CA-52089F17BE88},3"',
       file: [Object],
       id: '01QQQNVZ7BEMBO2N5NGFEZPSSSBCPRPPUI',
       lastModifiedDateTime: '2016-07-06T18:11:41Z',
       name: 'Pedro_Letra_Curriculum.pdf',
       parentReference: [Object],
       size: 811931,
       webUrl: 'https://luisteste-my.sharepoint.com/personal/pedrocoiso_luisteste_onmicrosoft_com/Documents/Pedro_Letra_Curriculum.pdf' } ] }`

**Comment by rgregg** [comment] 2016-07-07 17:59
Thanks @pedroletra-topdocs. And as you said, there are hundreds/thousands of items in this OneDrive, not actually just 8?

The API response you posted indicates that the response is "done" because there isn't an @odata.nextLink value (which would indicate that there are more items to return). By returning an @odata.deltaLink, that indicates that we think we've giving you all the items in the drive and we've giving you a URL you can use to get changes at some point in the future. I would expect giving that response that there are only 8 items in the drive and that you wouldn't ever see more by continuing to poll the deltaLink. However, it sounds like that isn't the case and there is a bug here, can you confirm?

**Comment by pedroletra-topdocs** [comment] 2016-07-08 10:13
No @rgregg. I had thousands but i deleted them to test. The 2000+ changes where deletes. 

The "clean" view.delta request works (I add some files to my test drive and now returns 64 items).

But my problem is that we handle big drives, so we can't request for the complete list of changes. It's imperative in terms of performance that we use the cursor token, and in that case, it is only returning 7 changes at a time, independent of the value of the "top" parameter (is 7 even if I do not pass the top parameter).

Another thing, @odata.nextLink never came, for example, even when there were more than 2000 changes left, the API returned the 7 changes that I showed you in my second post, without any "nextLink". But when I request the delta again with the new token (as told by the documentation to request until the changes array is empty), 7 more came (and then the process repeats and repeats). As you now, 2000 changes 7 at a time takes a really long time.

I hope I could clear my problem. Thank you in advance for your help

**Comment by pedroletra-topdocs** [comment] 2016-07-12 14:57
Hi @rgregg,

Any news about this problem?

Thanks

**Comment by ificator** [comment] 2016-07-12 16:35
I managed to get a repro of this so will be able to drill in and hopefully figure out what's going on.

My steps were:
1. Create a lot of items
2. Get a current sync token
3. Delete 200 of them
4. Call delta using the token from # 2

At that point I only got back 7 items (the root and 6 deleted ones).

**Comment by ificator** [comment] 2016-07-12 21:21
The issue with us calling the link resulting from this scenario the `deltaLink` instead of the `nextLink` is easy enough to resolve, however the reason for only returning 6 tombstones is somewhat convoluted. I've checked in a fix for the former, but the latter will take more time to figure out the best course of action.

**Comment by pedroletra-topdocs** [comment] 2016-07-14 14:25
Thank for your response!

When you have any news please let me know.

Best regards

**Comment by ificator** [comment] 2016-07-26 21:10
Just to update here, the fix to correctly return a `nextLink` instead of a `deltaLink` for this scenario is currently rolling out and should complete towards the end of the week. Unfortunately the underlying reason for the weird tombstone behavior is not something we can fix at this point in time, so you're going to have to put up with the larger number of round trips for the time being :(.

**Comment by ificator** [comment] 2017-02-11 03:02
The fix for the `nextLink` has been deployed for quite a while now :)

**Closed by ificator** 2017-02-11 03:02 UTC
Labels: bug
