### ISSUE TITLE
Picking not working at all GET https://js.live.net/v7.2/OneDrive.js net::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by jcharnley** [OneDrive/onedrive-api-docs#1538] opened 2021-09-29 09:52 UTC
please see title!

**Comment by dominik-weber** [comment] 2021-09-29 12:30
This seems to be a duplicate of #1537

**Comment by chackman** [comment] 2021-09-30 16:09
Yes this was a dupe of #1537.

**Closed by chackman** 2021-09-30 16:09 UTC
Labels: Needs: Triage :mag:
