### ISSUE TITLE
File Handler does not show custom actions on folders

### ISSUE THREAD

**Issue by enerdgumen** [OneDrive/onedrive-api-docs#1036] opened 2019-04-02 08:22 UTC
#### Category
- [x] Question
- [ ] Documentation issue
- [x] Bug

#### Expected or Desired Behavior

I've configured the file handler manifest as described in the [reference](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/define-actions?view=odsp-graph-online#properties) by setting a custom action with the `folder` attribute set to `{}`, in order to enable the action on folders.

Precisely, the action packaged in my manifest is similar to the following one:
```
{
  "type": "custom",
  "url": "https://localhost:3000/api/something",
  "displayName": "Do something",
  "shortDisplayName": "Do",
  "icon": {
    "png1x": "https://localhost:3000/icon.png"
  },
  "availableOn": {
    "file": { "extensions": ["*"] },
    "folder": {},
    "allowMultiSelect": true,
    "web": {}
  }
}
```

#### Observed Behavior

The action is shown by OneDrive only on files, not on folders.

#### Steps to Reproduce

1. [Register](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/register-manually?view=odsp-graph-online) a file handler with a custom action supporting folders to a specific app registration.
2. Enable the app on a OneDrive for Business account.
3. Go to OneDrive on cloud: selecting files the action is available, selecting folders it is not.

Thanks.

**Comment by maurocchi** [comment] 2019-04-15 15:39
Hi, any news about it?

**Comment by JeremyKelley** [comment] 2019-05-01 20:55
Hi, we've started taking a look into this issue but don't have any status to report yet.  We'll come back with more info as soon as we are able to repro the issue in-house.

Thanks for the bug report!

**Comment by maurocchi** [comment] 2019-05-16 08:08
Hi @JeremyKelley, have you some updates for this issue?

**Comment by mdorlando** [comment] 2019-06-24 09:51
Hi @JeremyKelley, any news?

**Comment by maurocchi** [comment] 2019-09-23 09:22
To help you in the troubleshooting, I reproduced this problem with your official [markdown file handler sample](https://github.com/OneDrive/o365-markdown-file-handler-v2).

As you can see, the file handler is enabled since the file `https.md` has the expected custom icon, but the menu has no custom menu with the action "Add to ZIP file - debug" on the selected folder:

![image](https://user-images.githubusercontent.com/240925/65414480-1d9b8180-ddf4-11e9-82f3-8b7798a0e7ec.png)

[This](https://github.com/OneDrive/onedrive-api-docs/files/3641422/apps.txt) is the result for `GET /_api/v2.0/drive/apps?select=*,promoted&expand=actions`.

@JeremyKelley I'm still waiting for your feedback.

**Comment by patrick-rodgers** [comment] 2023-02-17 20:30
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:30 UTC
Labels: status:investigating, Needs: Attention :wave:, automation:Closed
