### ISSUE TITLE
oneDrive file picker page open in new tab instead in pop-up

### ISSUE THREAD

**Issue by OriAmir** [OneDrive/onedrive-api-docs#650] opened 2017-07-10 08:20 UTC
Hey , I use one drive file picker in my outlook add-in to get files from one-drive .
In chrome and IE browsers it's OK and open a pop-up to choose files and it's also was OK in Outlook rich client(Desktop) but now when I try it's open the browser and set the choose files page in new tab instead 
 to open a pop-up (what was until now ).
In version 7.0 it's open me in new tab the page of choose files and in version 7.2 it's open my the redirect page and I don't know why...

Something change? what I can do that it's again will open it in pop-up of the choose files page and not in new tab?

Thanks all!

**Comment by OriAmir** [comment] 2017-07-16 08:27
@daboxu someone could help maybe?

**Comment by daboxu** [comment] 2017-07-17 17:05
hi @OriAmir , could you share your options object passed to onedrive.open() call?

**Comment by OriAmir** [comment] 2017-07-18 10:16
Hi, this is my options:
 
  `         var odOptions = {

            clientId: "33890ba5-2f89-4e0b-9686-39251f3927a0",
            action: "download",
            multiSelect: true,
            linkType: "query",
            advanced: {},
            success: function (files) {},
        cancel: function () { /* cancel handler */
            },
            error: function (e) { /* error handler */
            }
        };
        OneDrive.open(odOptions);`


I try also version 7.2 and also 7.0

**Comment by daboxu** [comment] 2017-07-18 16:45
The option looks good, have you seen the login page in v7.2 SDK? What's the redirect's pages url with query parameters?

**Comment by OriAmir** [comment] 2017-07-19 10:09
**On 7.0:**
When I click the one drive button it's open a new tab in browser and open the one drive page to select files ,it's good but then when I select the redirection work because it's on new page and not return to my add-in.

**On 7.2:**
When I click the one drive button it's open a new tab in browser and open the redirect page that on apps.dev.microsoft.com portal and not show me at all the onedrive page..
This is the link it open on browser:
https://localhost:44382/MessageCompose.html?sdk_state=%7B%22optionsMode%22%3A%22open%22%2C%22options%22%3A%7B%22action%22%3A%22download%22%2C%22advanced%22%3A%7B%22redirectUri%22%3A%22https%3A%2F%2Flocalhost%3A44382%2FMessageCompose.html%22%7D%2C%22clientId%22%3A%2233890ba5-2f89-4e0b-9686-39251f3927a0%22%2C%22isSharePointRedirect%22%3Afalse%2C%22multiSelect%22%3Atrue%2C%22openInNewWindow%22%3Atrue%7D%7D&state=open_popup

On myapps.dev.microsoft.com under the ID I have 3 redirecrt url:
![image](https://user-images.githubusercontent.com/17565646/28362003-72d979c0-6c83-11e7-9d49-aa030ceb6541.png)
When the last one is where it's redirect..

I don't really understand why it's open in new tab at all?

Thank you very much again ! @daboxu

**Comment by daboxu** [comment] 2017-07-19 16:46
@OriAmir from the url I can tell you have sdk v7.0 attached on your redirect url, which you registered on the apps.dev.microsoft.com. Try attache SDK v7.2 in the url and set it as your redirecturi in the option
``` javascript
var options = {
        advanced : { redirectUri: //your uri registered on dev portal with v7.2 SDK
}
```

V7.0 and v7.2 have different redirect parameters when handling the oauth redirect and apparently the url currently uses v7.0 SDK. But I still don't know why it opens in a new tab though, the only place in SDK opens a new window using

```javascript
 window.open(url, '_blank', Popup.createPopupFeatures());
```

which has second parameter set to '_blank' so it should open in a popup. Try give it a shot and hope it works.

**Comment by OriAmir** [comment] 2017-07-20 15:45
@daboxu thank you very much first!
I set the new option and use version 7.2 and the only place it's work good it's on chrome .
In outlook desktop it's open new tab directly to my redirect I set on options :  localhost:44382/MessageCompose.html ... and not to oneDrive page..
What else I could do? In version 7.0 it's work good on all browsers ( chrome ,ie,edge ) in 7.2 only with chrome...

**Comment by daboxu** [comment] 2017-07-20 16:43
hmm, I am expecting you first redirect to your localhost:44382/MessageCompose.html?oauth={} with the query parameter `oauth` which is a config object for redirecting to oauth page in a popup... could you verify the redirection happened by capturing the http traffic? You shall be able to redirect to OneDrive after that. I tested in IE/Edge and it seems work for me testing app, but haven't got a chance to build an app as outlook plugin though.

**Comment by OriAmir** [comment] 2017-07-24 11:30
1.About IE/Edge I think it's again a internt secuirty settings that I have before ( options->secuirty and set 'v' on "enable protected mode") but this time it's not helped becuase it's now open the right window but then imeedtily close it and drop error to console:
![image](https://user-images.githubusercontent.com/17565646/28521251-69afc0c4-707b-11e7-872e-c7ae6b29ecb4.png)

and on screen:
![image](https://user-images.githubusercontent.com/17565646/28521448-64e2f920-707c-11e7-8f4b-6003e6ef6ed4.png)


About outlook add-in rich client : it's still open in new tab on default browser ( I try chrome , IE and edge) no matter what I try to do... Why it's behave diffrent? it's open it again with redirect address and not with one drive page:
https://localhost:44382/MessageCompose.html?oauth={"clientId":"33890ba5-2f89-4e0b-9686-39251f3927a0","endpoint":1,"scopes":["Files.Read.All"],"origin":"https://localhost:44382","redirectUri":"https://localhost:44382/MessageCompose.html","loginHint":"oamir@difenlabs.com","isConsumerAccount":false,"state":"https://localhost:44382_4eyjn"}


Thanks for your help @daboxu

**Comment by daboxu** [comment] 2017-07-24 21:48
for **IE/Edge** : could you please copy and go to the url in a new tab https://localhost:44382/MessageCompose.html?oauth={"clientId":"33890ba5-2f89-4e0b-9686-39251f3927a0","endpoint":1,"scopes":["Files.Read.All"],"origin":"https://localhost:44382","redirectUri":"https://localhost:44382/MessageCompose.html","loginHint":"oamir@difenlabs.com","isConsumerAccount":false,"state":"https://localhost:44382_4eyjn"} in IE to see what's error? In this way it will not close as it was in a popup page. 

for **outlook add-in**, that's expected because SDK needs to go through the OAuth endpoint to validate your app and get accesstoken granted by the logined user to allow you access their OneDrive file.

Both v7.0 and v7.2 use this redirect pattern, the different is v7.2 checks the `window.opener` object to see if it is in a popup or not, if window.opener is undefined, which I believe IE/Edge has some wired setting over it lead to you see you are blocked at the page.

**Comment by daboxu** [comment] 2017-07-24 22:02
After searching for a while and I found another approachable way is combining the use of 'MSAL' + 'express mode of picker SDK':

1. Follow the ['MSAL'](https://github.com/AzureAD/microsoft-authentication-library-for-js/) guide to get an access token with scope `profile openid https://graph.microsoft.com/User.Read https://graph.microsoft.com/File.Read.All`
2. If you know it's ODB user, make a API call to "https://graph.microsoft.com/v1.0/me?select=mySite" to get the ODB tenant url.
3. Provide your config to SDK like:
```javascript
var  options = {
    .....
    advanced : {
        accessToken: "<token you got>",
        endpointHint: "api.onedrive.com" for ODC or "the url you got in step 2" for ODB user.
    }
    ....
```

So in this way, the SDK will not invoke the oauth flow, instead, MSAL does it for you. SDK will redirect to ODC or ODB based on your config directly in a popup.

Let me know if it works for you or not. If it works, I will consider integrate the MSAL to let SDK consume in the future.

**Comment by OriAmir** [comment] 2017-07-26 15:14
I work and work to get 'MSAL'  authentication and try with access token I get from this..
It's now open the one drive without authentication but again it's work just in **chrome** .
Right not I see that the only option is to work with v7.0 and without outlook desktop , it's funny because it's work ok from there and now it's open from outlook desktop a new tab ..
And v7.2 not work at all instead chrome ...

Can I try something else? I try to fell 

Thank you very veyr much @daboxu

**Comment by daboxu** [comment] 2017-07-26 16:43
hmm, could you uncheck use build-in debugger by the IE checkbox? I haven't seem the error before.

**Comment by OriAmir** [comment] 2017-08-01 08:54
@daboxu  thanks thanks again!

_version 7.2_
IE/EDGE :

1. Open a pop-up with this url 
![image](https://user-images.githubusercontent.com/17565646/28816968-69bc0444-76af-11e7-85a6-b06143597e89.png)

2.URL change to this:
![image](https://user-images.githubusercontent.com/17565646/28817040-abbadcbc-76af-11e7-8cdd-078f7906e862.png)

3.Pop up close immediately.

* When the redirect uri on Microsoft app regression is: https://webservice-proto.difenso.com/AddinWord/DifensoWordAdd-InWeb/Home.html

* When I set :  advanced: { redirectUri: "https://webservice-proto.difenso.com/AddinWord/DifensoWordAdd-InWeb/Home.html" } so it's not close the pop-up it's show pop-up with my Home.html page..

**Comment by daboxu** [comment] 2017-08-21 16:36
hey @OriAmir , after resolving #671 I think probably that's could be caused by the curly bracelet in the url, could you give it a try or you can prove it without using the picker, just doing an popup redirect with curly bracelet in query params.

**Comment by OriAmir** [comment] 2017-08-23 08:45
@daboxu Hi,Thx but I don't understand what you exactly mean to ? You mean to set empty curly bracelet on 'redirectURI' paramtar or what?
`  var odOptions = {
            clientId: clientIdOneDrive,
            action: "download",
            multiSelect: true,
            linkType: "query",
            advanced: { redirectUri: "{}"
            } ...

Thx again!

**Comment by daboxu** [comment] 2017-08-23 16:46
hi @OriAmir ideally you should not change nothing at your side, the issue was the SDK generated the redirect url in the format like foo.com/bar?oauth={} which it looks like some browser cannot recognized the bracelet in the query parameters so the redirect flow doesn't work. My fix was to encode the uri component so the browser will not yell at the url.

**Comment by zachzi** [comment] 2018-03-30 21:08
Hi OriAmir,

If you're still experiencing this problem, please re-open this issue, and I'll investigate.

Thanks,
Zach

**Closed by zachzi** 2018-03-30 21:08 UTC
