### ISSUE TITLE
DriveItem Copy custom fields incorrectly copied

### ISSUE THREAD

**Issue by POFerro** [OneDrive/onedrive-api-docs#1122] opened 2019-08-12 18:34 UTC
Hi,

I'm trying to copy a folder from one site to another. 
My site list has a custom field which is a lookup field, after calling DriveItem copy: [https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_copy?view=odsp-graph-online](url) field values became quite weird on the target site list, on the source one of the items had this field with value and on the target all other documents had this value except the one that actually has the value on the source, it's weird but I believe something is not right with List Item Fields copy.
Please find attached the source and target folder screenshot so you can see what I'm talking about.
Can you have a look?

The capture from the request and response are here:
Request:
POST https://graph.microsoft.com/v1.0/drives/b!UWq_wnr1M0-BToTCv3wLXBlWX2IFrf5Hm2wVB1gdFqWaVoXKcZ1ITIwy8n3JdpB_/items/014TBJFKD5HMKOINVVZREYBL5MTTERDJPM/microsoft.graph.copy HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6IkpTVTh2N0pMQkxOTV9NczBnTkNWSTR3NlJWUWRBUmlmRUpnTFE2QkllQzgiLCJhbGciOiJSUzI1NiIsIng1dCI6InU0T2ZORlBId0VCb3NIanRyYXVPYlY4NExuWSIsImtpZCI6InU0T2ZORlBId0VCb3NIanRyYXVPYlY4NExuWSJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20vIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNGU5OWI4NWUtOWM2Mi00OGM0LThlM2UtZDBkZGE5ODgzMTc5LyIsImlhdCI6MTU2NTYzMzY0OCwibmJmIjoxNTY1NjMzNjQ4LCJleHAiOjE1NjU2Mzc1NDgsImFpbyI6IjQyRmdZQ2dMMTkxd0lqeXJYMkYzd3IycFozMHNBQT09IiwiYXBwX2Rpc3BsYXluYW1lIjoiRVBNIiwiYXBwaWQiOiIwMjBmZmZmNi1jMGIwLTRlOTItYThmYy05ZDUzNjg2YWZkZmIiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC80ZTk5Yjg1ZS05YzYyLTQ4YzQtOGUzZS1kMGRkYTk4ODMxNzkvIiwib2lkIjoiNWEyY2UzMWQtZDM0Yi00OTk4LWFjMDctMDI5MDUyNGRkZDFiIiwicm9sZXMiOlsiR3JvdXAuUmVhZFdyaXRlLkFsbCIsIlNpdGVzLk1hbmFnZS5BbGwiLCJGaWxlcy5SZWFkV3JpdGUuQWxsIiwiVXNlci5SZWFkLkFsbCJdLCJzdWIiOiI1YTJjZTMxZC1kMzRiLTQ5OTgtYWMwNy0wMjkwNTI0ZGRkMWIiLCJ0aWQiOiI0ZTk5Yjg1ZS05YzYyLTQ4YzQtOGUzZS1kMGRkYTk4ODMxNzkiLCJ1dGkiOiJrYnFDckpudmprbUNycHhsSS1jN0FBIiwidmVyIjoiMS4wIiwieG1zX3RjZHQiOjE0MTY1OTE1ODF9.ggNxUFtzF6ZlisNQY7yNKtCFTZGx9mi06mOfjLjHoN4sLRYbyr0TpcLYid9eGUQyJlbDptzKqb0dkgTVUnPtfcRZCK-H3cOE1wBxWMJEf8B4QKW0X9Kd0Dx7gpHjiv4Kq52e3KoKjE7j84Ykjyx08dqLS3Zy6Aok5NXXbwGSGTRxO-2cnVeZPY2QTjIw9a89e9eB8tKCnXgLFyF1hQPu3a-PbUH8pZW52c1UuOysucv7cdwN0CWwN__MU-JVyOKjBqet8vdVS9LaFKktQDEmzzW6wZDqc4obw19Ir7GCk5WwLxWxJbAoxx10r6at9erqcLvYLbpl0gtVbqYPVy4qGg
FeatureFlag: 00000008
Content-Type: application/json
Host: graph.microsoft.com
Content-Length: 142

{"parentReference":{"driveId":"b!aCYXcyklIkycPqtgpnxIV85CiNX1Wz1LpzJLJPG4AIEBcyJBzyUsS6xu05kHyXt6","id":"01KOR6ZB56Y2GOVW7725BZO354PWSELRRZ"}}

Response:
HTTP/1.1 202 Accepted
Cache-Control: private
Transfer-Encoding: chunked
Content-Type: text/plain
Location: https://novabase.sharepoint.com/sites/EPMTemplateGeneral/_api/v2.1/drives/b!UWq_wnr1M0-BToTCv3wLXBlWX2IFrf5Hm2wVB1gdFqWaVoXKcZ1ITIwy8n3JdpB_/operations/4b3a9e61-7a82-4a52-a8b6-1b1276e214dd?c=MXIrZnB4UFdwRlhWeUJ0WjFuM0MzblRVdis2dENHbklnNGhaWCthS2F1bz0jaHR0cHM6Ly9zcG9kYjFhbTFtMDE0cHIucXVldWUuY29yZS53aW5kb3dzLm5ldC8yNDMzcHEyMDE5MDgxMi1hMTM1ZDZiMTZjNmM0NWRmOGFhYTYwOGU4YTU1OWRkYz9zdj0yMDE3LTA3LTI5JnNpZz1HMiUyQnpqQzBnemRYSWFaZHRqbEloTlpLeFAwZ0t1YTNSNGM0ZXZ0VklIT1UlM0Qmc3Q9MjAxOS0wOC0xMVQwNyUzQTAwJTNBMDBaJnNlPTIwMTktMDktMDJUMDclM0EwMCUzQTAwWiZzcD1yYXA&v=2.0&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbm92YWJhc2Uuc2hhcmVwb2ludC5jb21ANGU5OWI4NWUtOWM2Mi00OGM0LThlM2UtZDBkZGE5ODgzMTc5IiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTU2NTYzMzk1MCIsImV4cCI6IjE1NjU3MjAzNTAiLCJlbmRwb2ludHVybCI6ImMxeHg2ZmlNdlA0NHF6Y2NkMjRNMDRVMWtHS2NtY0gveGpVSVRZLzdYMW89IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiI1NTYiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6IlpEZzFNamxoT1dRdE9UTmtZUzAwWXpkakxXSTNOMll0WXpNMllqZGpaV0ppWm1aaiIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJZekppWmpaaE5URXRaalUzWVMwMFpqTXpMVGd4TkdVdE9EUmpNbUptTjJNd1lqVmoiLCJhcHBfZGlzcGxheW5hbWUiOiJFUE0iLCJuYW1laWQiOiIwMjBmZmZmNi1jMGIwLTRlOTItYThmYy05ZDUzNjg2YWZkZmJANGU5OWI4NWUtOWM2Mi00OGM0LThlM2UtZDBkZGE5ODgzMTc5Iiwicm9sZXMiOiJncm91cC53cml0ZSBhbGxzaXRlcy5tYW5hZ2UgYWxsZmlsZXMud3JpdGUgYWxscHJvZmlsZXMucmVhZCIsInR0IjoiMSIsInVzZVBlcnNpc3RlbnRDb29raWUiOm51bGx9.RlQ1QndPWjBmZGg0cEgzdVBRVzhFb1Z6VGNMTHFMbm96bWoxSFBZWitRTT0
request-id: d8529a9d-93da-4c7c-b77f-c36b7cebbffc
client-request-id: d8529a9d-93da-4c7c-b77f-c36b7cebbffc
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"UK South","Slice":"SliceC","Ring":"5","ScaleUnit":"002","RoleInstance":"AGSFE_IN_3","ADSiteName":"UKS"}}
Duration: 1547.2796
Strict-Transport-Security: max-age=31536000
Date: Mon, 12 Aug 2019 18:19:09 GMT

Thanks and best regards.
![source](https://user-images.githubusercontent.com/4305113/62888982-5564d300-bd38-11e9-9675-34f812336f56.png)
![target](https://user-images.githubusercontent.com/4305113/62888983-5564d300-bd38-11e9-90cf-6a14e91b5b40.png)

**Comment by ificator** [comment] 2019-08-15 16:10
Hi @POFerro, here's what we heard back regarding your issue:

```
The source list seems to have a lookup field “Tipo de documento”, which is a taxonomy field. Copy/move do support global taxonomy lookup field if both source and target enabled the taxonomy. 
However, it seems the target list field “Tipo de documento” is not a taxonomy field. So it can’t apply the value to the 1st file which has a taxonomy value at source.
```
They suggest verifying that the target field “Tipo de documento” was created as a Managed Metadata field associated with the global terms store. If not, try reconfiguring it and copying again to see if the issue is resolved.

They're still investigating why the other documents got a value - is it possible that "Project Plan" is the default value for that column?

**Comment by POFerro** [comment] 2019-08-19 19:53
Hi @ificator ,

The field is a Lookup field, not a managed metadata field, also doesn't have a default value nor does it is required either, here is the field properties page:
![TipoDocumento_old](https://user-images.githubusercontent.com/4305113/63292804-70968c00-c2be-11e9-948d-a99b32b291bb.png)

Just to make sure of this I deleted that field and created a new clean one:
![TipoDocumento_new](https://user-images.githubusercontent.com/4305113/63292899-a471b180-c2be-11e9-95a1-fbb1bf11c59e.png)

Repeated the process and it happened just the same, now with different field values in target.
![Copy target](https://user-images.githubusercontent.com/4305113/63294768-0e8c5580-c2c3-11e9-998b-20c823c3d508.png)

Here are the captures:
Request:
POST https://graph.microsoft.com/v1.0/drives/b!UWq_wnr1M0-BToTCv3wLXBlWX2IFrf5Hm2wVB1gdFqWaVoXKcZ1ITIwy8n3JdpB_/items/014TBJFKD5HMKOINVVZREYBL5MTTERDJPM/microsoft.graph.copy HTTP/1.1
Authorization: Bearer ...
FeatureFlag: 00000008
Content-Type: application/json
Host: graph.microsoft.com
Content-Length: 142

{"parentReference":{"driveId":"b!UQhgnIX37U6f_bP768kuh85CiNX1Wz1LpzJLJPG4AIEBcyJBzyUsS6xu05kHyXt6","id":"01K5QOVEV6Y2GOVW7725BZO354PWSELRRZ"}}

Response:
HTTP/1.1 202 Accepted
Cache-Control: private
Content-Type: text/plain
Location: https://novabase.sharepoint.com/sites/EPMTemplateGeneral/_api/v2.1/drives/b!UWq_wnr1M0-BToTCv3wLXBlWX2IFrf5Hm2wVB1gdFqWaVoXKcZ1ITIwy8n3JdpB_/operations/07009ca0-e606-418b-9f2e-2c8bde9f5f26?c=VXZMQnU4c2xaMWFYNUN1dDFSQmo1WHZrTm13eXFQM0NjT3p0TTlCRzZyaz0jaHR0cHM6Ly9zcG9kYjFhbTFtMDE5cHIucXVldWUuY29yZS53aW5kb3dzLm5ldC8yNDMzcHEyMDE5MDgxOS1mNjY4NjQyZGI2Yjc0NDIzODk2NWEzMGY2ODBhM2YyNT9zdj0yMDE3LTA3LTI5JnNpZz02bE55S21sb1ByMkZoRTFkem51MDJzNGVFcmlrRTRzalBQNkZDcEVlQWY4JTNEJnN0PTIwMTktMDgtMThUMDclM0EwMCUzQTAwWiZzZT0yMDE5LTA5LTA5VDA3JTNBMDAlM0EwMFomc3A9cmFw&v=2.0&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbm92YWJhc2Uuc2hhcmVwb2ludC5jb21ANGU5OWI4NWUtOWM2Mi00OGM0LThlM2UtZDBkZGE5ODgzMTc5IiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTU2NjI0MzcwNCIsImV4cCI6IjE1NjYzMzAxMDQiLCJlbmRwb2ludHVybCI6IjZhdHErM2w5QTV6RzFvZDdBaGhQRVJyYitZYWhZNFFpWWo1RldEaW14R1k9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiI1NTMiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6IlkySmtaakUzT0RjdE1qa3dPUzAwWmpkaUxUbGlNbU10WlRnd05UZGtZamRsT1RrMCIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJZekppWmpaaE5URXRaalUzWVMwMFpqTXpMVGd4TkdVdE9EUmpNbUptTjJNd1lqVmoiLCJhcHBfZGlzcGxheW5hbWUiOiJFUE0iLCJuYW1laWQiOiIwMjBmZmZmNi1jMGIwLTRlOTItYThmYy05ZDUzNjg2YWZkZmJANGU5OWI4NWUtOWM2Mi00OGM0LThlM2UtZDBkZGE5ODgzMTc5Iiwicm9sZXMiOiJncm91cC53cml0ZSBhbGxzaXRlcy5tYW5hZ2UgYWxsZmlsZXMud3JpdGUgYWxscHJvZmlsZXMucmVhZCIsInR0IjoiMSIsInVzZVBlcnNpc3RlbnRDb29raWUiOm51bGx9.VUtTc0pxRmw0aUxTUTV4ZGYwYjJlTHlXWU1zT2dkaUpqa3BuT0xac1lWbz0
request-id: cbdf1787-2909-4f7b-9b2c-e8057db7e994
client-request-id: cbdf1787-2909-4f7b-9b2c-e8057db7e994
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceC","Ring":"5","ScaleUnit":"001","RoleInstance":"AGSFE_IN_19","ADSiteName":"WEU"}}
Duration: 1517.337
Strict-Transport-Security: max-age=31536000
Date: Mon, 19 Aug 2019 19:41:43 GMT
Content-Length: 0


Some more info, I'm copying documents between two different sites, both sites have their own fields, this particular field has the same name on both sites, each of the Tipo de Documento Field point to a lookup list that is local to each site, although they have the same name properties and items, physically they are different, in fact I was never sure if copy method was able to copy this field values, I was expecting it to be empty in the destination or filled with the correct values, not this random behavior.
 
Hope this helps
Thanks and best regards

**Comment by patrick-rodgers** [comment] 2023-02-17 20:32
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Closed by patrick-rodgers** 2023-02-17 20:32 UTC
Labels: status:investigating, automation:Closed
