### ISSUE TITLE
Can account user strict the app from being access or similar think

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [OneDrive/onedrive-api-docs#109] opened 2015-05-08 14:07 UTC
Is there by any way that account user can disable the app from the onedrive.com, so further the app cant access the account???

I tried to search on onedrive.com, but didnt find such thinks. but read somewhere this is possible...

So can we have information over this

**Comment by The-Lion** [comment] 2015-05-08 14:17
I can manage the App permissions via https://account.live.com/consent/Manage.

**Comment by ankit-ankuagrawal** [comment] 2015-05-08 14:40
@The-Lion ty for the response

after deleting the app permission from the above uri, i was still able to access onedrive apis from the api.

**Comment by ankit-ankuagrawal** [comment] 2015-05-08 16:41
it expired mostly after 1 hr...

first when requested GET /drive/root/children in response got 
"Operation Failed  message: Required authentication information is either missing or not valid for the resource json reply: code: unauthenticated | message: Authentication failed | innerError:    code: passportAuthFail"

it is like accessToken expired, so requesting for new accessToken using existing refreshToken

in response received "Operation Failed  |  json reply: error: invalid_grant | error_description: The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope."

this error havent controlled in error handling

it is requested to documentation for all possible scnerio in which refreshToken becames invalid, such when user change password and etc...

**Comment by rgregg** [comment] 2015-05-08 20:58
This sounds like the expected behavior. Access tokens are like passwords, they are valid for 1 hour from when they are created and cannot be revoked. If the user revokes access to the application, the refresh token is invalidated and cannot be used to generate new access tokens, but any still valid access tokens will work until they expire.

The main scenarios for a refresh token expiring are the three you've come up with: the token expires naturally, the user changes their password, or the permissions to the app are revoked.

**Comment by ankit-ankuagrawal** [comment] 2015-05-08 21:28
ty for the reply, have knowledge about the accessToken expiry in one hr,
but thought if they permission are revoked they should changed...

But was not sure in how many which scenerio refreshToken expires, but now
got the idea...

will do the handling based on this...

Sir can this be documented so tht other can used it...

**Comment by rgregg** [comment] 2015-05-29 17:25
Closing this out since it doesn't seem like there is something actionable here. I'll work on making the docs more clear about when refresh tokens can be invalidated.

**Closed** 2015-05-29 17:24 UTC

**Comment by ankit-ankuagrawal** [comment] 2015-05-29 17:27
@ryan sir ty for the reply
